#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : memcached-custom
Version  : 1.0
Release  : 2
URL      : file:///home/clear/tar/memcached-custom-1.0.tar.gz
Source0  : file:///home/clear/tar/memcached-custom-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: memcached-custom-services = %{version}-%{release}
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%package services
Summary: services components for the memcached-custom package.
Group: Systemd services

%description services
services components for the memcached-custom package.


%prep
%setup -q -n memcached-custom-1.0
%patch1 -p1

%build
## build_prepend content
%define _unitdir /usr/lib/systemd/system/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568618799
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568618799
rm -rf %{buildroot}
%{__install} -d %{buildroot}%{_unitdir}
## install_append content
%{__install} -m 644 -p memcached.service %{buildroot}%{_unitdir}/memcached.service
## install_append end

%files
%defattr(-,root,root,-)

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/memcached.service
