#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : resource-agents
Version  : 4.1.1
Release  : 1
URL      : file:///home/clear/Downloads/resource-agents-4.1.1.tar.gz
Source0  : file:///home/clear/Downloads/resource-agents-4.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1
Requires: resource-agents-bin = %{version}-%{release}
Requires: resource-agents-config = %{version}-%{release}
Requires: resource-agents-data = %{version}-%{release}
Requires: resource-agents-libexec = %{version}-%{release}
Requires: resource-agents-man = %{version}-%{release}
Requires: resource-agents-services = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
This repository contains resource agents (RAs) compliant
with the Open Cluster Framework (OCF) specification.

%package bin
Summary: bin components for the resource-agents package.
Group: Binaries
Requires: resource-agents-data = %{version}-%{release}
Requires: resource-agents-libexec = %{version}-%{release}
Requires: resource-agents-config = %{version}-%{release}
Requires: resource-agents-services = %{version}-%{release}

%description bin
bin components for the resource-agents package.


%package config
Summary: config components for the resource-agents package.
Group: Default

%description config
config components for the resource-agents package.


%package data
Summary: data components for the resource-agents package.
Group: Data

%description data
data components for the resource-agents package.


%package dev
Summary: dev components for the resource-agents package.
Group: Development
Requires: resource-agents-bin = %{version}-%{release}
Requires: resource-agents-data = %{version}-%{release}
Provides: resource-agents-devel = %{version}-%{release}
Requires: resource-agents = %{version}-%{release}

%description dev
dev components for the resource-agents package.


%package doc
Summary: doc components for the resource-agents package.
Group: Documentation
Requires: resource-agents-man = %{version}-%{release}

%description doc
doc components for the resource-agents package.


%package libexec
Summary: libexec components for the resource-agents package.
Group: Default
Requires: resource-agents-config = %{version}-%{release}

%description libexec
libexec components for the resource-agents package.


%package man
Summary: man components for the resource-agents package.
Group: Default

%description man
man components for the resource-agents package.


%package services
Summary: services components for the resource-agents package.
Group: Systemd services

%description services
services components for the resource-agents package.


%prep
%setup -q -n resource-agents-4.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566269751
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1566269751
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/ocf/lib/heartbeat/apache-conf.sh
/usr/lib/ocf/lib/heartbeat/findif.sh
/usr/lib/ocf/lib/heartbeat/http-mon.sh
/usr/lib/ocf/lib/heartbeat/lvm-clvm.sh
/usr/lib/ocf/lib/heartbeat/lvm-plain.sh
/usr/lib/ocf/lib/heartbeat/lvm-tag.sh
/usr/lib/ocf/lib/heartbeat/mysql-common.sh
/usr/lib/ocf/lib/heartbeat/nfsserver-redhat.sh
/usr/lib/ocf/lib/heartbeat/ocf-binaries
/usr/lib/ocf/lib/heartbeat/ocf-directories
/usr/lib/ocf/lib/heartbeat/ocf-distro
/usr/lib/ocf/lib/heartbeat/ocf-rarun
/usr/lib/ocf/lib/heartbeat/ocf-returncodes
/usr/lib/ocf/lib/heartbeat/ocf-shellfuncs
/usr/lib/ocf/lib/heartbeat/ora-common.sh
/usr/lib/ocf/lib/heartbeat/sapdb-nosha.sh
/usr/lib/ocf/lib/heartbeat/sapdb.sh
/usr/lib/ocf/resource.d/heartbeat/.ocf-binaries
/usr/lib/ocf/resource.d/heartbeat/.ocf-directories
/usr/lib/ocf/resource.d/heartbeat/.ocf-returncodes
/usr/lib/ocf/resource.d/heartbeat/.ocf-shellfuncs
/usr/lib/ocf/resource.d/heartbeat/AoEtarget
/usr/lib/ocf/resource.d/heartbeat/AudibleAlarm
/usr/lib/ocf/resource.d/heartbeat/CTDB
/usr/lib/ocf/resource.d/heartbeat/ClusterMon
/usr/lib/ocf/resource.d/heartbeat/Delay
/usr/lib/ocf/resource.d/heartbeat/Dummy
/usr/lib/ocf/resource.d/heartbeat/EvmsSCC
/usr/lib/ocf/resource.d/heartbeat/Evmsd
/usr/lib/ocf/resource.d/heartbeat/Filesystem
/usr/lib/ocf/resource.d/heartbeat/ICP
/usr/lib/ocf/resource.d/heartbeat/IPaddr
/usr/lib/ocf/resource.d/heartbeat/IPaddr2
/usr/lib/ocf/resource.d/heartbeat/IPsrcaddr
/usr/lib/ocf/resource.d/heartbeat/LVM
/usr/lib/ocf/resource.d/heartbeat/LVM-activate
/usr/lib/ocf/resource.d/heartbeat/LinuxSCSI
/usr/lib/ocf/resource.d/heartbeat/MailTo
/usr/lib/ocf/resource.d/heartbeat/ManageRAID
/usr/lib/ocf/resource.d/heartbeat/ManageVE
/usr/lib/ocf/resource.d/heartbeat/NodeUtilization
/usr/lib/ocf/resource.d/heartbeat/Pure-FTPd
/usr/lib/ocf/resource.d/heartbeat/Raid1
/usr/lib/ocf/resource.d/heartbeat/Route
/usr/lib/ocf/resource.d/heartbeat/SAPDatabase
/usr/lib/ocf/resource.d/heartbeat/SAPInstance
/usr/lib/ocf/resource.d/heartbeat/SendArp
/usr/lib/ocf/resource.d/heartbeat/ServeRAID
/usr/lib/ocf/resource.d/heartbeat/SphinxSearchDaemon
/usr/lib/ocf/resource.d/heartbeat/Squid
/usr/lib/ocf/resource.d/heartbeat/Stateful
/usr/lib/ocf/resource.d/heartbeat/SysInfo
/usr/lib/ocf/resource.d/heartbeat/VIPArip
/usr/lib/ocf/resource.d/heartbeat/VirtualDomain
/usr/lib/ocf/resource.d/heartbeat/WAS
/usr/lib/ocf/resource.d/heartbeat/WAS6
/usr/lib/ocf/resource.d/heartbeat/WinPopup
/usr/lib/ocf/resource.d/heartbeat/Xen
/usr/lib/ocf/resource.d/heartbeat/Xinetd
/usr/lib/ocf/resource.d/heartbeat/ZFS
/usr/lib/ocf/resource.d/heartbeat/anything
/usr/lib/ocf/resource.d/heartbeat/apache
/usr/lib/ocf/resource.d/heartbeat/asterisk
/usr/lib/ocf/resource.d/heartbeat/aws-vpc-move-ip
/usr/lib/ocf/resource.d/heartbeat/aws-vpc-route53
/usr/lib/ocf/resource.d/heartbeat/awseip
/usr/lib/ocf/resource.d/heartbeat/awsvip
/usr/lib/ocf/resource.d/heartbeat/azure-lb
/usr/lib/ocf/resource.d/heartbeat/clvm
/usr/lib/ocf/resource.d/heartbeat/conntrackd
/usr/lib/ocf/resource.d/heartbeat/db2
/usr/lib/ocf/resource.d/heartbeat/dhcpd
/usr/lib/ocf/resource.d/heartbeat/dnsupdate
/usr/lib/ocf/resource.d/heartbeat/docker
/usr/lib/ocf/resource.d/heartbeat/eDir88
/usr/lib/ocf/resource.d/heartbeat/ethmonitor
/usr/lib/ocf/resource.d/heartbeat/exportfs
/usr/lib/ocf/resource.d/heartbeat/fio
/usr/lib/ocf/resource.d/heartbeat/galera
/usr/lib/ocf/resource.d/heartbeat/garbd
/usr/lib/ocf/resource.d/heartbeat/iSCSILogicalUnit
/usr/lib/ocf/resource.d/heartbeat/iSCSITarget
/usr/lib/ocf/resource.d/heartbeat/ids
/usr/lib/ocf/resource.d/heartbeat/iface-bridge
/usr/lib/ocf/resource.d/heartbeat/iface-vlan
/usr/lib/ocf/resource.d/heartbeat/ipsec
/usr/lib/ocf/resource.d/heartbeat/iscsi
/usr/lib/ocf/resource.d/heartbeat/jboss
/usr/lib/ocf/resource.d/heartbeat/jira
/usr/lib/ocf/resource.d/heartbeat/kamailio
/usr/lib/ocf/resource.d/heartbeat/ldirectord
/usr/lib/ocf/resource.d/heartbeat/lvmlockd
/usr/lib/ocf/resource.d/heartbeat/lxc
/usr/lib/ocf/resource.d/heartbeat/lxd-info
/usr/lib/ocf/resource.d/heartbeat/machine-info
/usr/lib/ocf/resource.d/heartbeat/mariadb
/usr/lib/ocf/resource.d/heartbeat/minio
/usr/lib/ocf/resource.d/heartbeat/mpathpersist
/usr/lib/ocf/resource.d/heartbeat/mysql
/usr/lib/ocf/resource.d/heartbeat/mysql-proxy
/usr/lib/ocf/resource.d/heartbeat/nagios
/usr/lib/ocf/resource.d/heartbeat/named
/usr/lib/ocf/resource.d/heartbeat/nfsnotify
/usr/lib/ocf/resource.d/heartbeat/nfsserver
/usr/lib/ocf/resource.d/heartbeat/nginx
/usr/lib/ocf/resource.d/heartbeat/oraasm
/usr/lib/ocf/resource.d/heartbeat/oracle
/usr/lib/ocf/resource.d/heartbeat/oralsnr
/usr/lib/ocf/resource.d/heartbeat/ovsmonitor
/usr/lib/ocf/resource.d/heartbeat/pgagent
/usr/lib/ocf/resource.d/heartbeat/pgsql
/usr/lib/ocf/resource.d/heartbeat/pingd
/usr/lib/ocf/resource.d/heartbeat/portblock
/usr/lib/ocf/resource.d/heartbeat/postfix
/usr/lib/ocf/resource.d/heartbeat/pound
/usr/lib/ocf/resource.d/heartbeat/proftpd
/usr/lib/ocf/resource.d/heartbeat/rabbitmq-cluster
/usr/lib/ocf/resource.d/heartbeat/redis
/usr/lib/ocf/resource.d/heartbeat/rkt
/usr/lib/ocf/resource.d/heartbeat/rsyncd
/usr/lib/ocf/resource.d/heartbeat/rsyslog
/usr/lib/ocf/resource.d/heartbeat/scsi2reservation
/usr/lib/ocf/resource.d/heartbeat/sfex
/usr/lib/ocf/resource.d/heartbeat/sg_persist
/usr/lib/ocf/resource.d/heartbeat/slapd
/usr/lib/ocf/resource.d/heartbeat/symlink
/usr/lib/ocf/resource.d/heartbeat/syslog-ng
/usr/lib/ocf/resource.d/heartbeat/tomcat
/usr/lib/ocf/resource.d/heartbeat/varnish
/usr/lib/ocf/resource.d/heartbeat/vmware
/usr/lib/ocf/resource.d/heartbeat/vsftpd
/usr/lib/ocf/resource.d/heartbeat/zabbixserver
/usr/lib/ocf/resource.d/redhat

%files bin
%defattr(-,root,root,-)
/usr/bin/ldirectord
/usr/bin/ocf-tester
/usr/bin/ocft
/usr/bin/rhev-check.sh

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/resource-agents.conf

%files data
%defattr(-,root,root,-)
/usr/share/cluster/ASEHAagent.sh
/usr/share/cluster/SAPDatabase
/usr/share/cluster/SAPInstance
/usr/share/cluster/apache.metadata
/usr/share/cluster/apache.sh
/usr/share/cluster/bind-mount.sh
/usr/share/cluster/clusterfs.sh
/usr/share/cluster/db2.sh
/usr/share/cluster/drbd.metadata
/usr/share/cluster/drbd.sh
/usr/share/cluster/fs.sh
/usr/share/cluster/ip.sh
/usr/share/cluster/lvm.metadata
/usr/share/cluster/lvm.sh
/usr/share/cluster/lvm_by_lv.sh
/usr/share/cluster/lvm_by_vg.sh
/usr/share/cluster/mysql.metadata
/usr/share/cluster/mysql.sh
/usr/share/cluster/named.metadata
/usr/share/cluster/named.sh
/usr/share/cluster/netfs.sh
/usr/share/cluster/nfsclient.sh
/usr/share/cluster/nfsexport.sh
/usr/share/cluster/nfsserver.sh
/usr/share/cluster/ocf-shellfuncs
/usr/share/cluster/openldap.metadata
/usr/share/cluster/openldap.sh
/usr/share/cluster/oracledb.sh
/usr/share/cluster/oradg.metadata
/usr/share/cluster/oradg.sh
/usr/share/cluster/orainstance.metadata
/usr/share/cluster/orainstance.sh
/usr/share/cluster/oralistener.metadata
/usr/share/cluster/oralistener.sh
/usr/share/cluster/postgres-8.metadata
/usr/share/cluster/postgres-8.sh
/usr/share/cluster/relaxng/ra-api-1-modified.dtd
/usr/share/cluster/relaxng/ra2man.xsl
/usr/share/cluster/relaxng/ra2ref.xsl
/usr/share/cluster/relaxng/ra2rng.xsl
/usr/share/cluster/relaxng/resources.rng.head
/usr/share/cluster/relaxng/resources.rng.mid
/usr/share/cluster/relaxng/resources.rng.tail
/usr/share/cluster/samba.metadata
/usr/share/cluster/samba.sh
/usr/share/cluster/script.sh
/usr/share/cluster/service.sh
/usr/share/cluster/smb.sh
/usr/share/cluster/svclib_nfslock
/usr/share/cluster/tomcat-5.metadata
/usr/share/cluster/tomcat-5.sh
/usr/share/cluster/tomcat-6.metadata
/usr/share/cluster/tomcat-6.sh
/usr/share/cluster/utils/config-utils.sh
/usr/share/cluster/utils/fs-lib.sh
/usr/share/cluster/utils/httpd-parse-config.pl
/usr/share/cluster/utils/member_util.sh
/usr/share/cluster/utils/messages.sh
/usr/share/cluster/utils/named-parse-config.pl
/usr/share/cluster/utils/ra-skelet.sh
/usr/share/cluster/utils/tomcat-parse-config.pl
/usr/share/cluster/vm.sh
/usr/share/resource-agents/metadata.rng
/usr/share/resource-agents/ocft/README
/usr/share/resource-agents/ocft/README.zh_CN
/usr/share/resource-agents/ocft/caselib
/usr/share/resource-agents/ocft/configs/Filesystem
/usr/share/resource-agents/ocft/configs/IPaddr2
/usr/share/resource-agents/ocft/configs/IPaddr2v4
/usr/share/resource-agents/ocft/configs/IPaddr2v6
/usr/share/resource-agents/ocft/configs/IPsrcaddr
/usr/share/resource-agents/ocft/configs/IPv6addr
/usr/share/resource-agents/ocft/configs/LVM
/usr/share/resource-agents/ocft/configs/MailTo
/usr/share/resource-agents/ocft/configs/Raid1
/usr/share/resource-agents/ocft/configs/SendArp
/usr/share/resource-agents/ocft/configs/VirtualDomain
/usr/share/resource-agents/ocft/configs/Xen
/usr/share/resource-agents/ocft/configs/Xinetd
/usr/share/resource-agents/ocft/configs/apache
/usr/share/resource-agents/ocft/configs/db2
/usr/share/resource-agents/ocft/configs/drbd.linbit
/usr/share/resource-agents/ocft/configs/exportfs
/usr/share/resource-agents/ocft/configs/exportfs-multidir
/usr/share/resource-agents/ocft/configs/iscsi
/usr/share/resource-agents/ocft/configs/jboss
/usr/share/resource-agents/ocft/configs/mysql
/usr/share/resource-agents/ocft/configs/mysql-proxy
/usr/share/resource-agents/ocft/configs/named
/usr/share/resource-agents/ocft/configs/nfsserver
/usr/share/resource-agents/ocft/configs/oracle
/usr/share/resource-agents/ocft/configs/pgsql
/usr/share/resource-agents/ocft/configs/portblock
/usr/share/resource-agents/ocft/configs/postfix
/usr/share/resource-agents/ocft/configs/sg_persist
/usr/share/resource-agents/ocft/configs/tomcat
/usr/share/resource-agents/ocft/helpers.sh
/usr/share/resource-agents/ocft/runocft
/usr/share/resource-agents/ocft/runocft.prereq
/usr/share/resource-agents/ra-api-1.dtd

%files dev
%defattr(-,root,root,-)
/usr/include/heartbeat/agent_config.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/resource\-agents/*

%files libexec
%defattr(-,root,root,-)
/usr/libexec/heartbeat/findif
/usr/libexec/heartbeat/send_arp
/usr/libexec/heartbeat/send_ua
/usr/libexec/heartbeat/tickle_tcp

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/ocf_heartbeat_AoEtarget.7
/usr/share/man/man7/ocf_heartbeat_AudibleAlarm.7
/usr/share/man/man7/ocf_heartbeat_CTDB.7
/usr/share/man/man7/ocf_heartbeat_ClusterMon.7
/usr/share/man/man7/ocf_heartbeat_Delay.7
/usr/share/man/man7/ocf_heartbeat_Dummy.7
/usr/share/man/man7/ocf_heartbeat_EvmsSCC.7
/usr/share/man/man7/ocf_heartbeat_Evmsd.7
/usr/share/man/man7/ocf_heartbeat_Filesystem.7
/usr/share/man/man7/ocf_heartbeat_ICP.7
/usr/share/man/man7/ocf_heartbeat_IPaddr.7
/usr/share/man/man7/ocf_heartbeat_IPaddr2.7
/usr/share/man/man7/ocf_heartbeat_IPsrcaddr.7
/usr/share/man/man7/ocf_heartbeat_LVM-activate.7
/usr/share/man/man7/ocf_heartbeat_LVM.7
/usr/share/man/man7/ocf_heartbeat_LinuxSCSI.7
/usr/share/man/man7/ocf_heartbeat_MailTo.7
/usr/share/man/man7/ocf_heartbeat_ManageRAID.7
/usr/share/man/man7/ocf_heartbeat_ManageVE.7
/usr/share/man/man7/ocf_heartbeat_NodeUtilization.7
/usr/share/man/man7/ocf_heartbeat_Pure-FTPd.7
/usr/share/man/man7/ocf_heartbeat_Raid1.7
/usr/share/man/man7/ocf_heartbeat_Route.7
/usr/share/man/man7/ocf_heartbeat_SAPDatabase.7
/usr/share/man/man7/ocf_heartbeat_SAPInstance.7
/usr/share/man/man7/ocf_heartbeat_SendArp.7
/usr/share/man/man7/ocf_heartbeat_ServeRAID.7
/usr/share/man/man7/ocf_heartbeat_SphinxSearchDaemon.7
/usr/share/man/man7/ocf_heartbeat_Squid.7
/usr/share/man/man7/ocf_heartbeat_Stateful.7
/usr/share/man/man7/ocf_heartbeat_SysInfo.7
/usr/share/man/man7/ocf_heartbeat_VIPArip.7
/usr/share/man/man7/ocf_heartbeat_VirtualDomain.7
/usr/share/man/man7/ocf_heartbeat_WAS.7
/usr/share/man/man7/ocf_heartbeat_WAS6.7
/usr/share/man/man7/ocf_heartbeat_WinPopup.7
/usr/share/man/man7/ocf_heartbeat_Xen.7
/usr/share/man/man7/ocf_heartbeat_Xinetd.7
/usr/share/man/man7/ocf_heartbeat_anything.7
/usr/share/man/man7/ocf_heartbeat_apache.7
/usr/share/man/man7/ocf_heartbeat_asterisk.7
/usr/share/man/man7/ocf_heartbeat_aws-vpc-move-ip.7
/usr/share/man/man7/ocf_heartbeat_aws-vpc-route53.7
/usr/share/man/man7/ocf_heartbeat_awseip.7
/usr/share/man/man7/ocf_heartbeat_awsvip.7
/usr/share/man/man7/ocf_heartbeat_azure-lb.7
/usr/share/man/man7/ocf_heartbeat_clvm.7
/usr/share/man/man7/ocf_heartbeat_conntrackd.7
/usr/share/man/man7/ocf_heartbeat_db2.7
/usr/share/man/man7/ocf_heartbeat_dhcpd.7
/usr/share/man/man7/ocf_heartbeat_dnsupdate.7
/usr/share/man/man7/ocf_heartbeat_docker.7
/usr/share/man/man7/ocf_heartbeat_eDir88.7
/usr/share/man/man7/ocf_heartbeat_ethmonitor.7
/usr/share/man/man7/ocf_heartbeat_exportfs.7
/usr/share/man/man7/ocf_heartbeat_fio.7
/usr/share/man/man7/ocf_heartbeat_galera.7
/usr/share/man/man7/ocf_heartbeat_garbd.7
/usr/share/man/man7/ocf_heartbeat_iSCSILogicalUnit.7
/usr/share/man/man7/ocf_heartbeat_iSCSITarget.7
/usr/share/man/man7/ocf_heartbeat_ids.7
/usr/share/man/man7/ocf_heartbeat_iface-bridge.7
/usr/share/man/man7/ocf_heartbeat_iface-vlan.7
/usr/share/man/man7/ocf_heartbeat_ipsec.7
/usr/share/man/man7/ocf_heartbeat_iscsi.7
/usr/share/man/man7/ocf_heartbeat_jboss.7
/usr/share/man/man7/ocf_heartbeat_jira.7
/usr/share/man/man7/ocf_heartbeat_kamailio.7
/usr/share/man/man7/ocf_heartbeat_lvmlockd.7
/usr/share/man/man7/ocf_heartbeat_lxc.7
/usr/share/man/man7/ocf_heartbeat_lxd-info.7
/usr/share/man/man7/ocf_heartbeat_machine-info.7
/usr/share/man/man7/ocf_heartbeat_mariadb.7
/usr/share/man/man7/ocf_heartbeat_mpathpersist.7
/usr/share/man/man7/ocf_heartbeat_mysql-proxy.7
/usr/share/man/man7/ocf_heartbeat_mysql.7
/usr/share/man/man7/ocf_heartbeat_nagios.7
/usr/share/man/man7/ocf_heartbeat_named.7
/usr/share/man/man7/ocf_heartbeat_nfsnotify.7
/usr/share/man/man7/ocf_heartbeat_nfsserver.7
/usr/share/man/man7/ocf_heartbeat_nginx.7
/usr/share/man/man7/ocf_heartbeat_oraasm.7
/usr/share/man/man7/ocf_heartbeat_oracle.7
/usr/share/man/man7/ocf_heartbeat_oralsnr.7
/usr/share/man/man7/ocf_heartbeat_ovsmonitor.7
/usr/share/man/man7/ocf_heartbeat_pgsql.7
/usr/share/man/man7/ocf_heartbeat_pingd.7
/usr/share/man/man7/ocf_heartbeat_portblock.7
/usr/share/man/man7/ocf_heartbeat_postfix.7
/usr/share/man/man7/ocf_heartbeat_pound.7
/usr/share/man/man7/ocf_heartbeat_proftpd.7
/usr/share/man/man7/ocf_heartbeat_rabbitmq-cluster.7
/usr/share/man/man7/ocf_heartbeat_redis.7
/usr/share/man/man7/ocf_heartbeat_rsyncd.7
/usr/share/man/man7/ocf_heartbeat_rsyslog.7
/usr/share/man/man7/ocf_heartbeat_scsi2reservation.7
/usr/share/man/man7/ocf_heartbeat_sfex.7
/usr/share/man/man7/ocf_heartbeat_sg_persist.7
/usr/share/man/man7/ocf_heartbeat_slapd.7
/usr/share/man/man7/ocf_heartbeat_symlink.7
/usr/share/man/man7/ocf_heartbeat_syslog-ng.7
/usr/share/man/man7/ocf_heartbeat_tomcat.7
/usr/share/man/man7/ocf_heartbeat_varnish.7
/usr/share/man/man7/ocf_heartbeat_vmware.7
/usr/share/man/man7/ocf_heartbeat_zabbixserver.7
/usr/share/man/man8/ldirectord.8
/usr/share/man/man8/ocf-tester.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/ldirectord.service
/usr/lib/systemd/system/resource-agents-deps.target
