#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : distributedcloud
Version  : 1.0.0
Release  : 7
URL      : file:///home/clear/clearlinux/packages/distributedcloud/distributedcloud-1.0.0.tar.gz
Source0  : file:///home/clear/clearlinux/packages/distributedcloud/distributedcloud-1.0.0.tar.gz
Source1  : dcdbsync-api.service
Source2  : dcmanager-api.service
Source3  : dcmanager-manager.service
Source4  : dcorch-api.service
Source5  : dcorch-engine.service
Source6  : dcorch-identity-api-proxy.service
Source7  : dcorch-snmp.service
Source8  : dcorch-sysinv-api-proxy.service
Source9  : file:///home/clear/clearlinux/packages/distributedcloud/conf.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: distributedcloud-bin = %{version}-%{release}
Requires: distributedcloud-python = %{version}-%{release}
Requires: distributedcloud-python3 = %{version}-%{release}
Requires: distributedcloud-services = %{version}-%{release}
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pbr-python
BuildRequires : pip
BuildRequires : setuptools

%description
This is a database migration repository.
More information at
http://code.google.com/p/sqlalchemy-migrate/

%package bin
Summary: bin components for the distributedcloud package.
Group: Binaries
Requires: distributedcloud-services = %{version}-%{release}

%description bin
bin components for the distributedcloud package.


%package python
Summary: python components for the distributedcloud package.
Group: Default
Requires: distributedcloud-python3 = %{version}-%{release}

%description python
python components for the distributedcloud package.


%package python3
Summary: python3 components for the distributedcloud package.
Group: Default
Requires: python3-core

%description python3
python3 components for the distributedcloud package.


%package services
Summary: services components for the distributedcloud package.
Group: Systemd services

%description services
services components for the distributedcloud package.


%prep
%setup -q -n distributedcloud-1.0.0
cd ..
%setup -q -T -D -n distributedcloud-1.0.0 -b 9

%build
## build_prepend content
%define _sysconfdir /usr/local/etc/
export PBR_VERSION=%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568100949
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pwd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/dcdbsync-api.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/dcmanager-api.service
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/systemd/system/dcmanager-manager.service
install -m 0644 %{SOURCE4} %{buildroot}/usr/lib/systemd/system/dcorch-api.service
install -m 0644 %{SOURCE5} %{buildroot}/usr/lib/systemd/system/dcorch-engine.service
install -m 0644 %{SOURCE6} %{buildroot}/usr/lib/systemd/system/dcorch-identity-api-proxy.service
install -m 0644 %{SOURCE7} %{buildroot}/usr/lib/systemd/system/dcorch-snmp.service
install -m 0644 %{SOURCE8} %{buildroot}/usr/lib/systemd/system/dcorch-sysinv-api-proxy.service
## install_append content
install -d -m 755 %{buildroot}%{_tmpfilesdir}
install -d -m 755 %{buildroot}/var/log/dcmanager
install -d -m 755 %{buildroot}/var/cache/dcmanager
install -d -m 755 %{buildroot}%{_sysconfdir}/dcmanager/
tar -xvJf %{SOURCE9}
install -p -D -m 644 dcmanager.conf %{buildroot}%{_tmpfilesdir}
install -p -D -m 640 dcmanager.conf %{buildroot}%{_sysconfdir}/dcmanager/dcmanager.conf
install -d -m 755 %{buildroot}/var/log/dcorch
install -d -m 755 %{buildroot}/var/cache/dcorch
install -d -m 755 %{buildroot}%{_sysconfdir}/dcorch/
install -p -D -m 644 dcorch.conf %{buildroot}%{_tmpfilesdir}
install -p -D -m 640 dcorch.conf %{buildroot}%{_sysconfdir}/dcorch/dcorch.conf
install -d -m 755 %{buildroot}/var/log/dcdbsync
install -d -m 755 %{buildroot}/var/cache/dcdbsync
install -d -m 755 %{buildroot}%{_sysconfdir}/dcdbsync/
install -p -D -m 644 dcdbsync.conf %{buildroot}%{_tmpfilesdir}
install -p -D -m 640 dcdbsync.conf %{buildroot}%{_sysconfdir}/dcdbsync/dcdbsync.conf
install -d -m 755 ${RPM_BUILD_ROOT}/usr/lib/ocf/resource.d/openstack
install -p -D -m 755 ocf/* ${RPM_BUILD_ROOT}/usr/lib/ocf/resource.d/openstack/
install -d -m 600 ${RPM_BUILD_ROOT}/opt/dc/ansible
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/ocf/resource.d/openstack/dcdbsync-api
/usr/lib/ocf/resource.d/openstack/dcmanager-api
/usr/lib/ocf/resource.d/openstack/dcmanager-manager
/usr/lib/ocf/resource.d/openstack/dcorch-cinder-api-proxy
/usr/lib/ocf/resource.d/openstack/dcorch-engine
/usr/lib/ocf/resource.d/openstack/dcorch-identity-api-proxy
/usr/lib/ocf/resource.d/openstack/dcorch-neutron-api-proxy
/usr/lib/ocf/resource.d/openstack/dcorch-nova-api-proxy
/usr/lib/ocf/resource.d/openstack/dcorch-patch-api-proxy
/usr/lib/ocf/resource.d/openstack/dcorch-snmp
/usr/lib/ocf/resource.d/openstack/dcorch-sysinv-api-proxy
/usr/local/etc/dcdbsync/dcdbsync.conf
/usr/local/etc/dcmanager/dcmanager.conf
/usr/local/etc/dcorch/dcorch.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/dcdbsync-api
/usr/bin/dcmanager-api
/usr/bin/dcmanager-manage
/usr/bin/dcmanager-manager
/usr/bin/dcorch-api
/usr/bin/dcorch-api-proxy
/usr/bin/dcorch-engine
/usr/bin/dcorch-manage
/usr/bin/dcorch-snmp

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/dcdbsync-api.service
/usr/lib/systemd/system/dcmanager-api.service
/usr/lib/systemd/system/dcmanager-manager.service
/usr/lib/systemd/system/dcorch-api.service
/usr/lib/systemd/system/dcorch-engine.service
/usr/lib/systemd/system/dcorch-identity-api-proxy.service
/usr/lib/systemd/system/dcorch-snmp.service
/usr/lib/systemd/system/dcorch-sysinv-api-proxy.service
