PKG_NAME := distributedcloud
URL = file:///home/clear/clearlinux/packages/distributedcloud/distributedcloud-1.0.0.tar.gz
ARCHIVES = file:///home/clear/clearlinux/packages/distributedcloud/conf.tar.xz : 

include ../common/Makefile.common
