#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : etcd
Version  : 3.2.24
Release  : 2
URL      : file:///home/clear/tar/etcd-v3.2.24.tar.gz
Source0  : file:///home/clear/tar/etcd-v3.2.24.tar.gz
Source1  : etcd.service
Source2  : file:///home/clear/tar/etcd.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: etcd-bin = %{version}-%{release}
Requires: etcd-services = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : libpcap-devel
BuildRequires : systemd
Patch1: bz1350875-disaster-recovery-with-copies.patch
Patch2: expand-etcd-arch-validation.patch

%description
To generate bad certs
1. Manually set system time back to past
2. Run ./gencerts.sh

%package bin
Summary: bin components for the etcd package.
Group: Binaries
Requires: etcd-services = %{version}-%{release}

%description bin
bin components for the etcd package.


%package services
Summary: services components for the etcd package.
Group: Systemd services

%description services
services components for the etcd package.


%prep
%setup -q -n etcd-v3.2.24
cd ..
%setup -q -T -D -n etcd-v3.2.24 -b 2
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
%define _sysconfdir /usr/local/etc
%define _unitdir /usr/lib/systemd/system/
%global provider        github
%global provider_tld    com
%global project         coreos
%global repo            etcd
%global provider_prefix %{provider}.%{provider_tld}/%{project}/%{repo}
%global import_path     %{provider_prefix}
%global commit          1674e682fe9fbecd66e9f20b77da852ad7f517a9
%global shortcommit     %(c=%{commit}; echo ${c:0:7})
%global system_name     etcd
mkdir -p src/
mv cmd/vendor/* $(pwd)/src
rm -rf src/github.com/coreos/etcd
ln -s ../../../ src/github.com/coreos/etcd
export GOPATH=$(pwd)
go build -o bin/%{system_name}ctl %{import_path}/%{system_name}ctl
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GOPATH="$PWD"
go build -o bin/%{system_name} %{import_path}

%install
rm -rf %{buildroot}

mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/etcd.service
## install_append content
install -D -p -m 0755 bin/%{system_name} %{buildroot}%{_bindir}/%{system_name}
install -D -p -m 0755 bin/%{system_name}ctl %{buildroot}%{_bindir}/%{system_name}ctl
install -d -m 0755 %{buildroot}%{_sysconfdir}/%{system_name}
tar -xzvf %{SOURCE2}
install -m 644 -t %{buildroot}%{_sysconfdir}/%{system_name} etcd.conf
install -d -m 0755 %{buildroot}%{_sharedstatedir}/%{system_name}
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/etcd/etcd.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/etcd
/usr/bin/etcdctl

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/etcd.service
