#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : controllerconfig
Version  : 1.0
Release  : 3
URL      : file:///home/clear/tar/controllerconfig-1.0.tar.gz
Source0  : file:///home/clear/tar/controllerconfig-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: controllerconfig-bin = %{version}-%{release}
Requires: controllerconfig-python = %{version}-%{release}
Requires: controllerconfig-python3 = %{version}-%{release}
Requires: fm-api
Requires: iso8601
Requires: keyring
Requires: netaddr
Requires: netifaces
Requires: oslo.utils
Requires: psmisc
Requires: pycrypto
Requires: pysnmp
Requires: pyudev
Requires: ruamel.yaml
Requires: six
Requires: sysinv
Requires: systemd
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
No detailed description available

%package bin
Summary: bin components for the controllerconfig package.
Group: Binaries

%description bin
bin components for the controllerconfig package.


%package python
Summary: python components for the controllerconfig package.
Group: Default
Requires: controllerconfig-python3 = %{version}-%{release}

%description python
python components for the controllerconfig package.


%package python3
Summary: python3 components for the controllerconfig package.
Group: Default
Requires: python3-core

%description python3
python3 components for the controllerconfig package.


%prep
%setup -q -n controllerconfig-1.0

%build
## build_prepend content
%define local_dir /usr/
%define local_bindir %{local_dir}/bin/
%define local_etc_initd /usr/local/etc/init.d/
%define local_goenabledd /usr/local/etc/goenabled.d/
%define local_etc_upgraded /usr/local/etc/upgrade.d/
%define local_etc_systemd /usr/local/etc/systemd/system/
%define pythonroot /usr/lib64/python2.7/site-packages
%define debug_package %{nil}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567129960
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
%{__python} setup.py install --root=$RPM_BUILD_ROOT \
--install-lib=%{pythonroot} \
--prefix=/usr \
--install-data=/usr/share \
--single-version-externally-managed
install -d -m 755 %{buildroot}%{local_bindir}
install -p -D -m 700 scripts/keyringstaging %{buildroot}%{local_bindir}/keyringstaging
install -p -D -m 700 scripts/openstack_update_admin_password %{buildroot}%{local_bindir}/openstack_update_admin_password
install -p -D -m 700 scripts/install_clone.py %{buildroot}%{local_bindir}/install_clone
install -p -D -m 700 scripts/finish_install_clone.sh %{buildroot}%{local_bindir}/finish_install_clone.sh
install -d -m 755 %{buildroot}%{local_goenabledd}
install -p -D -m 700 scripts/config_goenabled_check.sh %{buildroot}%{local_goenabledd}/config_goenabled_check.sh
install -d -m 755 %{buildroot}%{local_etc_initd}
install -p -D -m 755 scripts/controller_config %{buildroot}%{local_etc_initd}/controller_config
install -d -m 755 %{buildroot}%{local_etc_upgraded}
install -p -D -m 755 upgrade-scripts/* %{buildroot}%{local_etc_upgraded}/
install -d -m 755 %{buildroot}%{local_etc_systemd}
install -p -D -m 664 scripts/controllerconfig.service %{buildroot}%{local_etc_systemd}/controllerconfig.service
%post
systemctl enable controllerconfig.service
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/goenabled.d/config_goenabled_check.sh
/usr/local/etc/init.d/controller_config
/usr/local/etc/systemd/system/controllerconfig.service
/usr/local/etc/upgrade.d/16-neutron-move-bindings-off-controller-1.py
/usr/local/etc/upgrade.d/20-sysinv-retire-ceph-cache-tier-sp.py

%files bin
%defattr(-,root,root,-)
/usr/bin/config_controller
/usr/bin/config_management
/usr/bin/config_region
/usr/bin/config_subcloud
/usr/bin/finish_install_clone.sh
/usr/bin/install_clone
/usr/bin/keyringstaging
/usr/bin/openstack_update_admin_password
/usr/bin/tidy_storage_post_restore
/usr/bin/upgrade_controller
/usr/bin/upgrade_controller_simplex

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
