#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : systemd-config
Version  : 1.0
Release  : 3
URL      : file:///home/clr/stx-tar/systemd-config-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/systemd-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: systemd-config-data = %{version}-%{release}
Requires: systemd
BuildRequires : systemd
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package data
Summary: data components for the systemd-config package.
Group: Data

%description data
data components for the systemd-config package.


%prep
%setup -q -n systemd-config-1.0
%patch1 -p1

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir	/usr/local/etc
%define _unitdir /usr/lib/systemd/system/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568257646
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568257646
rm -rf %{buildroot}
install -d %{buildroot}%{_datadir}/starlingx
## install_append content
install -m644 60-persistent-storage.rules %{buildroot}%{_datadir}/starlingx/60-persistent-storage.rules
install -m644 journald.conf %{buildroot}%{_datadir}/starlingx/journald.conf
install -m644 systemd.conf.tmpfiles.d %{buildroot}%{_datadir}/starlingx/systemd.conf.tmpfiles.d
install -m644 tmp.conf.tmpfiles.d %{buildroot}%{_datadir}/starlingx/tmp.conf.tmpfiles.d
install -m644 tmp.mount %{buildroot}%{_datadir}/starlingx/tmp.mount
%post
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/60-persistent-storage.rules %{_udevrulesdir}/
chmod 644 %{_udevrulesdir}/60-persistent-storage.rules
cp -f %{_datadir}/starlingx/journald.conf %{_sysconfdir}/systemd
chmod 644 %{_sysconfdir}/systemd/journald.conf
cp -f %{_datadir}/starlingx/systemd.conf.tmpfiles.d %{_usr}/lib/tmpfiles.d/systemd.conf
chmod 644 %{_usr}/lib/tmpfiles.d/systemd.conf
cp -f %{_datadir}/starlingx/tmp.conf.tmpfiles.d %{_usr}/lib/tmpfiles.d/tmp.conf
chmod 644 %{_usr}/lib/tmpfiles.d/tmp.conf
cp -f %{_datadir}/starlingx/tmp.mount %{_unitdir}/
chmod 644 %{_unitdir}/tmp.mount
fi
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/60-persistent-storage.rules
/usr/share/starlingx/journald.conf
/usr/share/starlingx/systemd.conf.tmpfiles.d
/usr/share/starlingx/tmp.conf.tmpfiles.d
/usr/share/starlingx/tmp.mount
