#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : storageconfig
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/storageconfig-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/storageconfig-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: storageconfig-services = %{version}-%{release}
Requires: systemd
Patch1: 0001-change-sysconfig-dir.patch
Patch2: 0001-fix-Makefile-dir.patch

%description
No detailed description available

%package services
Summary: services components for the storageconfig package.
Group: Systemd services

%description services
services components for the storageconfig package.


%prep
%setup -q -n storageconfig-1.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568282205
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568282205
rm -rf %{buildroot}
## install_prepend content
%define local_etc_initd /usr/local/etc/init.d/
%define local_etc_goenabledd /usr/local/etc/goenabled.d/
%define _unitdir /usr/lib/systemd/system/
%define debug_package %{nil}
## install_prepend end
make install INITDDIR=%{buildroot}%{local_etc_initd} GOENABLEDDIR=%{buildroot}%{local_etc_goenabledd} SYSTEMDDIR=%{buildroot}%{_unitdir}
## install_append content
%post
systemctl enable storageconfig.service
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/goenabled.d/config_goenabled_check.sh
/usr/local/etc/init.d/storage_config

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/storageconfig.service
