#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtpms
Version  : 0.6.0.4f0d59d
Release  : 2
URL      : file:///home/clear/tar/libtpms-0.6.0-4f0d59d.tar.gz
Source0  : file:///home/clear/tar/libtpms-0.6.0-4f0d59d.tar.gz
Summary  : Library providing Trusted Platform Module (TPM) functionality
Group    : Development/Tools
License  : Apache-2.0
Requires: libtpms-lib = %{version}-%{release}
BuildRequires : autoconf
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bash
BuildRequires : coreutils
BuildRequires : gawk
BuildRequires : gettext-bin
BuildRequires : gmp-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : nss-dev >= 3.12.9-2
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : sed
Patch1: 0001-modify-check-error.patch
Patch2: 0002-upgrade-freebl-to-freebl3.patch
Patch3: 0003-modify-blapi.h-to-blapit.h.patch

%description
A library providing TPM functionality for VMs. Targeted for integration
into Qemu.

%package dev
Summary: dev components for the libtpms package.
Group: Development
Requires: libtpms-lib = %{version}-%{release}
Provides: libtpms-devel = %{version}-%{release}
Requires: libtpms = %{version}-%{release}

%description dev
dev components for the libtpms package.


%package lib
Summary: lib components for the libtpms package.
Group: Libraries

%description lib
lib components for the libtpms package.


%prep
%setup -q -n libtpms-0.6.0
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
## build_prepend content
%define _with_openssl --with-openssl
./bootstrap.sh
%configure \
--with-tpm2 \
--disable-static \
--prefix=/usr \
--libdir=%{_libdir} \
%{?_with_openssl}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568708238
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
rm -rf *.egg-info

%install
export SOURCE_DATE_EPOCH=1568708238
rm -rf %{buildroot}
## install_prepend content
install -d -m 0755 $RPM_BUILD_ROOT%{_libdir}
install -d -m 0755 $RPM_BUILD_ROOT%{_includedir}/libtpms
install -d -m 0755 $RPM_BUILD_ROOT%{_mandir}/man3
## install_prepend end
make %{?_smp_mflags} install DESTDIR=${RPM_BUILD_ROOT}
## install_append content
rm -f $RPM_BUILD_ROOT%{_libdir}/libtpms.la
%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libtpms/tpm_error.h
/usr/include/libtpms/tpm_library.h
/usr/include/libtpms/tpm_memory.h
/usr/include/libtpms/tpm_nvfilename.h
/usr/include/libtpms/tpm_tis.h
/usr/include/libtpms/tpm_types.h
/usr/lib64/libtpms.so
/usr/lib64/pkgconfig/libtpms.pc
/usr/share/man/man3/TPMLIB_CancelCommand.3
/usr/share/man/man3/TPMLIB_ChooseTPMVersion.3
/usr/share/man/man3/TPMLIB_DecodeBlob.3
/usr/share/man/man3/TPMLIB_GetTPMProperty.3
/usr/share/man/man3/TPMLIB_GetVersion.3
/usr/share/man/man3/TPMLIB_MainInit.3
/usr/share/man/man3/TPMLIB_Process.3
/usr/share/man/man3/TPMLIB_RegisterCallbacks.3
/usr/share/man/man3/TPMLIB_SetBufferSize.3
/usr/share/man/man3/TPMLIB_SetDebugFD.3
/usr/share/man/man3/TPMLIB_SetDebugLevel.3
/usr/share/man/man3/TPMLIB_SetDebugPrefix.3
/usr/share/man/man3/TPMLIB_Terminate.3
/usr/share/man/man3/TPMLIB_ValidateState.3
/usr/share/man/man3/TPMLIB_VolatileAll_Store.3
/usr/share/man/man3/TPM_Free.3
/usr/share/man/man3/TPM_IO_Hash_Data.3
/usr/share/man/man3/TPM_IO_Hash_End.3
/usr/share/man/man3/TPM_IO_Hash_Start.3
/usr/share/man/man3/TPM_IO_TpmEstablished_Get.3
/usr/share/man/man3/TPM_IO_TpmEstablished_Reset.3
/usr/share/man/man3/TPM_Malloc.3
/usr/share/man/man3/TPM_Realloc.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtpms.so.0
/usr/lib64/libtpms.so.0.6.0
