#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : haproxy-config
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/haproxy-config-1.0.tar.gz
Source0  : file:///home/clear/tar/haproxy-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: haproxy-config-services = %{version}-%{release}
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%package services
Summary: services components for the haproxy-config package.
Group: Systemd services

%description services
services components for the haproxy-config package.


%prep
%setup -q -n haproxy-config-1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568793362
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568793362
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir /usr/local/etc
%define _unitdir /usr/lib/systemd/system
## install_prepend end
%{__install} -d 755 %{buildroot}%{_sysconfdir}/haproxy/errors/
## install_append content
%{__install} -m 755 503.http %{buildroot}%{_sysconfdir}/haproxy/errors/503.http
%{__install} -d  %{buildroot}%{_sysconfdir}/systemd/system
%{__install} -m 644 haproxy.service %{buildroot}%{_sysconfdir}/systemd/system
%{__install} -d -m 755 %{buildroot}%{_unitdir}
%{__install} -m 644 haproxy.service %{buildroot}%{_unitdir}/haproxy.service
mkdir -p %{buildroot}%{_sysconfdir}/init.d
%{__install} -p -D -m 0755 haproxy.sh %{buildroot}%{_sysconfdir}/init.d/haproxy
%post
/bin/systemctl disable haproxy.service
if test -s %{_sysconfdir}/logrotate.d/haproxy ; then
echo '#See /etc/logrotate.d/syslog for haproxy rules' > %{_sysconfdir}/logrotate.d/haproxy
fi
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/haproxy/errors/503.http
/usr/local/etc/init.d/haproxy
/usr/local/etc/systemd/system/haproxy.service

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/haproxy.service
