#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lighttpd-config
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/lighttpd-config-1.0.tar.gz
Source0  : file:///home/clear/tar/lighttpd-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: lighttpd-config-data = %{version}-%{release}
Requires: lighttpd
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%package data
Summary: data components for the lighttpd-config package.
Group: Data

%description data
data components for the lighttpd-config package.


%prep
%setup -q -n lighttpd-config-1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568614170
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568614170
rm -rf %{buildroot}
## install_prepend content
%define debug_package %{nil}
%define _sysconfdir /usr/local/etc
CONFDIR=%{buildroot}%{_sysconfdir}/lighttpd
ROOTDIR=%{buildroot}/www
## install_prepend end
install -d -m 1777 ${ROOTDIR}/tmp
## install_append content
install -d ${CONFDIR}/ssl
install -d ${ROOTDIR}/pages/dav
install -d %{buildroot}%{_datadir}/starlingx
install -m640 lighttpd.conf %{buildroot}%{_datadir}/starlingx/lighttpd.conf
install -m755 lighttpd.init %{buildroot}%{_datadir}/starlingx/lighttpd.init
install -m644 lighttpd-inc.conf ${CONFDIR}/lighttpd-inc.conf
install -m644 index.html.lighttpd ${ROOTDIR}/pages/index.html
install -d %{buildroot}%{_sysconfdir}/logrotate.d
install -m644 lighttpd.logrotate %{buildroot}%{_datadir}/starlingx/lighttpd.logrotate
chmod 02770 %{buildroot}%{_sysconfdir}/lighttpd
%post
if [ $1 -eq 1 ] ; then
cp --preserve=xattr -f %{_datadir}/starlingx/lighttpd.conf %{_sysconfdir}/lighttpd/lighttpd.conf
chmod 640 %{_sysconfdir}/lighttpd/lighttpd.conf
cp --preserve=xattr -f %{_datadir}/starlingx/lighttpd.init %{_sysconfdir}/rc.d/init.d/lighttpd
chmod 755 %{_sysconfdir}/rc.d/init.d/lighttpd
cp --preserve=xattr -f %{_datadir}/starlingx/lighttpd.logrotate %{_sysconfdir}/logrotate.d/lighttpd
chmod 644 %{_sysconfdir}/logrotate.d/lighttpd
fi
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/lighttpd/lighttpd-inc.conf
/www/pages/index.html

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/lighttpd.conf
/usr/share/starlingx/lighttpd.init
/usr/share/starlingx/lighttpd.logrotate
