#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : syslog-ng-config
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/syslog-ng-config-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/syslog-ng-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: syslog-ng-config-bin = %{version}-%{release}
Requires: syslog-ng-config-data = %{version}-%{release}
Requires: syslog-ng
Requires: syslog-ng-libdbi
BuildRequires : systemd
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package bin
Summary: bin components for the syslog-ng-config package.
Group: Binaries
Requires: syslog-ng-config-data = %{version}-%{release}

%description bin
bin components for the syslog-ng-config package.


%package data
Summary: data components for the syslog-ng-config package.
Group: Data

%description data
data components for the syslog-ng-config package.


%prep
%setup -q -n syslog-ng-config-1.0
%patch1 -p1

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir	/usr/local/etc
%define _unitdir /usr/lib/systemd/system/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568258426
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568258426
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir	/usr/local/etc
%define debug_package %{nil}
%define _unitdir /usr/lib/systemd/system/
## install_prepend end
install -d %{buildroot}%{_datadir}/starlingx
## install_append content
install -D -m644 syslog-ng.conf %{buildroot}%{_datadir}/starlingx/syslog-ng.conf
install -D -m644 syslog-ng.logrotate %{buildroot}%{_datadir}/starlingx/syslog-ng.logrotate
install -D -m644 remotelogging.conf %{buildroot}%{_sysconfdir}/syslog-ng/remotelogging.conf
install -d %{buildroot}%{_sbindir}
install -D -m700 fm_event_syslogger %{buildroot}%{_sbindir}/fm_event_syslogger
install -D -m644 syslog-ng.service %{buildroot}%{_datadir}/starlingx/syslog-ng.service
%post
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/syslog-ng.conf %{_sysconfdir}/syslog-ng/syslog-ng.conf
chmod 644 %{_sysconfdir}/syslog-ng/syslog-ng.conf
cp -f %{_datadir}/starlingx/syslog-ng.logrotate %{_sysconfdir}/logrotate.d/syslog
chmod 644 %{_sysconfdir}/logrotate.d/syslog
cp -f %{_datadir}/starlingx/syslog-ng.service %{_unitdir}/syslog-ng.service
chmod 644 %{_unitdir}/syslog-ng.service
fi
ldconfig
%systemd_post syslog-ng.service
%preun
%systemd_preun syslog-ng.service
%postun
ldconfig
%systemd_postun_with_restart syslog-ng.service
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/syslog-ng/remotelogging.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/fm_event_syslogger

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/syslog-ng.conf
/usr/share/starlingx/syslog-ng.logrotate
/usr/share/starlingx/syslog-ng.service
