#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-boolean
Version  : 1.0.2
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-boolean-1.0.2.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-boolean-1.0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-boolean-data = %{version}-%{release}
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch

%description
puppet-boolean
==============
Define actual boolean parameters and properties for puppet types.

%package data
Summary: data components for the puppet-boolean package.
Group: Data

%description data
data components for the puppet-boolean package.


%prep
%setup -q -n puppet-boolean
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568859313
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568859313
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/boolean
## install_append content
cp -rp * %{buildroot}%{_datadir}/puppet/modules/boolean/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/boolean/CHANGELOG
/usr/share/puppet/modules/boolean/Gemfile
/usr/share/puppet/modules/boolean/LICENSE
/usr/share/puppet/modules/boolean/Makefile
/usr/share/puppet/modules/boolean/README.markdown
/usr/share/puppet/modules/boolean/Rakefile
/usr/share/puppet/modules/boolean/lib/puppet/parameter/boolean.rb
/usr/share/puppet/modules/boolean/lib/puppet/property/boolean.rb
/usr/share/puppet/modules/boolean/lib/puppet_x/util/boolean.rb
/usr/share/puppet/modules/boolean/metadata.json
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/centos-511-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/centos-66-x64-pe.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/centos-66-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/centos-72-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/debian-78-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/debian-82-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/centos-5.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/centos-6.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/centos-7.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/debian-7.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/debian-8.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/ubuntu-12.04.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/ubuntu-14.04.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/docker/ubuntu-16.04.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/ubuntu-server-1204-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/ubuntu-server-1404-x64.yml
/usr/share/puppet/modules/boolean/spec/acceptance/nodesets/ubuntu-server-1604-x64.yml
/usr/share/puppet/modules/boolean/spec/classes/coverage_spec.rb
/usr/share/puppet/modules/boolean/spec/default_facts.yml
/usr/share/puppet/modules/boolean/spec/spec_helper.rb
/usr/share/puppet/modules/boolean/spec/unit/puppet/property/boolean_spec.rb
