#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openstack-ras
Version  : 1.0.0
Release  : 1
URL      : file:///home/clr/stx-tar/openstack-ras-1.0.0.tar.gz
Source0  : file:///home/clr/stx-tar/openstack-ras-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
openstack-resource-agents
=========================
Pacemaker High Availability resource agents for OpenStack

%prep
%setup -q -n openstack-ras-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568014226
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568014226
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/ocf/resource.d/openstack/ceilometer-agent-central
/usr/lib/ocf/resource.d/openstack/ceilometer-alarm-evaluator
/usr/lib/ocf/resource.d/openstack/ceilometer-alarm-notifier
/usr/lib/ocf/resource.d/openstack/ceilometer-api
/usr/lib/ocf/resource.d/openstack/ceilometer-collector
/usr/lib/ocf/resource.d/openstack/cinder-api
/usr/lib/ocf/resource.d/openstack/cinder-schedule
/usr/lib/ocf/resource.d/openstack/cinder-volume
/usr/lib/ocf/resource.d/openstack/glance-api
/usr/lib/ocf/resource.d/openstack/glance-registry
/usr/lib/ocf/resource.d/openstack/heat-engine
/usr/lib/ocf/resource.d/openstack/keystone
/usr/lib/ocf/resource.d/openstack/neutron-agent-dhcp
/usr/lib/ocf/resource.d/openstack/neutron-agent-l3
/usr/lib/ocf/resource.d/openstack/neutron-metadata-agent
/usr/lib/ocf/resource.d/openstack/neutron-server
/usr/lib/ocf/resource.d/openstack/nova-api
/usr/lib/ocf/resource.d/openstack/nova-consoleauth
/usr/lib/ocf/resource.d/openstack/nova-network
/usr/lib/ocf/resource.d/openstack/nova-novnc
/usr/lib/ocf/resource.d/openstack/nova-scheduler
