#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : mtce-common
Version  : 1.0
Release  : 32
URL      : file:///home/clear/tar/mtce-common-1.0.tar.gz
Source0  : file:///home/clear/tar/mtce-common-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: /bin/bash
Requires: /bin/sh
Requires: /usr/bin/expect
Requires: dpkg
Requires: expect
Requires: fm-common >= 1.0
Requires: libc.so.6()(64bit)
Requires: libc.so.6(GLIBC_2.14)(64bit)
Requires: libc.so.6(GLIBC_2.2.5)(64bit)
Requires: libc.so.6(GLIBC_2.3)(64bit)
Requires: libc.so.6(GLIBC_2.4)(64bit)
Requires: libevent >= 2.0.21
Requires: libevent-2.1.so.6()(64bit)
Requires: libfmcommon.so.1()(64bit)
Requires: libgcc_s.so.1()(64bit)
Requires: libgcc_s.so.1(GCC_3.0)(64bit)
Requires: libjson-c.so.4()(64bit)
Requires: libm.so.6()(64bit)
Requires: libpthread.so.0()(64bit)
Requires: libpthread.so.0(GLIBC_2.2.5)(64bit)
Requires: librt.so.1()(64bit)
Requires: librt.so.1(GLIBC_2.2.5)(64bit)
Requires: librt.so.1(GLIBC_2.3.3)(64bit)
Requires: libssh2.so.1()(64bit)
Requires: libstdc++.so.6()(64bit)
Requires: libstdc++.so.6(CXXABI_1.3)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
Requires: libuuid.so.1()(64bit)
Requires: rtld(GNU_HASH)
Requires: rtslib-fb
Requires: systemd
Requires: time
Requires: util-linux
BuildRequires : cppcheck
BuildRequires : expect
BuildRequires : fm-common
BuildRequires : fm-common-dev
BuildRequires : fm-mgr
BuildRequires : json-c
BuildRequires : json-c-devel
BuildRequires : libevent
BuildRequires : libevent-devel
BuildRequires : libssh2
BuildRequires : libssh2-devel
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : postgresql
BuildRequires : systemd-devel
BuildRequires : util-linux-dev

%description
No detailed description available

%package dev
Summary: dev components for the mtce-common package.
Group: Development
Provides: mtce-common-devel = %{version}-%{release}
#Requires: mtce-common = %{version}-%{release}

%description dev
dev components for the mtce-common package.


%package staticdev
Summary: staticdev components for the mtce-common package.
Group: Default
Requires: mtce-common-dev = %{version}-%{release}

%description staticdev
staticdev components for the mtce-common package.


%prep
%setup -q -n mtce-common-1.0

%build
## build_prepend content
%define debug_package %{nil}
%global _buildsubdir %{_builddir}/%{name}-%{version}
%define _sysconfdir /usr/local/etc
VER=%{version}
MAJOR=$(echo $VER | awk -F . '{print $1}')
MINOR=$(echo $VER | awk -F . '{print $2}')
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567647990
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} MAJOR=$MAJOR MINOR=$MINOR build


%install
export SOURCE_DATE_EPOCH=1567647990
rm -rf %{buildroot}
## install_prepend content
VER=%{version}
MAJOR=$(echo $VER | awk -F . '{print $1}')
MINOR=$(echo $VER | awk -F . '{print $2}')
## install_prepend end
install -m 755 -d %{buildroot}%{_libdir}
## install_append content
install -m 644 -p -D %{_buildsubdir}/daemon/libdaemon.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libcommon.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libthreadUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libipmiUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libpingUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libnodeBase.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libregexUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libhostUtil.a %{buildroot}%{_libdir}
install -m 755 -d %{buildroot}%{_includedir}
install -m 755 -d %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/fitCodes.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/logMacros.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/returnCodes.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeTimers.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/hostClass.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/httpUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/jsonUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/msgClass.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeBase.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeEvent.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeMacro.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/timeUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 755 -d %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/daemon/daemon_ini.h %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/daemon/daemon_common.h %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/daemon/daemon_option.h %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/common/alarmUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/hostUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/ipmiUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nlEvent.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/pingUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/regexUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/threadUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/tokenUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/secretUtil.h %{buildroot}%{_includedir}/mtce-common
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mtce-common/alarmUtil.h
/usr/include/mtce-common/fitCodes.h
/usr/include/mtce-common/hostClass.h
/usr/include/mtce-common/hostUtil.h
/usr/include/mtce-common/httpUtil.h
/usr/include/mtce-common/ipmiUtil.h
/usr/include/mtce-common/jsonUtil.h
/usr/include/mtce-common/logMacros.h
/usr/include/mtce-common/msgClass.h
/usr/include/mtce-common/nlEvent.h
/usr/include/mtce-common/nodeBase.h
/usr/include/mtce-common/nodeEvent.h
/usr/include/mtce-common/nodeMacro.h
/usr/include/mtce-common/nodeTimers.h
/usr/include/mtce-common/nodeUtil.h
/usr/include/mtce-common/pingUtil.h
/usr/include/mtce-common/regexUtil.h
/usr/include/mtce-common/returnCodes.h
/usr/include/mtce-common/secretUtil.h
/usr/include/mtce-common/threadUtil.h
/usr/include/mtce-common/timeUtil.h
/usr/include/mtce-common/tokenUtil.h
/usr/include/mtce-daemon/daemon_common.h
/usr/include/mtce-daemon/daemon_ini.h
/usr/include/mtce-daemon/daemon_option.h

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libcommon.a
/usr/lib64/libdaemon.a
/usr/lib64/libhostUtil.a
/usr/lib64/libipmiUtil.a
/usr/lib64/libnodeBase.a
/usr/lib64/libpingUtil.a
/usr/lib64/libregexUtil.a
/usr/lib64/libthreadUtil.a
