#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : logmgmt
Version  : 1.0
Release  : 3
URL      : file:///home/clear/tar/logmgmt-1.0.tar.gz
Source0  : file:///home/clear/tar/logmgmt-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: logmgmt-bin = %{version}-%{release}
Requires: logmgmt-python = %{version}-%{release}
Requires: logmgmt-python3 = %{version}-%{release}
Requires: python-daemon
Requires: systemd
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : setuptools
BuildRequires : systemd-devel

%description
No detailed description available

%package bin
Summary: bin components for the logmgmt package.
Group: Binaries

%description bin
bin components for the logmgmt package.


%package python
Summary: python components for the logmgmt package.
Group: Default
Requires: logmgmt-python3 = %{version}-%{release}

%description python
python components for the logmgmt package.


%package python3
Summary: python3 components for the logmgmt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the logmgmt package.


%prep
%setup -q -n logmgmt-1.0

%build
## build_prepend content
%define local_bindir /usr/bin/
%define local_etc_initd /usr/local/etc/init.d/
%define local_etc_pmond /usr/local/etc/pmon.d/
%define pythonroot /usr/lib64/python2.7/site-packages
%define debug_package %{nil}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568000317
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
%{__python} setup.py install --root=$RPM_BUILD_ROOT \
--install-lib=%{pythonroot} \
--prefix=/usr \
--install-data=/usr/share \
--single-version-externally-managed
install -d -m 755 %{buildroot}%{local_bindir}
install -p -D -m 700 scripts/bin/logmgmt %{buildroot}%{local_bindir}/logmgmt
install -p -D -m 700 scripts/bin/logmgmt_postrotate %{buildroot}%{local_bindir}/logmgmt_postrotate
install -p -D -m 700 scripts/bin/logmgmt_prerotate %{buildroot}%{local_bindir}/logmgmt_prerotate
install -d -m 755 %{buildroot}%{local_etc_initd}
install -p -D -m 700 scripts/init.d/logmgmt %{buildroot}%{local_etc_initd}/logmgmt
install -d -m 755 %{buildroot}%{local_etc_pmond}
install -p -D -m 644 scripts/pmon.d/logmgmt %{buildroot}%{local_etc_pmond}/logmgmt
install -p -D -m 664 scripts/etc/systemd/system/logmgmt.service %{buildroot}%{_unitdir}/logmgmt.service
%post
/usr/bin/systemctl enable logmgmt.service >/dev/null 2>&1
%clean
rm -rf $RPM_BUILD_ROOT
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/logmgmt
/usr/local/etc/pmon.d/logmgmt

%files bin
%defattr(-,root,root,-)
/usr/bin/logmgmt
/usr/bin/logmgmt_postrotate
/usr/bin/logmgmt_prerotate

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
