#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-muranoclient
Version  : 1.1.1
Release  : 2
URL      : file:///home/clr/stx-tar/python-muranoclient-1.1.1.tar.gz
Source0  : file:///home/clr/stx-tar/python-muranoclient-1.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: python-muranoclient-bin = %{version}-%{release}
Requires: python-muranoclient-python = %{version}-%{release}
Requires: python-muranoclient-python3 = %{version}-%{release}
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : git
BuildRequires : openstack-macros
BuildRequires : pbr

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/python-muranoclient.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package bin
Summary: bin components for the python-muranoclient package.
Group: Binaries

%description bin
bin components for the python-muranoclient package.


%package python
Summary: python components for the python-muranoclient package.
Group: Default
Requires: python-muranoclient-python3 = %{version}-%{release}

%description python
python components for the python-muranoclient package.


%package python3
Summary: python3 components for the python-muranoclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-muranoclient package.


%prep
%setup -q -n python-muranoclient-1.1.1

%build
## build_prepend content
export PBR_VERSION=%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569376605
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
echo "dont need check"
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
LANG=en_US.UTF-8
python3 setup.py install --skip-build --root %{buildroot}
mv %{buildroot}%{_bindir}/murano %{buildroot}%{_bindir}/python3-murano
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/python3-murano

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
