#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iptables-config
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/iptables-config-1.0.tar.gz
Source0  : file:///home/clear/tar/iptables-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: iptables-config-data = %{version}-%{release}
Requires: iptables
Requires: iptables-services
Requires: iptables-utils
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%package data
Summary: data components for the iptables-config package.
Group: Data

%description data
data components for the iptables-config package.


%prep
%setup -q -n iptables-config-1.0
%patch1 -p1

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir /usr/local/etc
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568599018
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568599018
rm -rf %{buildroot}
install -d -m 755 %{buildroot}%{_sysconfdir}/sysconfig
## install_append content
install -d %{buildroot}%{_datadir}/starlingx
install -m 600 iptables.rules %{buildroot}%{_datadir}/starlingx/iptables.rules
install -m 600 ip6tables.rules %{buildroot}%{_datadir}/starlingx/ip6tables.rules
%post
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/iptables.rules %{_sysconfdir}/sysconfig/iptables
chmod 600 %{_sysconfdir}/sysconfig/iptables
cp -f %{_datadir}/starlingx/ip6tables.rules %{_sysconfdir}/sysconfig/ip6tables
chmod 600 %{_sysconfdir}/sysconfig/ip6tables
fi
%{_bindir}/systemctl enable iptables.service ip6tables.service >/dev/null 2>&1
exit 0
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/ip6tables.rules
/usr/share/starlingx/iptables.rules
