#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : build-info
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/build-info-1.0.tar.gz
Source0  : file:///home/clear/tar/build-info-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%package dev
Summary: dev components for the build-info package.
Group: Development
Provides: build-info-devel = %{version}-%{release}
Requires: build-info = %{version}-%{release}

%description dev
dev components for the build-info package.


%prep
%setup -q -n build-info-1.0
%patch1 -p1

%build
## build_prepend content
%define local_etcdir /usr/local/etc
%define local_incdir /usr/include
%define debug_package %{nil}
./collect.sh
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568169790
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568169790
rm -rf %{buildroot}
install -d -m 755 %{buildroot}%{local_etcdir}
## install_append content
install -m 644 build.info %{buildroot}/%{local_etcdir}
install -d -m 755 %{buildroot}%{local_incdir}
install -m 644 build_info.h %{buildroot}/%{local_incdir}
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/build.info

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
