#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : mtce-guest
Version  : 1.0
Release  : 10
URL      : file:///home/clear/tar/mtce-guest-1.0.tar.gz
Source0  : file:///home/clear/tar/mtce-guest-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mtce-guest-services = %{version}-%{release}
Requires: /bin/bash
Requires: /bin/sh
Requires: dpkg
Requires: fm-common >= 1.0
Requires: libc.so.6()(64bit)
Requires: libc.so.6(GLIBC_2.14)(64bit)
Requires: libc.so.6(GLIBC_2.2.5)(64bit)
Requires: libc.so.6(GLIBC_2.3)(64bit)
Requires: libc.so.6(GLIBC_2.4)(64bit)
Requires: libevent >= 2.0.21
Requires: libevent-2.1.so.6()(64bit)
Requires: libfmcommon.so.1()(64bit)
Requires: libgcc_s.so.1()(64bit)
Requires: libgcc_s.so.1(GCC_3.0)(64bit)
Requires: libjson-c.so.4()(64bit)
Requires: libm.so.6()(64bit)
Requires: libpthread.so.0()(64bit)
Requires: libpthread.so.0(GLIBC_2.2.5)(64bit)
Requires: librt.so.1()(64bit)
Requires: librt.so.1(GLIBC_2.2.5)(64bit)
Requires: librt.so.1(GLIBC_2.3.3)(64bit)
Requires: libstdc++.so.6()(64bit)
Requires: libstdc++.so.6(CXXABI_1.3)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
Requires: libuuid.so.1()(64bit)
Requires: rtld(GNU_HASH)
Requires: systemd
Requires: time
Requires: util-linux
BuildRequires : cppcheck
BuildRequires : fm-common
BuildRequires : fm-common-dev
BuildRequires : json-c
BuildRequires : json-c-devel
BuildRequires : libevent
BuildRequires : libevent-devel
BuildRequires : mtce-common-dev
BuildRequires : mtce-common-staticdev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : systemd-devel
BuildRequires : util-linux-dev
Patch1: 0001-change-sysconfig-dir.patch

%description
This maintenance common guest service provides a means of guest heartbeat
orchestration under VIM (system management) control.

%package services
Summary: services components for the mtce-guest package.
Group: Systemd services

%description services
services components for the mtce-guest package.


%prep
%setup -q -n mtce-guest-1.0
%patch1 -p1

%build
## build_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567648754
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} MAJOR=$MAJOR MINOR=$MINOR


%install
export SOURCE_DATE_EPOCH=1567648754
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir /usr/local/etc
%define _unitdir /usr/lib/systemd/system/
%define local_bindir /usr/local/bin
## install_prepend end
make install DESTDIR=%{buildroot} PREFIX=%{buildroot}/usr/local SYSCONFDIR=%{buildroot}%{_sysconfdir} LOCALBINDIR=%{buildroot}%{local_bindir} UNITDIR=%{buildroot}%{_unitdir}
## install_append content
%post
/bin/systemctl enable guestServer.service
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/ocf/resource.d/platform/guestAgent
/usr/local/bin/guestAgent
/usr/local/bin/guestServer
/usr/local/etc/init.d/guestAgent
/usr/local/etc/init.d/guestServer
/usr/local/etc/logrotate.d/guestAgent.logrotate
/usr/local/etc/logrotate.d/guestServer.logrotate
/usr/local/etc/mtc/guestAgent.ini
/usr/local/etc/mtc/guestServer.ini
/usr/local/etc/pmon.d/guestServer.conf

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/guestAgent.service
/usr/lib/systemd/system/guestServer.service
