#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sudo-config
Version  : 1.0
Release  : 2
URL      : file:///home/clr/stx-tar/sudo-config-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/sudo-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%prep
%setup -q -n sudo-config-1.0
%patch1 -p1

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir	/usr/local/etc
%define _unitdir /usr/lib/systemd/system/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568269157
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568269157
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir	/usr/local/etc
## install_prepend end
install -d %{buildroot}/%{_sysconfdir}/sudoers.d
## install_append content
install -m 440 sysadmin.sudo  %{buildroot}/%{_sysconfdir}/sudoers.d/sysadmin
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/sudoers.d/sysadmin
