#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fm-common
Version  : 1.0
Release  : 6
URL      : file:///home/qimingyu/packages/stx-fault/fm-common-1.0.tar.gz
Source0  : file:///home/qimingyu/packages/stx-fault/fm-common-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: fm-common-bin = %{version}-%{release}
Requires: fm-common-lib = %{version}-%{release}
Requires: fm-common-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : postgresql-dev
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : util-linux
BuildRequires : util-linux-dev
Patch1: 0001-strncpy-specified-bound-equals-destination-size.patch
Patch2: 0002-add-python-setup-to-Makefile.patch

%description
No detailed description available

%package bin
Summary: bin components for the fm-common package.
Group: Binaries

%description bin
bin components for the fm-common package.


%package dev
Summary: dev components for the fm-common package.
Group: Development
Requires: fm-common-lib = %{version}-%{release}
Requires: fm-common-bin = %{version}-%{release}
Provides: fm-common-devel = %{version}-%{release}
Requires: fm-common = %{version}-%{release}

%description dev
dev components for the fm-common package.


%package doc
Summary: doc components for the fm-common package.
Group: Documentation

%description doc
doc components for the fm-common package.


%package lib
Summary: lib components for the fm-common package.
Group: Libraries

%description lib
lib components for the fm-common package.


%package python
Summary: python components for the fm-common package.
Group: Default

%description python
python components for the fm-common package.


%prep
%setup -q -n fm-common
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568108498
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
pushd sources
make  %{?_smp_mflags} MAJOR=$MAJOR MINOR=$MINOR
popd


%install
export SOURCE_DATE_EPOCH=1568108498
rm -rf %{buildroot}
## install_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
%define tis_patch_ver 9
%define _tis_build_type std
%define local_dir /usr/local
%define local_bindir %{local_dir}/bin
%define cgcs_doc_deploy_dir /usr/share/doc/cgcs_doc
%define pythonroot /usr/lib64/python2.7/site-packages
## install_prepend end
pushd sources
make DEST_DIR=$RPM_BUILD_ROOT BIN_DIR=%{local_bindir} LIB_DIR=%{_libdir} INC_DIR=%{_includedir} MAJOR=$MAJOR MINOR=$MINOR install_non_bb
popd
## install_append content
pushd sources
python2 setup.py install --root=%{buildroot} \
--install-lib=%{pythonroot} \
--prefix=/usr \
--install-data=/usr/share
install -d $RPM_BUILD_ROOT/usr/bin
install -m 755 fm_db_sync_event_suppression.py $RPM_BUILD_ROOT/usr/bin/fm_db_sync_event_suppression.py
install -m 644 -p -D fmConfig.h %{buildroot}%{_includedir}/fmConfig.h
install -m 644 -p -D fmLog.h %{buildroot}%{_includedir}/fmLog.h
CGCS_DOC_DEPLOY=$RPM_BUILD_ROOT/%{cgcs_doc_deploy_dir}
install -d $CGCS_DOC_DEPLOY
install -m 644 fmAlarm.h $CGCS_DOC_DEPLOY
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/bin/fmClientCli

%files bin
%defattr(-,root,root,-)
/usr/bin/fm_db_sync_event_suppression.py

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libfmcommon.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/cgcs_doc/fmAlarm.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfmcommon.so.1
/usr/lib64/libfmcommon.so.1.0

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*
