#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-ldap
Version  : 0.2.4
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-ldap-0.2.4.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-ldap-0.2.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: puppet-ldap-data = %{version}-%{release}
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch

%description
Puppet OpenLDAP Module
======================
Introduction
------------
Puppet module to manage client and server configuration for
**OpenLdap**.

%package data
Summary: data components for the puppet-ldap package.
Group: Data

%description data
data components for the puppet-ldap package.


%prep
%setup -q -n puppet-ldap-master
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568788464
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568788464
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/ldap
## install_append content
cp -R ../puppet-ldap-master/* %{buildroot}%{_datadir}/puppet/modules/ldap/.
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/ldap/CHANGELOG
/usr/share/puppet/modules/ldap/Gemfile
/usr/share/puppet/modules/ldap/Gemfile.lock
/usr/share/puppet/modules/ldap/Makefile
/usr/share/puppet/modules/ldap/Modulefile
/usr/share/puppet/modules/ldap/README.md
/usr/share/puppet/modules/ldap/Rakefile
/usr/share/puppet/modules/ldap/manifests/client.pp
/usr/share/puppet/modules/ldap/manifests/init.pp
/usr/share/puppet/modules/ldap/manifests/os/debian.pp
/usr/share/puppet/modules/ldap/manifests/os/redhat.pp
/usr/share/puppet/modules/ldap/manifests/os/suse.pp
/usr/share/puppet/modules/ldap/manifests/os/ubuntu.pp
/usr/share/puppet/modules/ldap/manifests/params.pp
/usr/share/puppet/modules/ldap/manifests/server/debian.pp
/usr/share/puppet/modules/ldap/manifests/server/master.pp
/usr/share/puppet/modules/ldap/manifests/server/redhat.pp
/usr/share/puppet/modules/ldap/manifests/server/slave.pp
/usr/share/puppet/modules/ldap/metadata.json
/usr/share/puppet/modules/ldap/spec/classes/ldap_client_spec.rb
/usr/share/puppet/modules/ldap/spec/classes/ldap_server_master_spec.rb
/usr/share/puppet/modules/ldap/spec/classes/ldap_server_slave_spec.rb
/usr/share/puppet/modules/ldap/spec/classes/ldap_spec.rb
/usr/share/puppet/modules/ldap/spec/fixtures/manifests/site.pp
/usr/share/puppet/modules/ldap/spec/spec_helper.rb
/usr/share/puppet/modules/ldap/templates/default/slapd.erb
/usr/share/puppet/modules/ldap/templates/etc/default/slapd.erb
/usr/share/puppet/modules/ldap/templates/etc/ldap/ldap.conf.erb
/usr/share/puppet/modules/ldap/templates/etc/ldap/slapd.conf.erb
/usr/share/puppet/modules/ldap/templates/etc/ldap/slapd.d
/usr/share/puppet/modules/ldap/templates/etc/openldap/ldap.conf.erb
/usr/share/puppet/modules/ldap/templates/etc/openldap/slapd.conf.erb
/usr/share/puppet/modules/ldap/templates/etc/openldap/slapd.d/cn=config-update.ldif.erb
/usr/share/puppet/modules/ldap/templates/etc/sysconfig/ldap.erb
/usr/share/puppet/modules/ldap/templates/ldap.conf.erb
/usr/share/puppet/modules/ldap/templates/slapd.conf.erb
/usr/share/puppet/modules/ldap/templates/sysconfig/ldap.erb
