PKG_NAME := docker-distribution
URL = file:///home/clear/tar/docker-distribution-2.6.2.tar.gz
ARCHIVES = file:///home/clear/clearlinux/packages/docker-distribution/config.tar.xz :

include ../common/Makefile.common
