#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-dcorch
Version  : 1.0.0
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-dcorch-1.0.0.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-dcorch-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-dcorch-data = %{version}-%{release}
BuildRequires : python-dev
Patch1: 0001-fix-Makefile-dir.patch

%description
No detailed description available

%package data
Summary: data components for the puppet-dcorch package.
Group: Data

%description data
data components for the puppet-dcorch package.


%prep
%setup -q -n puppet-dcorch-1.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568796007
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568796007
rm -rf %{buildroot}
%make_install
## install_append content
make install MODULEDIR=%{buildroot}%{_datadir}/puppet/modules
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/dcorch/.fixtures.yml
/usr/share/puppet/modules/dcorch/Gemfile
/usr/share/puppet/modules/dcorch/LICENSE
/usr/share/puppet/modules/dcorch/Modulefile
/usr/share/puppet/modules/dcorch/Rakefile
/usr/share/puppet/modules/dcorch/lib/puppet/provider/dcorch_api_paste_ini/ini_setting.rb
/usr/share/puppet/modules/dcorch/lib/puppet/provider/dcorch_config/ini_setting.rb
/usr/share/puppet/modules/dcorch/lib/puppet/type/dcorch_api_paste_ini.rb
/usr/share/puppet/modules/dcorch/lib/puppet/type/dcorch_config.rb
/usr/share/puppet/modules/dcorch/manifests/api_proxy.pp
/usr/share/puppet/modules/dcorch/manifests/client.pp
/usr/share/puppet/modules/dcorch/manifests/db/postgresql.pp
/usr/share/puppet/modules/dcorch/manifests/db/sync.pp
/usr/share/puppet/modules/dcorch/manifests/deps.pp
/usr/share/puppet/modules/dcorch/manifests/engine.pp
/usr/share/puppet/modules/dcorch/manifests/init.pp
/usr/share/puppet/modules/dcorch/manifests/keystone/auth.pp
/usr/share/puppet/modules/dcorch/manifests/params.pp
/usr/share/puppet/modules/dcorch/manifests/rabbitmq.pp
/usr/share/puppet/modules/dcorch/manifests/snmp.pp
