#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dpkg
Version  : 1.18.24
Release  : 1
URL      : file:///home/clear/tar/dpkg_1.18.24.tar.xz
Source0  : file:///home/clear/tar/dpkg_1.18.24.tar.xz
Summary  : Debian package management system library
Group    : Development/Tools
License  : GPL-2.0
Requires: dpkg-bin = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : doxygen
BuildRequires : gcc
BuildRequires : ncurses
BuildRequires : ncurses-dev
BuildRequires : perl-Perl-Version
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev

%description
dpkg - Debian's package maintenance system
The primary interface for the dpkg suite is the ‘dselect’ program;
a more low-level and less user-friendly interface is available in
the form of the ‘dpkg’ command.

%package bin
Summary: bin components for the dpkg package.
Group: Binaries

%description bin
bin components for the dpkg package.


%prep
%setup -q -n dpkg-1.18.24

%build
## build_prepend content
%define local_bindir /usr/bin/
./configure --prefix=$RPM_BUILD_ROOT \
--disable-dselect \
--disable-update-alternatives \
--without-liblzma
make -j"%(nproc)"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567157205
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8

%install
export SOURCE_DATE_EPOCH=1567157205
rm -rf %{buildroot}
install -d -m 755 %{buildroot}%{local_bindir}
## install_append content
install -p -D -m 700 utils/start-stop-daemon %{buildroot}%{local_bindir}/start-stop-daemon
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/start-stop-daemon
