#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cgts-client
Version  : 1.0
Release  : 5
URL      : file:///home/clear/tar/cgts-client-1.0.tar.gz
Source0  : file:///home/clear/tar/cgts-client-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: cgts-client-bin = %{version}-%{release}
Requires: cgts-client-python = %{version}-%{release}
Requires: cgts-client-python3 = %{version}-%{release}
Requires: bash-completion
Requires: httplib2
Requires: prettytable
Requires: python-keystoneclient
Requires: python-neutronclient
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pbr-python
BuildRequires : pip
BuildRequires : setuptools

%description


%package bin
Summary: bin components for the cgts-client package.
Group: Binaries

%description bin
bin components for the cgts-client package.


%package python
Summary: python components for the cgts-client package.
Group: Default
Requires: cgts-client-python3 = %{version}-%{release}

%description python
python components for the cgts-client package.


%package python3
Summary: python3 components for the cgts-client package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cgts-client package.


%prep
%setup -q -n cgts-client-1.0

%build
## build_prepend content
%define local_bindir /usr/bin/
%define local_etc_bash_completiond /usr/local/etc/bash_completion.d/
%define pythonroot /usr/lib64/python3.7/site-packages
%define debug_package %{nil}
export PBR_VERSION=%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566457452
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
rm -rf *.egg-info
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
%{__python} setup.py install --root=$RPM_BUILD_ROOT --install-lib=%{pythonroot} --prefix=/usr --install-data=/usr/share --single-version-externally-managed
install -d -m 755 %{buildroot}%{local_etc_bash_completiond}
install -p -D -m 664 tools/system.bash_completion %{buildroot}%{local_etc_bash_completiond}/system.bash_completion
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/bash_completion.d/system.bash_completion

%files bin
%defattr(-,root,root,-)
/usr/bin/system

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
