#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-network
Version  : 1.0.2
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-network-1.0.2.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-network-1.0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-network-data = %{version}-%{release}
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch

%description
puppet-network
==============
Manage non-volatile network and route configuration.

%package data
Summary: data components for the puppet-network package.
Group: Data

%description data
data components for the puppet-network package.


%prep
%setup -q -n packstack
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568776821
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568776821
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/network
## install_append content
cp -R puppet/modules/network %{buildroot}%{_datadir}/puppet/modules
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/network/.fixtures.yml
/usr/share/puppet/modules/network/.gitignore
/usr/share/puppet/modules/network/.travis.yml
/usr/share/puppet/modules/network/CHANGELOG
/usr/share/puppet/modules/network/Gemfile
/usr/share/puppet/modules/network/LICENSE
/usr/share/puppet/modules/network/Modulefile
/usr/share/puppet/modules/network/README.markdown
/usr/share/puppet/modules/network/Rakefile
/usr/share/puppet/modules/network/lib/facter/network.rb
/usr/share/puppet/modules/network/lib/puppet/parser/functions/compact_hash.rb
/usr/share/puppet/modules/network/lib/puppet/provider/network_config/interfaces.rb
/usr/share/puppet/modules/network/lib/puppet/provider/network_config/redhat.rb
/usr/share/puppet/modules/network/lib/puppet/provider/network_route/redhat.rb
/usr/share/puppet/modules/network/lib/puppet/provider/network_route/routes.rb
/usr/share/puppet/modules/network/lib/puppet/type/network_config.rb
/usr/share/puppet/modules/network/lib/puppet/type/network_route.rb
/usr/share/puppet/modules/network/manifests/bond.pp
/usr/share/puppet/modules/network/manifests/bond/debian.pp
/usr/share/puppet/modules/network/manifests/bond/redhat.pp
/usr/share/puppet/modules/network/manifests/bond/setup.pp
/usr/share/puppet/modules/network/spec/classes/bond/setup_spec.rb
/usr/share/puppet/modules/network/spec/defines/bond/debian_spec.rb
/usr/share/puppet/modules/network/spec/defines/bond/redhat_spec.rb
/usr/share/puppet/modules/network/spec/defines/bond_spec.rb
/usr/share/puppet/modules/network/spec/fixtures/manifests/site.pp
/usr/share/puppet/modules/network/spec/fixtures/modules/.gitignore
/usr/share/puppet/modules/network/spec/fixtures/modules/network/files
/usr/share/puppet/modules/network/spec/fixtures/modules/network/lib
/usr/share/puppet/modules/network/spec/fixtures/modules/network/manifests
/usr/share/puppet/modules/network/spec/fixtures/modules/network/templates
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/flush_lo_eth0_dhcp
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/iface_whitespace
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/loopback
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/single_interface_dhcp
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/single_interface_options
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/single_interface_static
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/three_interface_static
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/two_interface_dhcp
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/interfaces_spec/two_interfaces_static_vlan
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/eth0-dhcp
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/eth0-hotplug
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/eth0-nohotplug
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/eth0-static
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/eth1-dhcp
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/lo
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-bond0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-bond1
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-bond1~
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0.0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0.1
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0.4095
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0.4096
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0:10000000
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth1
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth2
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth3
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan100
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan100:0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan200
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan300
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan400
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan500
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-vlan500.bak
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/bond0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/bond1
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/eth0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/eth1
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/eth2
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/eth3
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/vlan100
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/vlan100_0
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/vlan200
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/vlan300
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/vlan400
/usr/share/puppet/modules/network/spec/fixtures/provider/network_config/redhat_spec/virbonding/vlan500
/usr/share/puppet/modules/network/spec/fixtures/provider/network_route/redhat/advanced_routes
/usr/share/puppet/modules/network/spec/fixtures/provider/network_route/redhat/simple_routes
/usr/share/puppet/modules/network/spec/fixtures/provider/network_route/routes_spec/advanced_routes
/usr/share/puppet/modules/network/spec/fixtures/provider/network_route/routes_spec/simple_routes
/usr/share/puppet/modules/network/spec/spec_helper.rb
/usr/share/puppet/modules/network/spec/travis_rspec.rb
/usr/share/puppet/modules/network/spec/unit/network_facts_spec.rb
/usr/share/puppet/modules/network/spec/unit/provider/network_config/interfaces_spec.rb
/usr/share/puppet/modules/network/spec/unit/provider/network_config/redhat_spec.rb
/usr/share/puppet/modules/network/spec/unit/provider/network_route/redhat_spec.rb
/usr/share/puppet/modules/network/spec/unit/provider/network_route/routes_spec.rb
/usr/share/puppet/modules/network/spec/unit/type/network_config_spec.rb
/usr/share/puppet/modules/network/spec/unit/type/network_route_spec.rb
/usr/share/puppet/modules/network/templates/bond/opts-redhat.erb
