#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sm-tools
Version  : 1.0
Release  : 2
URL      : file:///home/clr/stx-tar/sm-tools-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/sm-tools-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: sm-tools-bin = %{version}-%{release}
Requires: sm-tools-python = %{version}-%{release}
Requires: sm-tools-legacypython
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
No detailed description available

%package bin
Summary: bin components for the sm-tools package.
Group: Binaries

%description bin
bin components for the sm-tools package.


%package legacypython
Summary: legacypython components for the sm-tools package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the sm-tools package.


%package python
Summary: python components for the sm-tools package.
Group: Default

%description python
python components for the sm-tools package.


%prep
%setup -q -n sm-tools-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566378345
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sm-configure
/usr/bin/sm-deprovision
/usr/bin/sm-dump
/usr/bin/sm-iface-state
/usr/bin/sm-manage
/usr/bin/sm-provision
/usr/bin/sm-query
/usr/bin/sm-restart
/usr/bin/sm-restart-safe
/usr/bin/sm-unmanage

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
