#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ceph-manager
Version  : 1.0
Release  : 3
URL      : file:///home/clear/tar/ceph-manager-1.0.tar.gz
Source0  : file:///home/clear/tar/ceph-manager-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: ceph-manager-bin = %{version}-%{release}
Requires: ceph-manager-python = %{version}-%{release}
Requires: ceph-manager-python3 = %{version}-%{release}
Requires: sysinv
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : systemd
BuildRequires : systemd-devel
BuildRequires : tox
BuildRequires : virtualenv
Patch1: 0001-change-sysconfig-dir.patch

%description
No detailed description available

%package bin
Summary: bin components for the ceph-manager package.
Group: Binaries

%description bin
bin components for the ceph-manager package.


%package python
Summary: python components for the ceph-manager package.
Group: Default
Requires: ceph-manager-python3 = %{version}-%{release}

%description python
python components for the ceph-manager package.


%package python3
Summary: python3 components for the ceph-manager package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ceph-manager package.


%prep
%setup -q -n ceph-manager-1.0
%patch1 -p1

%build
## build_prepend content
%define local_bindir /usr/bin/
%define local_etc_initd /usr/local/etc/init.d/
%define local_etc_logrotated /usr/local/etc/logrotate.d/
%define pythonroot /usr/lib64/python2.7/site-packages
%define debug_package %{nil}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567049623
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
%{__python} setup.py install --root=$RPM_BUILD_ROOT \
--install-lib=%{pythonroot} \
--prefix=/usr \
--install-data=/usr/share \
--single-version-externally-managed
install -d -m 755 %{buildroot}%{local_etc_initd}
install -p -D -m 700 scripts/init.d/ceph-manager %{buildroot}%{local_etc_initd}/ceph-manager
install -d -m 755 %{buildroot}%{local_bindir}
install -p -D -m 700 scripts/bin/ceph-manager %{buildroot}%{local_bindir}/ceph-manager
install -d -m 755 %{buildroot}%{local_etc_logrotated}
install -p -D -m 644 files/ceph-manager.logrotate %{buildroot}%{local_etc_logrotated}/ceph-manager.logrotate
install -d -m 755 %{buildroot}%{_unitdir}
install -m 644 -p -D files/%{name}.service %{buildroot}%{_unitdir}/%{name}.service
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/ceph-manager
/usr/local/etc/logrotate.d/ceph-manager.logrotate

%files bin
%defattr(-,root,root,-)
/usr/bin/ceph-manager

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
