#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : workerconfig
Version  : 1.0
Release  : 8
URL      : file:///home/clear/tar/workerconfig-1.0.tar.gz
Source0  : file:///home/clear/tar/workerconfig-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: workerconfig-services = %{version}-%{release}
Requires: systemd
Patch1: 0001-change-sysconfig-dir.patch

%description
No detailed description available

%package services
Summary: services components for the workerconfig package.
Group: Systemd services

%description services
services components for the workerconfig package.


%prep
%setup -q -n workerconfig-1.0
%patch1 -p1

%build
## build_prepend content
%define initddir /usr/local/etc/init.d/
%define goenableddir /usr/local/etc/goenabled.d/
%define systemddir /usr/lib/systemd/system/
%define debug_package %{nil}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570603249
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1570603249
rm -rf %{buildroot}
install -d -m 755 %{buildroot}%{initddir}
## install_append content
install -d -m 755 %{buildroot}%{goenableddir}
install -d -m 755 %{buildroot}%{systemddir}
install -d -m 755 %{buildroot}%{systemddir}/config
install -p -D -m 700 worker_config %{buildroot}%{initddir}/worker_config
install -p -D -m 700 worker_services %{buildroot}%{initddir}/worker_services
install -p -D -m 664 workerconfig.service %{buildroot}%{systemddir}/workerconfig-standalone.service
install -p -D -m 664 workerconfig-combined.service %{buildroot}%{systemddir}/workerconfig-combined.service
%post
if [ ! -e $D%{systemddir}/workerconfig.service ]; then
cp $D%{systemddir}/config/workerconfig-standalone.service $D%{systemddir}/workerconfig.service
else
cmp -s $D%{systemddir}/config/workerconfig-standalone.service $D%{systemddir}/workerconfig.service
if [ $? -ne 0 ]; then
rm -f $D%{systemddir}/workerconfig.service
cp $D%{systemddir}/config/workerconfig-standalone.service $D%{systemddir}/workerconfig.service
fi
fi
systemctl enable workerconfig.service
if [ ! -e $D%{systemddir}/workerconfig.service ]; then
cp $D%{systemddir}/config/workerconfig-combined.service $D%{systemddir}/workerconfig.service
else
cmp -s $D%{systemddir}/config/workerconfig-combined.service $D%{systemddir}/workerconfig.service
if [ $? -ne 0 ]; then
rm -f $D%{systemddir}/workerconfig.service
cp $D%{systemddir}/config/workerconfig-combined.service $D%{systemddir}/workerconfig.service
fi
fi
systemctl enable workerconfig.service
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/worker_config
/usr/local/etc/init.d/worker_services

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/workerconfig-combined.service
/usr/lib/systemd/system/workerconfig-standalone.service
