#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-drbd
Version  : 0.3.1
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-drbd-0.3.1.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-drbd-0.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-drbd-data = %{version}-%{release}
Requires: puppet-concat
Requires: puppet-stdlib
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch
Patch2: 0001-TIS-Patches.patch
Patch3: 0002-Disable-timeout-for-mkfs-command.patch
Patch4: 0003-drbd-parallel-to-serial-synchronization.patch
Patch5: 0004-US-96914-reuse-existing-drbd-cinder-resource.patch
Patch6: 0005-Add-PausedSync-states-to-acceptable-cstate.patch
Patch7: 0006-CGTS-7164-Add-resource-options-cpu-mask-to-affine-drbd-kernel-threads.patch
Patch8: 0007-Add-disk-by-path-test.patch
Patch9: 0008-CGTS-7953-support-for-new-drbd-resources.patch
Patch10: 0009-drbd-slow-before-swact.patch

%description
# DRBD module for Puppet
[![Build Status](https://travis-ci.org/voxpupuli/puppet-drbd.png?branch=master)](https://travis-ci.org/voxpupuli/puppet-drbd)
[![Code Coverage](https://coveralls.io/repos/github/voxpupuli/puppet-drbd/badge.svg?branch=master)](https://coveralls.io/github/voxpupuli/puppet-drbd)
[![Puppet Forge](https://img.shields.io/puppetforge/v/puppet/drbd.svg)](https://forge.puppetlabs.com/puppet/drbd)
[![Puppet Forge - downloads](https://img.shields.io/puppetforge/dt/puppet/drbd.svg)](https://forge.puppetlabs.com/puppet/drbd)
[![Puppet Forge - endorsement](https://img.shields.io/puppetforge/e/puppet/drbd.svg)](https://forge.puppetlabs.com/puppet/drbd)
[![Puppet Forge - scores](https://img.shields.io/puppetforge/f/puppet/drbd.svg)](https://forge.puppetlabs.com/puppet/drbd)

%package data
Summary: data components for the puppet-drbd package.
Group: Data

%description data
data components for the puppet-drbd package.


%prep
%setup -q -n puppetlabs-drbd
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568794854
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568794854
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/drbd
## install_append content
cp -rp * %{buildroot}%{_datadir}/puppet/modules/drbd/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/drbd/CHANGELOG.md
/usr/share/puppet/modules/drbd/CONTRIBUTING.md
/usr/share/puppet/modules/drbd/Gemfile
/usr/share/puppet/modules/drbd/LICENSE
/usr/share/puppet/modules/drbd/Makefile
/usr/share/puppet/modules/drbd/README.md
/usr/share/puppet/modules/drbd/Rakefile
/usr/share/puppet/modules/drbd/examples/site.pp
/usr/share/puppet/modules/drbd/files/drbd.conf
/usr/share/puppet/modules/drbd/manifests/init.pp
/usr/share/puppet/modules/drbd/manifests/migration.pp
/usr/share/puppet/modules/drbd/manifests/resource.pp
/usr/share/puppet/modules/drbd/manifests/resource/enable.pp
/usr/share/puppet/modules/drbd/manifests/resource/up.pp
/usr/share/puppet/modules/drbd/manifests/service.pp
/usr/share/puppet/modules/drbd/metadata.json
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/centos-511-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/centos-66-x64-pe.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/centos-66-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/centos-72-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/debian-78-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/debian-82-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/centos-5.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/centos-6.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/centos-7.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/debian-7.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/debian-8.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/ubuntu-12.04.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/ubuntu-14.04.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/docker/ubuntu-16.04.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/ubuntu-server-1204-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/ubuntu-server-1404-x64.yml
/usr/share/puppet/modules/drbd/spec/acceptance/nodesets/ubuntu-server-1604-x64.yml
/usr/share/puppet/modules/drbd/spec/classes/coverage_spec.rb
/usr/share/puppet/modules/drbd/spec/classes/drbd_spec.rb
/usr/share/puppet/modules/drbd/spec/default_facts.yml
/usr/share/puppet/modules/drbd/spec/defines/resource_spec.rb.backup
/usr/share/puppet/modules/drbd/spec/spec_helper.rb
/usr/share/puppet/modules/drbd/templates/global_common.conf.erb
/usr/share/puppet/modules/drbd/templates/header.res.erb
/usr/share/puppet/modules/drbd/templates/primary-resource.res.erb
/usr/share/puppet/modules/drbd/templates/primary-stacked-resource.res.erb
/usr/share/puppet/modules/drbd/templates/resource.res.erb
/usr/share/puppet/modules/drbd/templates/secondary-resource.res.erb
/usr/share/puppet/modules/drbd/templates/secondary-stacked-resource.res.erb
