#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fm-api
Version  : 1.0
Release  : 11
URL      : file:///home/clr/stx-tar/fm-api-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/fm-api-1.0.tar.gz
Summary  : CGTS Platform Fault Management Python API Package
Group    : Development/Tools
License  : Apache-2.0
Requires: fm-api-python = %{version}-%{release}
Requires: fm-api-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : setuptools

%description
for applications to raise/clear/update active alarms.

%package doc
Summary: doc components for the fm-api package.
Group: Documentation

%description doc
doc components for the fm-api package.


%package python
Summary: python components for the fm-api package.
Group: Default
Requires: fm-api-python3 = %{version}-%{release}

%description python
python components for the fm-api package.


%package python3
Summary: python3 components for the fm-api package.
Group: Default
Requires: python3-core

%description python3
python3 components for the fm-api package.


%prep
%setup -q -n fm-api-1.0

%build
## build_prepend content
%define pythonroot %{_libdir}/python2.7/site-packages
%define doc_deploy_dir /usr/share/doc
python setup.py build
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568107897
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
python setup.py install --root=%{buildroot} \
--install-lib=%{pythonroot} \
--prefix=%{_prefix} \
--install-data=%{_datadir} \
--single-version-externally-managed
DOC_DEPLOY=%{buildroot}/%{doc_deploy_dir}
install -d $DOC_DEPLOY
install -m 644 fm_api/constants.py $DOC_DEPLOY
## install_append end

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/constants.py

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
