#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-ryu
Version  : 4.19
Release  : 3
URL      : file:///home/clr/stx-tar/python-ryu-4.19.tar.gz
Source0  : file:///home/clr/stx-tar/python-ryu-4.19.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: python-ryu-bin = %{version}-%{release}
Requires: python-ryu-python = %{version}-%{release}
Requires: python-ryu-python3 = %{version}-%{release}
Requires: Routes
Requires: WebOb
Requires: debtcollector
Requires: eventlet
Requires: lxml
Requires: msgpack
Requires: netaddr
Requires: oslo.config
Requires: paramiko
Requires: six
Requires: tinyrpc
BuildRequires : Routes
BuildRequires : Sphinx
BuildRequires : WebOb
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : eventlet
BuildRequires : greenlet
BuildRequires : lxml
BuildRequires : msgpack
BuildRequires : oslo.config
BuildRequires : ovs
BuildRequires : ovs-python
BuildRequires : paramiko
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : repoze.lru
BuildRequires : routes-python
BuildRequires : setuptools
BuildRequires : tinyrpc
BuildRequires : tinyrpc-python
BuildRequires : webob-python
BuildRequires : wheel

%description
What's Ryu
==========
Ryu is a component-based software defined networking framework.

%package bin
Summary: bin components for the python-ryu package.
Group: Binaries

%description bin
bin components for the python-ryu package.


%package python
Summary: python components for the python-ryu package.
Group: Default
Requires: python-ryu-python3 = %{version}-%{release}

%description python
python components for the python-ryu package.


%package python3
Summary: python3 components for the python-ryu package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-ryu package.


%prep
%setup -q -n python-ryu-4.19

%build
## build_prepend content
export PBR_VERSION=%{version}
cd doc && make man
cd ../
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570784437
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
echo "dont need check"
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
%define _sysconfdir	/usr/local/etc
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -d -m 755 %{buildroot}%{_sysconfdir}/ryu
mv %{buildroot}/usr/etc/ryu/ryu.conf %{buildroot}%{_sysconfdir}/ryu/ryu.conf
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/ryu/ryu.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/ryu
/usr/bin/ryu-manager

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
