#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nfscheck
Version  : 1.0
Release  : 2
URL      : file:///home/clear/tar/nfscheck-1.0.tar.gz
Source0  : file:///home/clear/tar/nfscheck-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: nfscheck-bin = %{version}-%{release}
Requires: nfscheck-data = %{version}-%{release}
Requires: nfscheck-services = %{version}-%{release}
Requires: systemd
Requires: util-linux

%description
No detailed description available

%package bin
Summary: bin components for the nfscheck package.
Group: Binaries
Requires: nfscheck-data = %{version}-%{release}
Requires: nfscheck-services = %{version}-%{release}

%description bin
bin components for the nfscheck package.


%package data
Summary: data components for the nfscheck package.
Group: Data

%description data
data components for the nfscheck package.


%package services
Summary: services components for the nfscheck package.
Group: Systemd services

%description services
services components for the nfscheck package.


%prep
%setup -q -n nfscheck-1.0

%build
## build_prepend content
%define license /usr/share/licenses/%{name}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568685416
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568685416
rm -rf %{buildroot}
install -d -m 755 %{buildroot}/usr/bin/
## install_append content
install -m 755 nfscheck.sh %{buildroot}/usr/bin/nfscheck.sh
install -d -m 755 %{buildroot}/usr/lib/systemd/system/
install -m 664 nfscheck.service %{buildroot}/usr/lib/systemd/system/nfscheck.service
install -d -m 755 ${RPM_BUILD_ROOT}%{license}
install -m 500 LICENSE ${RPM_BUILD_ROOT}%{license}
%post
/usr/bin/systemctl enable nfscheck.service >/dev/null 2>&1
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nfscheck.sh

%files data
%defattr(-,root,root,-)
/usr/share/licenses/nfscheck/LICENSE

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/nfscheck.service
