PKG_NAME := registry-token-server
URL = file:///home/clr/stx-tar/registry-token-server-1.0.0.tar.gz
ARCHIVES = file:///home/clr/stx-tar/docker-distribution-48294d928ced5dd9b378f7fd7c6f5da3ff3f2c89.tar.gz : file:///home/clr/stx-tar/docker-libtrust-fa567046d9b14f6aa788882a950d69651d230b21.tar.gz : file:///home/clr/stx-tar/gophercloud-gophercloud-aa00757ee3ab58e53520b6cb910ca0543116400a.tar.gz : file:///home/clr/stx-tar/gorilla-context-08b5f424b9271eedf6f9f0ce86cb9396ed337a42.tar.gz : file:///home/clr/stx-tar/gorilla-mux-456bcfa82d672db7cae587c9b541463f65bc2718.tar.gz : file:///home/clr/stx-tar/Sirupsen-logrus-55eb11d21d2a31a3cc93838241d04800f52e823d.tar.gz : file:///home/clr/stx-tar/token-server.tar.gz :

include ../common/Makefile.common
