#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-staging
Version  : 1
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-staging-b466d93.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-staging-b466d93.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-staging-data = %{version}-%{release}
Requires: puppet >= 2.7.0
Patch1: 0001-add-makefile.patch
Patch2: 0001-Rename-nanliu-staging-to-puppet-staging.patch

%description
# Staging module for Puppet
Manages staging directory, along with download/extraction of compressed files.

%package data
Summary: data components for the puppet-staging package.
Group: Data

%description data
data components for the puppet-staging package.


%prep
%setup -q -n puppet-staging-b466d93f8deb0ed4d9762a17c3c38f356aa833ee
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568706333
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568706333
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}/%{_datadir}/openstack-puppet/modules/staging/
## install_append content
cp -rp * %{buildroot}/%{_datadir}/openstack-puppet/modules/staging/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/openstack-puppet/modules/staging/Gemfile
/usr/share/openstack-puppet/modules/staging/LICENSE
/usr/share/openstack-puppet/modules/staging/Makefile
/usr/share/openstack-puppet/modules/staging/README.md
/usr/share/openstack-puppet/modules/staging/Rakefile
/usr/share/openstack-puppet/modules/staging/Vagrantfile
/usr/share/openstack-puppet/modules/staging/docs/deploy.html
/usr/share/openstack-puppet/modules/staging/docs/extract.html
/usr/share/openstack-puppet/modules/staging/docs/file.html
/usr/share/openstack-puppet/modules/staging/docs/init.html
/usr/share/openstack-puppet/modules/staging/files/sample
/usr/share/openstack-puppet/modules/staging/files/sample.tar.bz2
/usr/share/openstack-puppet/modules/staging/files/sample.tar.gz
/usr/share/openstack-puppet/modules/staging/lib/facter/staging_http_get.rb
/usr/share/openstack-puppet/modules/staging/lib/facter/staging_windir.rb
/usr/share/openstack-puppet/modules/staging/lib/puppet/parser/functions/scope_defaults.rb
/usr/share/openstack-puppet/modules/staging/lib/puppet/parser/functions/staging_parse.rb
/usr/share/openstack-puppet/modules/staging/manifests/deploy.pp
/usr/share/openstack-puppet/modules/staging/manifests/extract.pp
/usr/share/openstack-puppet/modules/staging/manifests/file.pp
/usr/share/openstack-puppet/modules/staging/manifests/init.pp
/usr/share/openstack-puppet/modules/staging/manifests/params.pp
/usr/share/openstack-puppet/modules/staging/metadata.json
/usr/share/openstack-puppet/modules/staging/spec/defines/staging_deploy_spec.rb
/usr/share/openstack-puppet/modules/staging/spec/defines/staging_extract_spec.rb
/usr/share/openstack-puppet/modules/staging/spec/defines/staging_file_spec.rb
/usr/share/openstack-puppet/modules/staging/spec/fixtures/hiera.yaml
/usr/share/openstack-puppet/modules/staging/spec/spec_helper.rb
/usr/share/openstack-puppet/modules/staging/spec/unit/puppet/parser/functions/scope_defaults_spec.rb
/usr/share/openstack-puppet/modules/staging/spec/unit/puppet/parser/functions/staging_parse_spec.rb
/usr/share/openstack-puppet/modules/staging/tests/deploy.pp
/usr/share/openstack-puppet/modules/staging/tests/extract.pp
/usr/share/openstack-puppet/modules/staging/tests/file.pp
/usr/share/openstack-puppet/modules/staging/tests/init.pp
/usr/share/openstack-puppet/modules/staging/tests/scope_defaults.pp
/usr/share/openstack-puppet/modules/staging/tests/staging_parse.pp
