#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : drbd
Version  : 8.4.3
Release  : 3
URL      : file:///home/clear/clearlinux/packages/drbd/drbd-8.4.3.tar.gz
Source0  : file:///home/clear/clearlinux/packages/drbd/drbd-8.4.3.tar.gz
Source1  : drbd.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: drbd-bin = %{version}-%{release}
Requires: drbd-man = %{version}-%{release}
Requires: drbd-services = %{version}-%{release}
BuildRequires : flex
BuildRequires : libxslt-bin
Patch1: 0001-skip_wait_con_int_on_simplex.patch
Patch2: 0002-drbd-conditional-crm-dependency.patch
Patch3: 0003-drbd_report_condition.patch
Patch4: 0004-drbdadm-ipaddr-change.patch
Patch5: 0005-drbd_reconnect_standby_standalone.patch
Patch6: 0006-avoid-kernel-userspace-version-check.patch
Patch7: 0007-Update-OCF-to-attempt-connect-in-certain-states.patch
Patch8: 0008-Increase-short-cmd-timeout-to-15-secs.patch
Patch9: 0009-Check-for-mounted-device-before-demoting-Primary-DRB.patch
Patch10: 0010-Maor-minor-function-not-find.patch

%description
DRBD
======
by Philipp Reisner
and Lars Ellenberg
LINBIT Information Technologies

%package bin
Summary: bin components for the drbd package.
Group: Binaries
Requires: drbd-services = %{version}-%{release}

%description bin
bin components for the drbd package.


%package man
Summary: man components for the drbd package.
Group: Default

%description man
man components for the drbd package.


%package services
Summary: services components for the drbd package.
Group: Systemd services

%description services
services components for the drbd package.


%prep
%setup -q -n drbd-8.4.3
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567482689
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1567482689
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/drbd.service

%files
%defattr(-,root,root,-)
/lib/drbd/drbdadm-83
/lib/drbd/drbdsetup-83
/usr/lib/drbd/crm-fence-peer.sh
/usr/lib/drbd/crm-unfence-peer.sh
/usr/lib/drbd/notify-emergency-reboot.sh
/usr/lib/drbd/notify-emergency-shutdown.sh
/usr/lib/drbd/notify-io-error.sh
/usr/lib/drbd/notify-out-of-sync.sh
/usr/lib/drbd/notify-pri-lost-after-sb.sh
/usr/lib/drbd/notify-pri-lost.sh
/usr/lib/drbd/notify-pri-on-incon-degr.sh
/usr/lib/drbd/notify-split-brain.sh
/usr/lib/drbd/notify.sh
/usr/lib/drbd/outdate-peer.sh
/usr/lib/drbd/snapshot-resync-target-lvm.sh
/usr/lib/drbd/stonith_admin-fence-peer.sh
/usr/lib/drbd/unsnapshot-resync-target-lvm.sh
/usr/lib/ocf/resource.d/linbit/drbd

%files bin
%defattr(-,root,root,-)
/usr/bin/drbd-overview
/usr/bin/drbdadm
/usr/bin/drbdmeta
/usr/bin/drbdsetup

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/drbd.conf.5
/usr/share/man/man8/drbd.8
/usr/share/man/man8/drbdadm.8
/usr/share/man/man8/drbddisk.8
/usr/share/man/man8/drbdmeta.8
/usr/share/man/man8/drbdsetup.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/drbd.service
