#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-filemapper
Version  : 1.1.3
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-filemapper-1.1.3.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-filemapper-1.1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-filemapper-data = %{version}-%{release}
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch

%description
Puppet FileMapper
=================
Synopsis
--------
Map files to resources and back with this handy dandy mixin!

%package data
Summary: data components for the puppet-filemapper package.
Group: Data

%description data
data components for the puppet-filemapper package.


%prep
%setup -q -n packstack
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568793710
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568793710
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/filemapper
## install_append content
cp -R puppet/modules/filemapper %{buildroot}%{_datadir}/puppet/modules
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/filemapper/.gitignore
/usr/share/puppet/modules/filemapper/.travis.yml
/usr/share/puppet/modules/filemapper/CHANGELOG
/usr/share/puppet/modules/filemapper/Gemfile
/usr/share/puppet/modules/filemapper/Guardfile
/usr/share/puppet/modules/filemapper/LICENSE
/usr/share/puppet/modules/filemapper/Modulefile
/usr/share/puppet/modules/filemapper/README.markdown
/usr/share/puppet/modules/filemapper/lib/puppetx/filemapper.rb
/usr/share/puppet/modules/filemapper/manifests/init.pp
/usr/share/puppet/modules/filemapper/spec/spec_helper.rb
/usr/share/puppet/modules/filemapper/spec/unit/puppetx/filemapper_spec.rb
