#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-rabbitmq
Version  : 5ac45de
Release  : 1
URL      : file:///home/clr/stx-tar/puppetlabs-rabbitmq-5ac45de.tar.gz
Source0  : file:///home/clr/stx-tar/puppetlabs-rabbitmq-5ac45de.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-rabbitmq-data = %{version}-%{release}
Requires: puppet >= 2.7.0
Requires: puppet-staging
Requires: puppet-stdlib
Patch1: 0001-add-makefile.patch
Patch2: 0001-Roll-up-TIS-patches.patch
Patch3: 0002-Changed-cipher-specification-to-openssl-format.patch
Patch4: 0003-Eliminate-Puppet-4-deprecation-warnings.patch
Patch5: 0004-Partially-revert-upstream-commit-f7c3a4a637d59f3065d.patch
Patch6: 0005-Remove-the-rabbitmq_nodename-fact.patch

%description
# rabbitmq
#### Table of Contents
1. [Overview](#overview)
2. [Module Description - What the module does and why it is useful](#module-description)
3. [Setup - The basics of getting started with rabbitmq](#setup)
* [What rabbitmq affects](#what-rabbitmq-affects)
* [Setup requirements](#setup-requirements)
* [Beginning with rabbitmq](#beginning-with-rabbitmq)
4. [Usage - Configuration options and additional functionality](#usage)
5. [Reference - An under-the-hood peek at what the module is doing and how](#reference)
5. [Limitations - OS compatibility, etc.](#limitations)
* [RedHat module dependencies](#redhat-module-dependecies)
6. [Development - Guide for contributing to the module](#development)

%package data
Summary: data components for the puppet-rabbitmq package.
Group: Data

%description data
data components for the puppet-rabbitmq package.


%prep
%setup -q -n puppet-rabbitmq-5ac45dedd9b409c9efac654724bc74867cb9233b
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568709547
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568709547
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}/%{_datadir}/openstack-puppet/modules/rabbitmq/
## install_append content
cp -rp * %{buildroot}/%{_datadir}/openstack-puppet/modules/rabbitmq/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/openstack-puppet/modules/rabbitmq/CHANGELOG.md
/usr/share/openstack-puppet/modules/rabbitmq/CONTRIBUTING.md
/usr/share/openstack-puppet/modules/rabbitmq/Gemfile
/usr/share/openstack-puppet/modules/rabbitmq/LICENSE
/usr/share/openstack-puppet/modules/rabbitmq/MAINTAINERS.md
/usr/share/openstack-puppet/modules/rabbitmq/Makefile
/usr/share/openstack-puppet/modules/rabbitmq/NOTICE
/usr/share/openstack-puppet/modules/rabbitmq/README.md
/usr/share/openstack-puppet/modules/rabbitmq/Rakefile
/usr/share/openstack-puppet/modules/rabbitmq/examples/erlang_deps.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/full.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/permissions/add.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/plugin.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/repo/apt.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/server.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/service.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/site.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/user/add.pp
/usr/share/openstack-puppet/modules/rabbitmq/examples/vhosts/add.pp
/usr/share/openstack-puppet/modules/rabbitmq/files/README.markdown
/usr/share/openstack-puppet/modules/rabbitmq/files/plugins/amqp_client-2.3.1.ez
/usr/share/openstack-puppet/modules/rabbitmq/files/plugins/rabbit_stomp-2.3.1.ez
/usr/share/openstack-puppet/modules/rabbitmq/lib/facter/rabbitmq_version.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/provider/rabbitmqctl.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_binding.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_erlang_cookie.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_exchange.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_parameter.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_plugin.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_policy.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_queue.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_user.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_user_permissions.rb
/usr/share/openstack-puppet/modules/rabbitmq/lib/puppet/type/rabbitmq_vhost.rb
/usr/share/openstack-puppet/modules/rabbitmq/locales/config.yaml
/usr/share/openstack-puppet/modules/rabbitmq/manifests/config.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/init.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/install.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/install/rabbitmqadmin.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/management.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/params.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/repo/apt.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/repo/rhel.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/server.pp
/usr/share/openstack-puppet/modules/rabbitmq/manifests/service.pp
/usr/share/openstack-puppet/modules/rabbitmq/metadata.json
/usr/share/openstack-puppet/modules/rabbitmq/spec/README.markdown
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/class_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/clustering_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/delete_guest_user_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/nodesets/centos-7-x64.yml
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/nodesets/debian-8-x64.yml
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/nodesets/default.yml
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/nodesets/docker/centos-7.yml
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/nodesets/docker/debian-8.yml
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/nodesets/docker/ubuntu-14.04.yml
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/parameter_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/policy_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/queue_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/rabbitmqadmin_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/server_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/user_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/vhost_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/acceptance/zz281_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/classes/rabbitmq_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/spec_helper.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/spec_helper_acceptance.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/spec_helper_local.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_policy/rabbitmqctl_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_queue/rabbitmqadmin_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_user_permissions/rabbitmqctl_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/provider/rabbitmq_vhost/rabbitmqctl_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_binding_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_exchange_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_parameter_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_plugin_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_policy_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_queue_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_user_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/puppet/type/rabbitmq_vhost_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/spec/unit/rabbitmq_version_spec.rb
/usr/share/openstack-puppet/modules/rabbitmq/templates/README.markdown
/usr/share/openstack-puppet/modules/rabbitmq/templates/default.erb
/usr/share/openstack-puppet/modules/rabbitmq/templates/inetrc.erb
/usr/share/openstack-puppet/modules/rabbitmq/templates/limits.conf
/usr/share/openstack-puppet/modules/rabbitmq/templates/rabbitmq-env.conf.erb
/usr/share/openstack-puppet/modules/rabbitmq/templates/rabbitmq-server.service.d/limits.conf
/usr/share/openstack-puppet/modules/rabbitmq/templates/rabbitmq.config.erb
/usr/share/openstack-puppet/modules/rabbitmq/templates/rabbitmqadmin.conf.erb
