#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : grubby
Version  : 8.28.1
Release  : 11
URL      : file:///home/clear/tar/grubby-8.28-1.tar.bz2
Source0  : file:///home/clear/tar/grubby-8.28-1.tar.bz2
Source1  : file:///home/clear/tar/prune_debug.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: grubby-bin = %{version}-%{release}
Requires: grubby-libexec = %{version}-%{release}
Requires: grubby-man = %{version}-%{release}
Requires: grubby-python = %{version}-%{release}
Requires: python-dev
Requires: system-release
BuildRequires : git
BuildRequires : glib-devel
BuildRequires : grub
BuildRequires : pkg-config
BuildRequires : popt-dev
BuildRequires : setuptools
BuildRequires : util-linux-dev
Patch1: 0001-Only-set-RPM_OPT_FLAGS-if-undefined.patch
Patch2: 0002-If-we-re-using-multiboot-add-a-new-mbmodule-not-an-i.patch
Patch3: 0003-Use-PREFIX-during-make-install.patch
Patch4: 0004-Honor-linux16-and-initrd16.patch
Patch5: 0005-If-we-re-on-a-zipl-based-platform-use-banner-passed-.patch
Patch6: 0006-Support-devicetree-directive-in-grub2.patch
Patch7: 0007-Actually-USE-DEVTREE-in-new-kernel-pkg.patch
Patch8: 0008-Use-the-correct-load-commands-for-aarch64-efi.patch
Patch9: 0009-Always-choose-linux-initrd-on-efi-only-platforms.patch
Patch10: 0010-extlinux-Understand-default-properly.patch
Patch11: 0011-extlinux-Add-test-suite.patch
Patch12: 0012-grub-Fix-a-crash-with-kernel-line-without-being-prec.patch
Patch13: 0013-grub-Remove-a-redundant-test.patch
Patch14: 0014-Fix-bad-check-for-new-kernel-pkg-s-command-line-argu.patch
Patch15: 0015-Previous-ARM-64-bit-test-had-the-wrong-compiler-defi.patch
Patch16: 0016-Actually-do-a-fix-for-rhbz-1082318-that-fixes-the-is.patch
Patch17: 0017-Strip-the-LT_END-line-from-a-new-stanza-before-addin.patch
Patch18: 0018-Fix-a-wrong-test-case-lacked-boot-filesystem.patch
Patch19: 0019-Don-t-go-past-the-last-element-of-indexVars-in-findE.patch
Patch20: 0020-Tell-a-slightly-better-fib-about-default-bootloader-.patch
Patch21: 0021-Make-findTemplate-actually-return-the-saved-default.patch
Patch22: 0022-Support-filtering-update-kernel-by-title-as-well.patch
Patch23: 0023-Conditionally-create-debug-entries-when-installing-k.patch
Patch24: 0024-Always-error-check-getLineByType.patch
Patch25: 0025-Get-the-error-checking-on-getLineByType-return-right.patch
Patch26: 0026-Fix-ppc-kernelName-when-invoked-by-installkernel.patch
Patch27: 0027-Update-grubby-man-page-for-Power8-PPC64LE.patch
Patch28: 0028-Update-man-page-to-include-default-config-file-for-s.patch
Patch29: 0029-Split-the-test-case-for-rescue-images-into-tests-wit.patch
Patch30: 0030-Actually-get-the-test-from-a7800d8f-right.patch
Patch31: 0031-Strdup-the-right-place-in-title-extraction.patch
Patch32: 0032-Make-the-cases-for-0cb78dab-actually-work-not-just-n.patch
Patch33: 0033-grub2ExtractTitle-and-extractTitle-don-t-do-the-same.patch
Patch34: 0034-Set-envFile-from-env-when-bootloader-is-not-specifie.patch
Patch35: 0035-grubby-properly-handle-mixed-and-and-nested-quotes.patch
Patch36: 0036-Don-t-put-spaces-in-debug-entries-on-zipl-platforms.patch
Patch37: 0037-Drop-SEGV-handler.patch
Patch38: 0038-Add-a-bunch-of-tests-for-various-default-kernel-titl.patch
Patch39: 0039-Emit-better-systemd-debug-settings-on-debug-entries.patch
Patch40: 0040-Make-the-grub1-defaultkernel-test-more-reliable.patch
Patch41: 0041-Work-around-aarch64-not-having-quite-the-same-grub-c.patch
Patch42: 0042-ppc64le-sync-grub.cfg-changes-to-disk-1212114.patch
Patch43: 0043-Make-it-possible-to-run-test.sh-verbose-from-the-mak.patch
Patch44: 0044-Don-t-leak-from-one-extractTitle-call.patch
Patch45: 0045-Better-formatting.patch
Patch46: 0046-Make-SET_VARIABLE-get-handled-individually-in-GetNex.patch
Patch47: 0047-Specify-bootloader-directory-in-the-test-case-for-11.patch
Patch48: 0048-Fix-some-coverity-concerns.patch
Patch49: 0049-Always-do-the-rungrubby-debug-after-the-normal-kerne.patch
Patch50: 0050-grubby-add-set-index-to-specify-which-position-to-ad.patch
Patch51: 0051-Fix-thinko-on-set-index-naming.patch
Patch52: 0052-Fix-a-typo-on-the-rhel-7.3-branch.patch
Patch53: 0053-Add-a-test-case-for-a-failure-rmarshall-saw-in-set-i.patch
Patch54: 0054-Ensure-command-line-updates-also-honor-set-index.patch
Patch55: 0055-Change-debug-entry-insertion-order-rhbz-1285601.patch
Patch56: 0056-Reorganize-grubby-man-page-1232168.patch
Patch57: 0057-Update-grubby-man-page-contents-bz1232168.patch
Patch58: 0058-Fix-inline-help-typo-1232168.patch
Patch59: 0059-More-edits-for-grubby.8-1232168.patch
Patch60: 0060-Minor-man-page-changes-1232168.patch
Patch61: 0061-Rename-setDefaultImage-variables.patch
Patch62: 0062-Add-index-constant-definitions-instead-of-open-coded.patch
Patch63: 0063-Track-configuration-modifications.patch
Patch64: 0064-Fix-some-test-cases-where-the-resulting-default-inde.patch
Patch65: 0065-Don-t-assume-make-default-just-because-set-index-was.patch
Patch66: 0066-Clarify-set-default-index-in-the-man-page.patch
Patch67: 0067-Add-multi-entry-removal-test-1285601.patch
Patch68: 0068-Fix-findTemplate-index-logic-1285601.patch
Patch69: 0069-Write-correct-default-to-environment-1285601.patch
Patch70: 0070-Initialize-variable-for-ppc-environment-1285601.patch
Patch71: 0071-Fix-initial-saved_entry-read-issue-1285601.patch
Patch72: 0072-Add-s390-s390x-info-test-1285601.patch
Patch73: 0073-Fix-info-for-s390x-s390-1285601.patch
Patch74: 0074-Add-s390-s390x-set-default-index-test-1285601.patch
Patch75: 0075-Fix-setDefaultImage-for-s390-s390x-1285601.patch
Patch76: 0076-grubby-Make-sure-configure-BOOTLOADER-variables-are-.patch
Patch77: 1000-Generic-name-for-Titanium.patch
Patch78: 1001-Add-support-for-updating-grub-cfg-with-multiboot-2.patch

%description
No detailed description available

%package bin
Summary: bin components for the grubby package.
Group: Binaries
Requires: grubby-libexec = %{version}-%{release}

%description bin
bin components for the grubby package.


%package libexec
Summary: libexec components for the grubby package.
Group: Default

%description libexec
libexec components for the grubby package.


%package man
Summary: man components for the grubby package.
Group: Default

%description man
man components for the grubby package.


%package python
Summary: python components for the grubby package.
Group: Default

%description python
python components for the grubby package.


%prep
%setup -q -n grubby-8.28-1
cd ..
%setup -q -T -D -n grubby-8.28-1 -b 1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1
%patch15 -p1
%patch16 -p1
%patch17 -p1
%patch18 -p1
%patch19 -p1
%patch20 -p1
%patch21 -p1
%patch22 -p1
%patch23 -p1
%patch24 -p1
%patch25 -p1
%patch26 -p1
%patch27 -p1
%patch28 -p1
%patch29 -p1
%patch30 -p1
%patch31 -p1
%patch32 -p1
%patch33 -p1
%patch34 -p1
%patch35 -p1
%patch36 -p1
%patch37 -p1
%patch38 -p1
%patch39 -p1
%patch40 -p1
%patch41 -p1
%patch42 -p1
%patch43 -p1
%patch44 -p1
%patch45 -p1
%patch46 -p1
%patch47 -p1
%patch48 -p1
%patch49 -p1
%patch50 -p1
%patch51 -p1
%patch52 -p1
%patch53 -p1
%patch54 -p1
%patch55 -p1
%patch56 -p1
%patch57 -p1
%patch58 -p1
%patch59 -p1
%patch60 -p1
%patch61 -p1
%patch62 -p1
%patch63 -p1
%patch64 -p1
%patch65 -p1
%patch66 -p1
%patch67 -p1
%patch68 -p1
%patch69 -p1
%patch70 -p1
%patch71 -p1
%patch72 -p1
%patch73 -p1
%patch74 -p1
%patch75 -p1
%patch76 -p1
%patch77 -p1
%patch78 -p1

%build
## build_prepend content
%define pythonroot  /usr/lib64/python2.7/site-packages
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567493247
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1567493247
rm -rf %{buildroot}
make install DESTDIR=$RPM_BUILD_ROOT PREFIX=%{_prefix} mandir=%{_mandir}
## install_append content
install -d -m 0755 $RPM_BUILD_ROOT/usr/libexec/grubby/
tar -xzvf %{SOURCE1}
install -m 0755 prune_debug $RPM_BUILD_ROOT/usr/libexec/grubby/
install -d -m 0755 $RPM_BUILD_ROOT/%{pythonroot}/grubby
install -m 644 grub_cfg_update.py $RPM_BUILD_ROOT/%{pythonroot}/grubby/grub_cfg_update.py
install -m 644 __init__.py $RPM_BUILD_ROOT/%{pythonroot}/grubby/__init__.py
install -m 500 grub-cfg-update $RPM_BUILD_ROOT/usr/sbin/grub-cfg-update
%clean
rm -rf $RPM_BUILD_ROOT
%post
/usr/libexec/grubby/prune_debug
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/sbin/grub-cfg-update
/usr/sbin/grubby
/usr/sbin/installkernel
/usr/sbin/new-kernel-pkg

%files libexec
%defattr(-,root,root,-)
/usr/libexec/grubby/prune_debug

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/grubby.8
/usr/share/man/man8/installkernel.8
/usr/share/man/man8/new-kernel-pkg.8

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*
