#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lighttpd
Version  : 1.4.52
Release  : 5
URL      : file:///home/clear/tar/lighttpd-1.4.52.tar.gz
Source0  : file:///home/clear/tar/lighttpd-1.4.52.tar.gz
Source1  : lighttpd.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: lighttpd-bin = %{version}-%{release}
Requires: lighttpd-man = %{version}-%{release}
Requires: lighttpd-services = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : buildreq-scons
BuildRequires : bzip2-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(zlib)
BuildRequires : util-linux-dev
BuildRequires : valgrind
Patch1: 0001-lighttpd-1.4.39-defaultconf.patch
Patch2: 0002-lighttpd-1.4.35-system-crypto-policy.patch
Patch3: 0003-lighttpd-1.4.39-socket.patch
Patch4: check-content-length.patch
Patch5: lighttpd-tpm-support.patch
Patch6: 0004-modify-check-test-fail.patch

%description
========
lighttpd
========
-------------
a light httpd
-------------
:abstract:
lighttpd a secure, fast, compliant and very flexible web-server
which has been optimized for high-performance environments. It has a very
low memory footprint compared to other webservers and takes care of cpu-load.
Its advanced feature-set (FastCGI, CGI, Auth, Output-Compression,
URL-Rewriting and many more) make lighttpd the perfect webserver-software
for every server that is suffering load problems.

%package bin
Summary: bin components for the lighttpd package.
Group: Binaries
Requires: lighttpd-services = %{version}-%{release}

%description bin
bin components for the lighttpd package.


%package dev
Summary: dev components for the lighttpd package.
Group: Development
Requires: lighttpd-bin = %{version}-%{release}
Provides: lighttpd-devel = %{version}-%{release}
Requires: lighttpd = %{version}-%{release}

%description dev
dev components for the lighttpd package.


%package man
Summary: man components for the lighttpd package.
Group: Default

%description man
man components for the lighttpd package.


%package services
Summary: services components for the lighttpd package.
Group: Systemd services

%description services
services components for the lighttpd package.


%prep
%setup -q -n lighttpd-1.4.52
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568796284
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1568796284
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/lighttpd.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lighttpd
/usr/bin/lighttpd-angel

%files dev
%defattr(-,root,root,-)
/usr/lib64/mod_access.so
/usr/lib64/mod_accesslog.so
/usr/lib64/mod_alias.so
/usr/lib64/mod_auth.so
/usr/lib64/mod_authn_file.so
/usr/lib64/mod_cgi.so
/usr/lib64/mod_compress.so
/usr/lib64/mod_deflate.so
/usr/lib64/mod_dirlisting.so
/usr/lib64/mod_evasive.so
/usr/lib64/mod_evhost.so
/usr/lib64/mod_expire.so
/usr/lib64/mod_extforward.so
/usr/lib64/mod_fastcgi.so
/usr/lib64/mod_flv_streaming.so
/usr/lib64/mod_indexfile.so
/usr/lib64/mod_proxy.so
/usr/lib64/mod_redirect.so
/usr/lib64/mod_rewrite.so
/usr/lib64/mod_rrdtool.so
/usr/lib64/mod_scgi.so
/usr/lib64/mod_secdownload.so
/usr/lib64/mod_setenv.so
/usr/lib64/mod_simple_vhost.so
/usr/lib64/mod_sockproxy.so
/usr/lib64/mod_ssi.so
/usr/lib64/mod_staticfile.so
/usr/lib64/mod_status.so
/usr/lib64/mod_uploadprogress.so
/usr/lib64/mod_userdir.so
/usr/lib64/mod_usertrack.so
/usr/lib64/mod_vhostdb.so
/usr/lib64/mod_webdav.so
/usr/lib64/mod_wstunnel.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/lighttpd-angel.8
/usr/share/man/man8/lighttpd.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/lighttpd.service
