#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tsconfig
Version  : 1.0
Release  : 5
URL      : file:///home/clr/stx-tar/tsconfig-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/tsconfig-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: tsconfig-bin = %{version}-%{release}
Requires: tsconfig-python = %{version}-%{release}
Requires: tsconfig-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
No detailed description available

%package bin
Summary: bin components for the tsconfig package.
Group: Binaries

%description bin
bin components for the tsconfig package.


%package python
Summary: python components for the tsconfig package.
Group: Default
Requires: tsconfig-python3 = %{version}-%{release}

%description python
python components for the tsconfig package.


%package python3
Summary: python3 components for the tsconfig package.
Group: Default
Requires: python3-core

%description python3
python3 components for the tsconfig package.


%prep
%setup -q -n tsconfig-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568185102
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
%define debug_package %{nil}
%define local_dir /usr/
%define local_bindir %{local_dir}/bin/
%define pythonroot /usr/lib64/python2.7/site-packages
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
python3 setup.py install --root=$RPM_BUILD_ROOT --install-lib=%{pythonroot} --prefix=/usr --install-data=/usr/share --single-version-externally-managed
install -d -m 755 %{buildroot}%{local_bindir}
install -p -D -m 700 scripts/tsconfig %{buildroot}%{local_bindir}/tsconfig
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tsconfig

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
