#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-dnsmasq
Version  : 1.1.0
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-dnsmasq-1.1.0.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-dnsmasq-1.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-dnsmasq-data = %{version}-%{release}
Requires: puppet-concat
Requires: puppet-puppi
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch
Patch2: 0001-puppet-dnsmasq-Kilo-quilt-patches.patch
Patch3: 0002-Fixing-mismatched-permission-on-dnsmasq-conf.patch
Patch4: 0003-Support-management-of-tftp_max-option.patch
Patch5: 0004-Enable-clear-DNS-cache-on-reload.patch

%description
# Puppet module: dnsmasq
This is a Puppet module for dnsmasq based on the second generation layout ("NextGen") of Example42 Puppet Modules.

%package data
Summary: data components for the puppet-dnsmasq package.
Group: Data

%description data
data components for the puppet-dnsmasq package.


%prep
%setup -q -n packstack
%patch1 -p1
%patch2 -p2
%patch3 -p2
%patch4 -p2
%patch5 -p2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568795584
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568795584
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/dnsmasq
## install_append content
cp -R puppet/modules/dnsmasq %{buildroot}%{_datadir}/puppet/modules
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/dnsmasq/.fixtures.yml
/usr/share/puppet/modules/dnsmasq/.gitignore
/usr/share/puppet/modules/dnsmasq/.project
/usr/share/puppet/modules/dnsmasq/.rspec
/usr/share/puppet/modules/dnsmasq/.travis.yml
/usr/share/puppet/modules/dnsmasq/Gemfile
/usr/share/puppet/modules/dnsmasq/Modulefile
/usr/share/puppet/modules/dnsmasq/README.md
/usr/share/puppet/modules/dnsmasq/Rakefile
/usr/share/puppet/modules/dnsmasq/TODO
/usr/share/puppet/modules/dnsmasq/manifests/addhost.pp
/usr/share/puppet/modules/dnsmasq/manifests/hostconcat.pp
/usr/share/puppet/modules/dnsmasq/manifests/init.pp
/usr/share/puppet/modules/dnsmasq/manifests/params.pp
/usr/share/puppet/modules/dnsmasq/manifests/spec.pp
/usr/share/puppet/modules/dnsmasq/spec/classes/dnsmasq_spec.rb
/usr/share/puppet/modules/dnsmasq/spec/defines/dnsmasq_addhost_spec.rb
/usr/share/puppet/modules/dnsmasq/spec/defines/dnsmasq_hostconcat_spec.rb
/usr/share/puppet/modules/dnsmasq/spec/spec_helper.rb
/usr/share/puppet/modules/dnsmasq/templates/dnsmasq.conf.erb
/usr/share/puppet/modules/dnsmasq/templates/spec.erb
/usr/share/puppet/modules/dnsmasq/tests/absent.pp
/usr/share/puppet/modules/dnsmasq/tests/disable.pp
/usr/share/puppet/modules/dnsmasq/tests/init.pp
