#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stx-extensions
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/stx-extensions-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/stx-extensions-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: systemd
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%prep
%setup -q -n stx-extensions-1.0
%patch1 -p1

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir	/usr/local/etc
%define local_etc_systemd %{_sysconfdir}/systemd/system/
%define local_etc_coredump %{_sysconfdir}/systemd/coredump.conf.d
%define local_etc_initd %{_sysconfdir}/init.d
%define local_etc_sysctl %{_sysconfdir}/sysctl.d
%define local_etc_modload %{_sysconfdir}/modules-load.d
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568598922
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568598922
rm -rf %{buildroot}
install -d -m 755 %{buildroot}%{local_etc_sysctl}
## install_append content
install -p -D -m 644 coredump-sysctl.conf %{buildroot}%{local_etc_sysctl}/50-coredump.conf
install -d -m 755 %{buildroot}%{local_etc_coredump}
install -p -D -m 644 coredump.conf %{buildroot}%{local_etc_coredump}/coredump.conf
install -d -m 755 %{buildroot}%{local_etc_modload}
install -p -D -m 644 modules-load-vfio.conf %{buildroot}%{local_etc_modload}/vfio.conf
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/modules-load.d/vfio.conf
/usr/local/etc/sysctl.d/50-coredump.conf
/usr/local/etc/systemd/coredump.conf.d/coredump.conf
