#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ntp-config
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/ntp-config-1.0.tar.gz
Source0  : file:///home/clear/tar/ntp-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: ntp-config-data = %{version}-%{release}
Requires: ntp
Requires: ntp-perl
Requires: ntpdate

%description
No detailed description available

%package data
Summary: data components for the ntp-config package.
Group: Data

%description data
data components for the ntp-config package.


%prep
%setup -q -n ntp-config-1.0

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir /usr/local/etc
%define license /usr/share/licenses/%{name}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568687948
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568687948
rm -rf %{buildroot}
install -d %{buildroot}%{_datadir}/starlingx
## install_append content
install -D -m644 ntpd.sysconfig %{buildroot}%{_datadir}/starlingx/ntpd.sysconfig
install -D -m644 ntp.conf %{buildroot}%{_datadir}/starlingx/ntp.conf
install -d -m 755 ${RPM_BUILD_ROOT}%{license}
install -m 500 LICENSE ${RPM_BUILD_ROOT}%{license}
%post
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/ntpd.sysconfig %{_sysconfdir}/sysconfig/ntpd
cp -f %{_datadir}/starlingx/ntp.conf %{_sysconfdir}/ntp.conf
chmod 644 %{_sysconfdir}/sysconfig/ntpd
chmod 644 %{_sysconfdir}/ntp.conf
fi
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/licenses/ntp-config/LICENSE
/usr/share/starlingx/ntp.conf
/usr/share/starlingx/ntpd.sysconfig
