#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : util-linux-config
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/util-linux-config-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/util-linux-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: util-linux-config-data = %{version}-%{release}
Requires: util-linux
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package data
Summary: data components for the util-linux-config package.
Group: Data

%description data
data components for the util-linux-config package.


%prep
%setup -q -n util-linux-config-1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568188789
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568188789
rm -rf %{buildroot}
## install_prepend content
%global _sysconfdir	'/usr/local/etc'
## install_prepend end
%{__install} -d 644            %{buildroot}%{_datadir}/starlingx/
## install_append content
%{__install} -m 644 stx.su     %{buildroot}%{_datadir}/starlingx/stx.su
%{__install} -m 644 stx.login  %{buildroot}%{_datadir}/starlingx/stx.login
%post
%define _pamconfdir %{_sysconfdir}/pam.d
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/stx.su     %{_pamconfdir}/su
cp -f %{_datadir}/starlingx/stx.login  %{_pamconfdir}/login
fi
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/stx.login
/usr/share/starlingx/stx.su
