#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sysinv-agent
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/sysinv-agent-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/sysinv-agent-1.0.tar.gz
Summary  : CGCS Host Inventory Init Package
Group    : Development/Tools
License  : Apache-2.0
Requires: sysinv-agent-services = %{version}-%{release}
BuildRequires : systemd-devel
Patch1: 0001-change-sysconfig-dir.patch
Patch2: 0001-add-makefile.patch

%description
No detailed description available

%package services
Summary: services components for the sysinv-agent package.
Group: Systemd services

%description services
services components for the sysinv-agent package.


%prep
%setup -q -n sysinv-agent-1.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568273684
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568273684
rm -rf %{buildroot}
## install_prepend content
%define local_etc_initd /usr/local/etc/init.d/
%define local_etc_pmond /usr/local/etc/pmon.d/
%define _unitdir /usr/lib/systemd/system/
%define debug_package %{nil}
## install_prepend end
install -d -m 755 %{buildroot}%{local_etc_initd}
## install_append content
install -d -m 755 %{buildroot}%{local_etc_initd}
install -p -D -m 755 sysinv-agent %{buildroot}%{local_etc_initd}/sysinv-agent
install -d -m 755 %{buildroot}%{local_etc_pmond}
install -p -D -m 644 sysinv-agent.conf %{buildroot}%{local_etc_pmond}/sysinv-agent.conf
install -p -D -m 644 sysinv-agent.service %{buildroot}%{_unitdir}/sysinv-agent.service
%post
/usr/bin/systemctl enable sysinv-agent.service >/dev/null 2>&1
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/sysinv-agent
/usr/local/etc/pmon.d/sysinv-agent.conf

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/sysinv-agent.service
