#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pci-irq-affinity-agent
Version  : 1.0
Release  : 3
URL      : file:///home/clr/stx-tar/pci-irq-affinity-agent-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/pci-irq-affinity-agent-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: pci-irq-affinity-agent-bin = %{version}-%{release}
Requires: pci-irq-affinity-agent-python = %{version}-%{release}
Requires: pci-irq-affinity-agent-python3 = %{version}-%{release}
Requires: pci-irq-affinity-agent-services = %{version}-%{release}
Requires: python-novaclient
BuildRequires : buildreq-distutils3
BuildRequires : setuptools
BuildRequires : systemd-devel
Patch1: 0001-change-sysconfig-dir.patch

%description
No detailed description available

%package bin
Summary: bin components for the pci-irq-affinity-agent package.
Group: Binaries
Requires: pci-irq-affinity-agent-services = %{version}-%{release}

%description bin
bin components for the pci-irq-affinity-agent package.


%package python
Summary: python components for the pci-irq-affinity-agent package.
Group: Default
Requires: pci-irq-affinity-agent-python3 = %{version}-%{release}

%description python
python components for the pci-irq-affinity-agent package.


%package python3
Summary: python3 components for the pci-irq-affinity-agent package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pci-irq-affinity-agent package.


%package services
Summary: services components for the pci-irq-affinity-agent package.
Group: Systemd services

%description services
services components for the pci-irq-affinity-agent package.


%prep
%setup -q -n pci-irq-affinity-agent-1.0
%patch1 -p1

%build
## build_prepend content
%define local_etc_initd /usr/local/etc/init.d/
%define local_etc_pmond /usr/local/etc/pmon.d/
%define pythonroot           /usr/lib64/python2.7/site-packages
%define debug_package %{nil}
%define _unitdir /usr/lib/systemd/system/
%define _sysconfdir	/usr/local/etc
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568944321
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
install -d -m 0755 %{buildroot}%{_datadir}/openstack-puppet/modules/horizon/
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
python3 setup.py install --root=%{buildroot} \
--install-lib=%{pythonroot} \
--prefix=/usr \
--install-data=/usr/share \
--single-version-externally-managed
%{__install}  -d -m 755 %{buildroot}%{local_etc_initd}
%{__install}  -p -D -m 755 pci-irq-affinity-agent %{buildroot}%{local_etc_initd}/pci-irq-affinity-agent
%{__install}  -d -m 755 %{buildroot}%{local_etc_pmond}
%{__install}  -p -D -m 644 pci-irq-affinity-agent.conf %{buildroot}%{local_etc_pmond}/pci-irq-affinity-agent.conf
%{__install}  -p -D -m 644 pci-irq-affinity-agent.service %{buildroot}%{_unitdir}/pci-irq-affinity-agent.service
%{__install}  -d  %{buildroot}%{_bindir}
%{__install}  -p -D -m 755 nova-sriov %{buildroot}%{_bindir}/nova-sriov
%{__install}  -d  %{buildroot}%{_sysconfdir}/pci_irq_affinity
%{__install}  -p -D -m 600 config.ini %{buildroot}%{_sysconfdir}/pci_irq_affinity/config.ini
%post
/usr/bin/systemctl enable pci-irq-affinity-agent.service >/dev/null 2>&1
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/pci-irq-affinity-agent
/usr/local/etc/pci_irq_affinity/config.ini
/usr/local/etc/pmon.d/pci-irq-affinity-agent.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/nova-sriov
/usr/bin/pci-irq-affinity-agent

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/pci-irq-affinity-agent.service
