#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-lvm
Version  : 0.5.0
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-lvm-0.5.0.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-lvm-0.5.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: puppet-lvm-data = %{version}-%{release}
Requires: puppet-stdlib
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch
Patch2: 0001-puppet-lvm-kilo-quilt-changes.patch
Patch3: 0002-UEFI-pvcreate-fix.patch
Patch4: 0003-US94222-Persistent-Dev-Naming.patch
Patch5: 0004-extendind-nuke_fs_on_resize_failure-functionality.patch
Patch6: Fix-the-logical-statement-for-nuke_fs_on_resize.patch

%description
Puppet LVM Module
=================
Provides Logical Resource Management (LVM) features for Puppet.

%package data
Summary: data components for the puppet-lvm package.
Group: Data

%description data
data components for the puppet-lvm package.


%prep
%setup -q -n packstack
%patch1 -p1
%patch2 -p2
%patch3 -p2
%patch4 -p2
%patch5 -p2
%patch6 -p2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568787958
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568787958
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}%{_datadir}/puppet/modules/lvm
## install_append content
cp -R puppet/modules/lvm %{buildroot}%{_datadir}/puppet/modules
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/lvm/.autotest
/usr/share/puppet/modules/lvm/.fixtures.yml
/usr/share/puppet/modules/lvm/.gitignore
/usr/share/puppet/modules/lvm/.rspec
/usr/share/puppet/modules/lvm/.travis.yml
/usr/share/puppet/modules/lvm/CHANGELOG.md
/usr/share/puppet/modules/lvm/Gemfile
/usr/share/puppet/modules/lvm/LICENSE
/usr/share/puppet/modules/lvm/README.md
/usr/share/puppet/modules/lvm/Rakefile
/usr/share/puppet/modules/lvm/lib/facter/lvm_support.rb
/usr/share/puppet/modules/lvm/lib/puppet/provider/filesystem/aix.rb
/usr/share/puppet/modules/lvm/lib/puppet/provider/filesystem/lvm.rb
/usr/share/puppet/modules/lvm/lib/puppet/provider/logical_volume/aix.rb
/usr/share/puppet/modules/lvm/lib/puppet/provider/logical_volume/lvm.rb
/usr/share/puppet/modules/lvm/lib/puppet/provider/physical_volume/lvm.rb
/usr/share/puppet/modules/lvm/lib/puppet/provider/volume_group/lvm.rb
/usr/share/puppet/modules/lvm/lib/puppet/type/filesystem.rb
/usr/share/puppet/modules/lvm/lib/puppet/type/logical_volume.rb
/usr/share/puppet/modules/lvm/lib/puppet/type/physical_volume.rb
/usr/share/puppet/modules/lvm/lib/puppet/type/volume_group.rb
/usr/share/puppet/modules/lvm/manifests/init.pp
/usr/share/puppet/modules/lvm/manifests/logical_volume.pp
/usr/share/puppet/modules/lvm/manifests/volume.pp
/usr/share/puppet/modules/lvm/manifests/volume_group.pp
/usr/share/puppet/modules/lvm/metadata.json
/usr/share/puppet/modules/lvm/spec/lib/helpers.rb
/usr/share/puppet/modules/lvm/spec/lib/matchers.rb
/usr/share/puppet/modules/lvm/spec/spec_helper.rb
/usr/share/puppet/modules/lvm/spec/unit/classes/lvm_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/facter/lvm_support_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/provider/filesystem/lvm_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/provider/logical_volume/lvm_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/provider/physical_volume/lvm_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/provider/volume_group/lvm_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/type/filesystem_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/type/logical_volume_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/type/physical_volume_spec.rb
/usr/share/puppet/modules/lvm/spec/unit/puppet/type/volume_group_spec.rb
