#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-keystone
Version  : 11.3.0
Release  : 1
URL      : file:///home/clr/stx-tar/puppet-keystone-11.3.0.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-keystone-11.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-keystone-data = %{version}-%{release}
Requires: puppet-keystone-python = %{version}-%{release}
Requires: puppet-keystone-python3 = %{version}-%{release}
Requires: puppet >= 2.7.0
Requires: puppet-apache
Requires: puppet-inifile
Requires: puppet-openstacklib
Requires: puppet-oslo
Requires: puppet-stdlib
BuildRequires : buildreq-distutils3
BuildRequires : pbr
Patch1: 0001-add-makefile.patch
Patch2: 0001-pike-rebase-squash-titanium-patches.patch
Patch3: 0002-remove-the-Keystone-admin-app.patch
Patch4: 0003-remove-eventlet_bindhost-from-Keystoneconf.patch
Patch5: 0004-escape-special-characters-in-bootstrap.patch
Patch6: 0005-Add-support-for-fernet-receipts.patch

%description
Team and repository tags
========================
[![Team and repository tags](http://governance.openstack.org/badges/puppet-keystone.svg)](http://governance.openstack.org/reference/tags/index.html)

%package data
Summary: data components for the puppet-keystone package.
Group: Data

%description data
data components for the puppet-keystone package.


%package python
Summary: python components for the puppet-keystone package.
Group: Default
Requires: puppet-keystone-python3 = %{version}-%{release}

%description python
python components for the puppet-keystone package.


%package python3
Summary: python3 components for the puppet-keystone package.
Group: Default
Requires: python3-core

%description python3
python3 components for the puppet-keystone package.


%prep
%setup -q -n openstack-keystone-11.3.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
## build_prepend content
export PBR_VERSION=%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568789352
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
echo "dont need check"
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
install -d -m 0755 %{buildroot}%{_datadir}/openstack-puppet/modules/keystone/
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
cp -rp * %{buildroot}%{_datadir}/openstack-puppet/modules/keystone/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/openstack-puppet/modules/keystone/CHANGELOG.md
/usr/share/openstack-puppet/modules/keystone/Gemfile
/usr/share/openstack-puppet/modules/keystone/LICENSE
/usr/share/openstack-puppet/modules/keystone/Makefile
/usr/share/openstack-puppet/modules/keystone/README.md
/usr/share/openstack-puppet/modules/keystone/Rakefile
/usr/share/openstack-puppet/modules/keystone/bindep.txt
/usr/share/openstack-puppet/modules/keystone/checksums.json
/usr/share/openstack-puppet/modules/keystone/examples/apache_dropin.pp
/usr/share/openstack-puppet/modules/keystone/examples/apache_with_paths.pp
/usr/share/openstack-puppet/modules/keystone/examples/k2k_sp_shib.pp
/usr/share/openstack-puppet/modules/keystone/examples/ldap_backend.pp
/usr/share/openstack-puppet/modules/keystone/examples/ldap_full.pp
/usr/share/openstack-puppet/modules/keystone/examples/ldap_identity.pp
/usr/share/openstack-puppet/modules/keystone/examples/user_project_user_role_composite_namevar.pp
/usr/share/openstack-puppet/modules/keystone/examples/v3_basic.pp
/usr/share/openstack-puppet/modules/keystone/examples/v3_domain_configuration.pp
/usr/share/openstack-puppet/modules/keystone/ext/keystone_test.rb
/usr/share/openstack-puppet/modules/keystone/ext/keystone_test_v3.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone/util.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_config/ini_setting.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_domain/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_domain_config/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_endpoint/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_identity_provider/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_paste_ini/ini_setting.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_role/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_service/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_tenant/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_user/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/provider/keystone_user_role/openstack.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_config.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_domain.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_domain_config.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_endpoint.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_identity_provider.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_paste_ini.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_role.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_service.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_tenant.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_user.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet/type/keystone_user_role.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/composite_namevar.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/composite_namevar/helpers.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/composite_namevar/helpers/utilities.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/type.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/type/default_domain.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/type/read_only.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone/type/required.rb
/usr/share/openstack-puppet/modules/keystone/lib/puppet_x/keystone_config/ini_setting.rb
/usr/share/openstack-puppet/modules/keystone/manifests/client.pp
/usr/share/openstack-puppet/modules/keystone/manifests/config.pp
/usr/share/openstack-puppet/modules/keystone/manifests/cors.pp
/usr/share/openstack-puppet/modules/keystone/manifests/cron/fernet_rotate.pp
/usr/share/openstack-puppet/modules/keystone/manifests/cron/token_flush.pp
/usr/share/openstack-puppet/modules/keystone/manifests/db.pp
/usr/share/openstack-puppet/modules/keystone/manifests/db/mysql.pp
/usr/share/openstack-puppet/modules/keystone/manifests/db/postgresql.pp
/usr/share/openstack-puppet/modules/keystone/manifests/db/sync.pp
/usr/share/openstack-puppet/modules/keystone/manifests/deps.pp
/usr/share/openstack-puppet/modules/keystone/manifests/disable_admin_token_auth.pp
/usr/share/openstack-puppet/modules/keystone/manifests/endpoint.pp
/usr/share/openstack-puppet/modules/keystone/manifests/federation/identity_provider.pp
/usr/share/openstack-puppet/modules/keystone/manifests/federation/mellon.pp
/usr/share/openstack-puppet/modules/keystone/manifests/federation/openidc.pp
/usr/share/openstack-puppet/modules/keystone/manifests/federation/openidc_httpd_configuration.pp
/usr/share/openstack-puppet/modules/keystone/manifests/federation/shibboleth.pp
/usr/share/openstack-puppet/modules/keystone/manifests/init.pp
/usr/share/openstack-puppet/modules/keystone/manifests/ldap.pp
/usr/share/openstack-puppet/modules/keystone/manifests/ldap_backend.pp
/usr/share/openstack-puppet/modules/keystone/manifests/logging.pp
/usr/share/openstack-puppet/modules/keystone/manifests/messaging/amqp.pp
/usr/share/openstack-puppet/modules/keystone/manifests/params.pp
/usr/share/openstack-puppet/modules/keystone/manifests/policy.pp
/usr/share/openstack-puppet/modules/keystone/manifests/python.pp
/usr/share/openstack-puppet/modules/keystone/manifests/resource/authtoken.pp
/usr/share/openstack-puppet/modules/keystone/manifests/resource/service_identity.pp
/usr/share/openstack-puppet/modules/keystone/manifests/roles/admin.pp
/usr/share/openstack-puppet/modules/keystone/manifests/security_compliance.pp
/usr/share/openstack-puppet/modules/keystone/manifests/service.pp
/usr/share/openstack-puppet/modules/keystone/manifests/wsgi/apache.pp
/usr/share/openstack-puppet/modules/keystone/metadata.json
/usr/share/openstack-puppet/modules/keystone/puppet_keystone.egg-info/PKG-INFO
/usr/share/openstack-puppet/modules/keystone/puppet_keystone.egg-info/SOURCES.txt
/usr/share/openstack-puppet/modules/keystone/puppet_keystone.egg-info/dependency_links.txt
/usr/share/openstack-puppet/modules/keystone/puppet_keystone.egg-info/not-zip-safe
/usr/share/openstack-puppet/modules/keystone/puppet_keystone.egg-info/top_level.txt
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/Add-cert-and-key-files-specifically-for-the-admin-endpoint-815e0109247d6f70.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/Add-servername-for-admin-endpoint-vhost-c62a86939e5b9e49.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/Create-domain-on-ldap_backend-resource-ac3cc85bc101883e.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/add-notification-transport-url-2a2d023520d8301e.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/add_messaging_default_parameters-8719a35df77146e1.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/add_oslo_messaging_amqp1-04e7a2a4951c65f4.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/add_target_admin_domain-272f97b06e476495.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/admin_password_parameter-df9a4b5056fedd44.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/authtoken-os_service_default-eb8809222b21e05a.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/authtoken_memcache_package-3b459c97a205cdf1.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/autocreate-keystone-role-98c565ce590d9d32.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/changes_around_keystone_manage_commands-5bbf256bb24c0a81.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/deprecate-group_allow_ldap-params-671a23e9813f1d75.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/deprecate-user_allow_ldap-params-0b8b6d2a53d7d818.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/deprecate_pki_signing-ae35fe25182735ab.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/deprecate_signing_dir_parameter-3123a377ef197813.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/deprecated_ldap-02957eb56827ead5.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/deprecated_uuid_default_token-33090f377b0086b7.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/disable_admin_token_auth-b82d0aca80d1f091.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/drop_qpid-50eb89c1bec84504.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/ensure_parameter_service_identity_resource-610076e4902c23ec.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/federation_with_mellon-2f8229c1464b2e0e.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fernet_rotate_crontab-aad7ddda61d8ee31.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fernet_token_provider-700f0feb36e0e168.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix-cache-configs-a3972486723f1d99.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix-wsgi-params-366be2d75d6792c8.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_admin-fee6e76089c07a42.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_endpoint_region-0fa0d89061ebaf12.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_endpoint_update_when_missing-4cd73e06a8ac30f7.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_ldap_packages-3dd59f5bfa5a5bc0.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_log_dir_documentation-0ecb8eb4c98c5cbf.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_openrc_v2-64049769daf57b65.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/fix_retry_for_keystone_user_exists-53987cf3bfac4f6e.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/hash_domains-d6a867466bcf324b.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/hourly-token-flush-175800b7f614f26e.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/httpd-logs-syslog-51bff89ca52d21a1.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/implement-chase-referrals-02cc67c98c272f52.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/ipv6_provider-796b60badd356e59.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone-credential-setup-0971292cf1b0bde7.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone-fernet-setup-227ef6d380519cce.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone-wsgi-scripts-0d772d1f9f2d6c57.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone_bootstrap-4bf00198001d3350.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone_cors-00694edf25d53324.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone_hooks_support-2c9e8b09bdbd1b5b.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone_identity_provider-9b6f6b3ad70c60f3.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystone_python_depr-80fa804d9cd242c5.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/keystonev3-919f2e4842670c0f.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/ldap_backend_domain-37839afb8b1d26e4.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/make-replacing-fernet-keys-configurable-4e8f342f4a8ec67a.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/manage_ldap_packages-3b739e338f3e59c2.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/mellon-websso-support-8c367e5b732ffbf3.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/multi_domain_configuration-32dc8cbef450f1d6.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/multi_ldap-975858a46dd622a6.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/optional-email-parameter-for-roles::admin-2a17a5d13fa172da.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/os_service_default-9caeeb340d4bb303.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/os_workers_for_worker_count-50c1f496bf4dc954.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/permissions_on_keys_and_creds-9c0b9f56dfc1fd63.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/policy_driver-c991dd693d2336fc.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/policy_rc_d_keystone_eventlet-2dc65eb3d27f8969.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/rabbit-connection-params-deprecation-c6e990b4f788505d.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/remove_deprecated_keystone_signing_dir_option-ac9691ad2165491a.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/remove_unused_class-0615d6744896ad97.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/remove_verbose-6cbdd66294362090.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/service_provider_deprecation-50421064c823f3ee.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/stop_posix_and_files-930ee921d0ebead2.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/support_multi_domain-bd04f18aa7913eaa.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/switch_to_oslo-b7caf6d5906e29dc.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/uca_newton-434b3f07a06be290.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/update_authtoken-c3b672875f4c5b50.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/use-reno-1caaec4ba5aa4285.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/verbose-deprecation-38d9b7667fcf381d.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/notes/wsgi_process_options-9c7149dd45d835b7.yaml
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/_static/.placeholder
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/conf.py
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/index.rst
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/mitaka.rst
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/newton.rst
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/ocata.rst
/usr/share/openstack-puppet/modules/keystone/releasenotes/source/unreleased.rst
/usr/share/openstack-puppet/modules/keystone/setup.cfg
/usr/share/openstack-puppet/modules/keystone/setup.py
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/default_domain_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/keystone_federation_identity_provider_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/keystone_federation_shibboleth_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/keystone_wsgi_apache_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/nodesets/centos-70-x64.yml
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/nodesets/default.yml
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/nodesets/nodepool-centos7.yml
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/nodesets/nodepool-trusty.yml
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/nodesets/nodepool-xenial.yml
/usr/share/openstack-puppet/modules/keystone/spec/acceptance/nodesets/ubuntu-server-1404-x64.yml
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_client_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_config_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_cors_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_cron_fernet_rotate_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_cron_token_flush_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_db_mysql_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_db_postgresql_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_db_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_db_sync_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_deps_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_disable_admin_token_auth_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_endpoint_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_federation_identity_provider_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_federation_mellon_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_federation_openidc_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_federation_shibboleth_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_init_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_ldap_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_logging_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_messaging_amqp_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_policy_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_roles_admin_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_security_compliance_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_service_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/classes/keystone_wsgi_apache_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/defines/keystone_ldap_backend_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/defines/keystone_resource_authtoken_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/defines/keystone_resource_service_identity_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/shared_examples.rb
/usr/share/openstack-puppet/modules/keystone/spec/shared_examples_acceptance.rb
/usr/share/openstack-puppet/modules/keystone/spec/spec.opts
/usr/share/openstack-puppet/modules/keystone/spec/spec_helper.rb
/usr/share/openstack-puppet/modules/keystone/spec/spec_helper_acceptance.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone/util_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_config/ini_setting_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_domain/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_domain_config/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_endpoint/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_identity_provider/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_paste_ini/ini_setting_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_role/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_service/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_tenant/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_user/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/provider/keystone_user_role/openstack_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_config_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_domain_config_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_endpoint_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_identity_provider_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_paste_ini_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_service_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_tenant_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_user_role_spec.rb
/usr/share/openstack-puppet/modules/keystone/spec/unit/type/keystone_user_spec.rb
/usr/share/openstack-puppet/modules/keystone/templates/mellon.conf.erb
/usr/share/openstack-puppet/modules/keystone/templates/openidc.conf.erb
/usr/share/openstack-puppet/modules/keystone/templates/shibboleth.conf.erb
/usr/share/openstack-puppet/modules/keystone/test-requirements.txt
/usr/share/openstack-puppet/modules/keystone/tests/site.pp
/usr/share/openstack-puppet/modules/keystone/tox.ini

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
