#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libibverbs
Version  : 41mlnx1
Release  : 2
URL      : file:///home/clear/tar/libibverbs-41mlnx1.tar.gz
Source0  : file:///home/clear/tar/libibverbs-41mlnx1.tar.gz
Summary  : A library for direct userspace use of RDMA (InfiniBand/iWARP) hardware
Group    : Development/Tools
License  : GPL-2.0
Requires: libibverbs-bin = %{version}-%{release}
Requires: libibverbs-lib = %{version}-%{release}
Requires: libibverbs-man = %{version}-%{release}
BuildRequires : libnl-devel
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : valgrind-dev

%description
libibverbs is a library that allows userspace processes to use RDMA
"verbs" as described in the InfiniBand Architecture Specification and
the RDMA Protocol Verbs Specification.  This includes direct hardware
access from userspace to InfiniBand/iWARP adapters (kernel bypass) for
fast path operations.

For this library to be useful, a device-specific plug-in module should
also be installed.

%package bin
Summary: bin components for the libibverbs package.
Group: Binaries

%description bin
bin components for the libibverbs package.


%package dev
Summary: dev components for the libibverbs package.
Group: Development
Requires: libibverbs-lib = %{version}-%{release}
Requires: libibverbs-bin = %{version}-%{release}
Provides: libibverbs-devel = %{version}-%{release}
Requires: libibverbs = %{version}-%{release}

%description dev
dev components for the libibverbs package.


%package lib
Summary: lib components for the libibverbs package.
Group: Libraries

%description lib
lib components for the libibverbs package.


%package man
Summary: man components for the libibverbs package.
Group: Default

%description man
man components for the libibverbs package.


%prep
%setup -q -n libibverbs-41mlnx1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568719215
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags} CFLAGS=" "

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
echo "no check"

%install
export SOURCE_DATE_EPOCH=1568719215
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install
## install_append content
rm -f $RPM_BUILD_ROOT%{_libdir}/*.la
%clean
rm -rf $RPM_BUILD_ROOT
%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ibv_asyncwatch
/usr/bin/ibv_cc_pingpong
/usr/bin/ibv_dcini
/usr/bin/ibv_dctgt
/usr/bin/ibv_devices
/usr/bin/ibv_devinfo
/usr/bin/ibv_intf
/usr/bin/ibv_polldcinfo
/usr/bin/ibv_rc_pingpong
/usr/bin/ibv_srq_pingpong
/usr/bin/ibv_task_pingpong
/usr/bin/ibv_uc_pingpong
/usr/bin/ibv_ud_pingpong
/usr/bin/ibv_umr
/usr/bin/ibv_xsrq_pingpong

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/arch.h
/usr/include/infiniband/driver.h
/usr/include/infiniband/driver_exp.h
/usr/include/infiniband/kern-abi.h
/usr/include/infiniband/kern-abi_exp.h
/usr/include/infiniband/marshall.h
/usr/include/infiniband/ofa_verbs.h
/usr/include/infiniband/opcode.h
/usr/include/infiniband/peer_ops.h
/usr/include/infiniband/sa-kern-abi.h
/usr/include/infiniband/sa.h
/usr/include/infiniband/verbs.h
/usr/include/infiniband/verbs_exp.h
/usr/lib64/libibverbs.so
/usr/share/man/man3/ibv_ack_async_event.3
/usr/share/man/man3/ibv_ack_cq_events.3
/usr/share/man/man3/ibv_alloc_mw.3
/usr/share/man/man3/ibv_alloc_pd.3
/usr/share/man/man3/ibv_attach_mcast.3
/usr/share/man/man3/ibv_bind_mw.3
/usr/share/man/man3/ibv_close_device.3
/usr/share/man/man3/ibv_close_xrcd.3
/usr/share/man/man3/ibv_create_ah.3
/usr/share/man/man3/ibv_create_ah_from_wc.3
/usr/share/man/man3/ibv_create_comp_channel.3
/usr/share/man/man3/ibv_create_cq.3
/usr/share/man/man3/ibv_create_flow.3
/usr/share/man/man3/ibv_create_qp.3
/usr/share/man/man3/ibv_create_qp_ex.3
/usr/share/man/man3/ibv_create_srq.3
/usr/share/man/man3/ibv_create_srq_ex.3
/usr/share/man/man3/ibv_dealloc_mw.3
/usr/share/man/man3/ibv_dealloc_pd.3
/usr/share/man/man3/ibv_dereg_mr.3
/usr/share/man/man3/ibv_destroy_ah.3
/usr/share/man/man3/ibv_destroy_comp_channel.3
/usr/share/man/man3/ibv_destroy_cq.3
/usr/share/man/man3/ibv_destroy_flow.3
/usr/share/man/man3/ibv_destroy_qp.3
/usr/share/man/man3/ibv_destroy_srq.3
/usr/share/man/man3/ibv_detach_mcast.3
/usr/share/man/man3/ibv_event_type_str.3
/usr/share/man/man3/ibv_exp_alloc_dm.3
/usr/share/man/man3/ibv_exp_alloc_ec_calc.3
/usr/share/man/man3/ibv_exp_alloc_mkey_list_memory.3
/usr/share/man/man3/ibv_exp_bind_mw.3
/usr/share/man/man3/ibv_exp_cqe_ts_to_ns.3
/usr/share/man/man3/ibv_exp_create_cq.3
/usr/share/man/man3/ibv_exp_create_dct.3
/usr/share/man/man3/ibv_exp_create_flow.3
/usr/share/man/man3/ibv_exp_create_mr.3
/usr/share/man/man3/ibv_exp_create_qp.3
/usr/share/man/man3/ibv_exp_create_res_domain.3
/usr/share/man/man3/ibv_exp_create_rwq_ind_table.3
/usr/share/man/man3/ibv_exp_create_srq.3
/usr/share/man/man3/ibv_exp_create_wq.3
/usr/share/man/man3/ibv_exp_dealloc_ec_calc.3
/usr/share/man/man3/ibv_exp_dealloc_mkey_list_memory.3
/usr/share/man/man3/ibv_exp_destroy_flow.3
/usr/share/man/man3/ibv_exp_destroy_res_domain.3
/usr/share/man/man3/ibv_exp_destroy_rwq_ind_table.3
/usr/share/man/man3/ibv_exp_destroy_wq.3
/usr/share/man/man3/ibv_exp_ec_decode_async.3
/usr/share/man/man3/ibv_exp_ec_decode_sync.3
/usr/share/man/man3/ibv_exp_ec_encode_async.3
/usr/share/man/man3/ibv_exp_ec_encode_sync.3
/usr/share/man/man3/ibv_exp_ec_update_async.3
/usr/share/man/man3/ibv_exp_ec_update_sync.3
/usr/share/man/man3/ibv_exp_free_dm.3
/usr/share/man/man3/ibv_exp_get_provider_func.3
/usr/share/man/man3/ibv_exp_memcpy_dm.3
/usr/share/man/man3/ibv_exp_modify_cq.3
/usr/share/man/man3/ibv_exp_modify_qp.3
/usr/share/man/man3/ibv_exp_modify_wq.3
/usr/share/man/man3/ibv_exp_open_device.3
/usr/share/man/man3/ibv_exp_peer_abort_peek_cq.3
/usr/share/man/man3/ibv_exp_peer_commit_qp.3
/usr/share/man/man3/ibv_exp_peer_peek_cq.3
/usr/share/man/man3/ibv_exp_poll_cq.3
/usr/share/man/man3/ibv_exp_post_send.3
/usr/share/man/man3/ibv_exp_post_srq_ops.3
/usr/share/man/man3/ibv_exp_post_task.3
/usr/share/man/man3/ibv_exp_prefetch_mr.3
/usr/share/man/man3/ibv_exp_query_dct.3
/usr/share/man/man3/ibv_exp_query_device.3
/usr/share/man/man3/ibv_exp_query_gid_attr.3
/usr/share/man/man3/ibv_exp_query_intf.3
/usr/share/man/man3/ibv_exp_query_mkey.3
/usr/share/man/man3/ibv_exp_query_values.3
/usr/share/man/man3/ibv_exp_reg_mr.3
/usr/share/man/man3/ibv_exp_release_intf.3
/usr/share/man/man3/ibv_exp_rereg_mr.3
/usr/share/man/man3/ibv_exp_rollback_qp.3
/usr/share/man/man3/ibv_fork_init.3
/usr/share/man/man3/ibv_free_device_list.3
/usr/share/man/man3/ibv_get_async_event.3
/usr/share/man/man3/ibv_get_cq_event.3
/usr/share/man/man3/ibv_get_device_guid.3
/usr/share/man/man3/ibv_get_device_list.3
/usr/share/man/man3/ibv_get_device_name.3
/usr/share/man/man3/ibv_get_srq_num.3
/usr/share/man/man3/ibv_inc_rkey.3
/usr/share/man/man3/ibv_init_ah_from_wc.3
/usr/share/man/man3/ibv_modify_qp.3
/usr/share/man/man3/ibv_modify_srq.3
/usr/share/man/man3/ibv_node_type_str.3
/usr/share/man/man3/ibv_open_device.3
/usr/share/man/man3/ibv_open_qp.3
/usr/share/man/man3/ibv_open_xrcd.3
/usr/share/man/man3/ibv_poll_cq.3
/usr/share/man/man3/ibv_port_state_str.3
/usr/share/man/man3/ibv_post_recv.3
/usr/share/man/man3/ibv_post_send.3
/usr/share/man/man3/ibv_post_srq_recv.3
/usr/share/man/man3/ibv_query_device.3
/usr/share/man/man3/ibv_query_device_ex.3
/usr/share/man/man3/ibv_query_gid.3
/usr/share/man/man3/ibv_query_pkey.3
/usr/share/man/man3/ibv_query_port.3
/usr/share/man/man3/ibv_query_qp.3
/usr/share/man/man3/ibv_query_srq.3
/usr/share/man/man3/ibv_rate_to_mbps.3
/usr/share/man/man3/ibv_rate_to_mult.3
/usr/share/man/man3/ibv_reg_mr.3
/usr/share/man/man3/ibv_req_notify_cq.3
/usr/share/man/man3/ibv_rereg_mr.3
/usr/share/man/man3/ibv_resize_cq.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libibverbs.so.1
/usr/lib64/libibverbs.so.1.0.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ibv_asyncwatch.1
/usr/share/man/man1/ibv_cc_pingpong.1
/usr/share/man/man1/ibv_devices.1
/usr/share/man/man1/ibv_devinfo.1
/usr/share/man/man1/ibv_intf.1
/usr/share/man/man1/ibv_rc_pingpong.1
/usr/share/man/man1/ibv_srq_pingpong.1
/usr/share/man/man1/ibv_task_pingpong.1
/usr/share/man/man1/ibv_uc_pingpong.1
/usr/share/man/man1/ibv_ud_pingpong.1
/usr/share/man/man7/peer_direct.7
