#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : worker-utils
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/worker-utils-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/worker-utils-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: worker-utils-bin = %{version}-%{release}
Requires: worker-utils-services = %{version}-%{release}
Requires: /bin/systemctl
Requires: perl
Requires: python
Requires: systemd
BuildRequires : systemd-devel
Patch1: 0001-change-sysconfig-dir.patch
Patch2: 0002-change-sysconfig-dir.patch
Patch3: 0003-Delete-the-wrong-command.patch

%description
No detailed description available

%package bin
Summary: bin components for the worker-utils package.
Group: Binaries
Requires: worker-utils-services = %{version}-%{release}

%description bin
bin components for the worker-utils package.


%package services
Summary: services components for the worker-utils package.
Group: Systemd services

%description services
services components for the worker-utils package.


%prep
%setup -q -n worker-utils-1.0
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568187825
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568187825
rm -rf %{buildroot}
## install_prepend content
%define local_bindir /usr/bin/
%define local_etc_initd /usr/local/etc/init.d/
%define local_etc_platform /usr/local/etc/platform/
%define local_etc_goenabledd /usr/local/etc/goenabled.d/
%define _unitdir /usr/lib/systemd/system/
%define debug_package %{nil}
## install_prepend end
%make_install
## install_append content
make install BINDIR=%{buildroot}%{local_bindir} \
INITDDIR=%{buildroot}%{local_etc_initd} \
GOENABLEDDIR=%{buildroot}%{local_etc_goenabledd} \
PLATFORMCONFDIR=%{buildroot}%{local_etc_platform} \
SYSTEMDDIR=%{buildroot}%{_unitdir}
%post
/bin/systemctl enable affine-platform.sh.service >/dev/null 2>&1
/bin/systemctl enable affine-tasks.service >/dev/null 2>&1
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/goenabled.d/worker-goenabled.sh
/usr/local/etc/init.d/affine-platform.sh
/usr/local/etc/init.d/affine-tasks.sh
/usr/local/etc/init.d/cpumap_functions.sh
/usr/local/etc/init.d/task_affinity_functions.sh
/usr/local/etc/platform/worker_reserved.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/affine-interrupts.sh
/usr/bin/ps-sched.sh
/usr/bin/set-cpu-wakeup-latency.sh
/usr/bin/topology
/usr/bin/topology.py

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/affine-platform.sh.service
/usr/lib/systemd/system/affine-tasks.service
