#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sm
Version  : 1.0.0
Release  : 1
URL      : file:///home/clr/stx-tar/sm-1.0.0.tar.gz
Source0  : file:///home/clr/stx-tar/sm-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: sm-bin = %{version}-%{release}
Requires: sm-services = %{version}-%{release}
Requires: chkconfig
Requires: logrotate
Requires: mtce-pmon
Requires: systemd
Requires: time
BuildRequires : fm-common-dev
BuildRequires : gcc
BuildRequires : glib-dev
BuildRequires : glibc
BuildRequires : json-c
BuildRequires : json-c-dev
BuildRequires : mtce-dev
BuildRequires : openssl-dev
BuildRequires : sm-common-dev
BuildRequires : sm-db-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : systemd
BuildRequires : systemd-devel
Patch1: 0001-fix-snprintf-compiler-error.patch
Patch2: 0002-put-lsqlite3-flag-after-lsm_db.patch
Patch3: 0003-change-sysconfig-dir-to-clear-path.patch

%description
No detailed description available

%package bin
Summary: bin components for the sm package.
Group: Binaries
Requires: sm-services = %{version}-%{release}

%description bin
bin components for the sm package.


%package services
Summary: services components for the sm package.
Group: Systemd services

%description services
services components for the sm package.


%prep
%setup -q -n sm-1.0.0
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
## build_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566357083
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1566357083
rm -rf %{buildroot}
## install_prepend content
%define _unitdir /usr/lib/systemd/system/
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
## install_prepend end
make DEST_DIR=%{buildroot} UNIT_DIR=%{_unitdir} install
## install_append content
%post
/usr/bin/systemctl enable sm.service >/dev/null 2>&1
/usr/bin/systemctl enable sm-shutdown.service >/dev/null 2>&1
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/sm
/usr/local/etc/init.d/sm-shutdown
/usr/local/etc/logrotate.d/sm.logrotate
/usr/local/etc/pmon.d/sm.conf
/usr/local/sbin/sm-notification
/usr/local/sbin/sm-notify
/usr/local/sbin/sm-troubleshoot

%files bin
%defattr(-,root,root,-)
/usr/bin/sm

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/sm-shutdown.service
/usr/lib/systemd/system/sm.service
