#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : shadow-utils-config
Version  : 1
Release  : 1
URL      : file:///home/clr/stx-tar/shadow-utils-config.tar.gz
Source0  : file:///home/clr/stx-tar/shadow-utils-config.tar.gz
Source1  : clear_shadow_locks.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: shadow-utils-config-data = %{version}-%{release}
Requires: shadow-utils-config-services = %{version}-%{release}
Requires: setup
Requires: shadow-utils
BuildRequires : systemd
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package data
Summary: data components for the shadow-utils-config package.
Group: Data

%description data
data components for the shadow-utils-config package.


%package services
Summary: services components for the shadow-utils-config package.
Group: Systemd services

%description services
services components for the shadow-utils-config package.


%prep
%setup -q -n shadow-utils-config-1.0-0
%patch1 -p1

%build
## build_prepend content
%define debug_package %{nil}
%define _sysconfdir	/usr/local/etc
%define _unitdir /usr/lib/systemd/system/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568605801
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568605801
rm -rf %{buildroot}
install -d %{buildroot}%{_sysconfdir}
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/clear_shadow_locks.service
## install_append content
install -d %{buildroot}%{_datadir}/starlingx
install -D -m644 login.defs %{buildroot}%{_datadir}/starlingx/login.defs
install -d -m 755 %{buildroot}%{_sysconfdir}/init.d
install -D -m644 clear_shadow_locks.service %{buildroot}%{_unitdir}/clear_shadow_locks.service
%post
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/login.defs %{_sysconfdir}/
chmod 644 %{_sysconfdir}/login.defs
fi
%systemd_post clear_shadow_locks.service
%preun
%systemd_preun clear_shadow_locks.service
%postun
%systemd_postun_with_restart clear_shadow_locks.service
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/login.defs

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/clear_shadow_locks.service
