#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fm-doc
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/fm-doc-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/fm-doc-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : PyYAML
BuildRequires : fm-api-doc
BuildRequires : fm-common-doc
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package doc
Summary: doc components for the fm-doc package.
Group: Documentation

%description doc
doc components for the fm-doc package.


%prep
%setup -q -n fm-doc-1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569206936
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1569206936
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir	/usr/local/etc
%define  cgcs_doc_deploy_dir /usr/share/doc/cgcs_doc
%define debug_package %{nil}
## install_prepend end
CGCS_DOC_DEPLOY=$RPM_BUILD_ROOT/%{cgcs_doc_deploy_dir}
## install_append content
install -d $CGCS_DOC_DEPLOY
mkdir -p $RPM_BUILD_ROOT/%{_sysconfdir}/fm/
install -m 744 events.yaml $RPM_BUILD_ROOT/%{_sysconfdir}/fm/
install -m 644 events.yaml $CGCS_DOC_DEPLOY
install -m 755 checkEventYaml $CGCS_DOC_DEPLOY
install -m 644 parseEventYaml.py $CGCS_DOC_DEPLOY
install -m 644 check_missing_alarms.py $CGCS_DOC_DEPLOY
pushd $CGCS_DOC_DEPLOY
cp %{cgcs_doc_deploy_dir}/constants.py %{cgcs_doc_deploy_dir}/fmAlarm.h .
./checkEventYaml
rm constants.py* fmAlarm.h*
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/fm/events.yaml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/cgcs_doc/checkEventYaml
/usr/share/doc/cgcs_doc/check_missing_alarms.py
/usr/share/doc/cgcs_doc/events.yaml
/usr/share/doc/cgcs_doc/parseEventYaml.py
