#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stx-ssl
Version  : 1.0.0
Release  : 1
URL      : file:///home/clr/stx-tar/stx-ssl-1.0.0.tar.gz
Source0  : file:///home/clr/stx-tar/stx-ssl-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: stx-ssl-bin = %{version}-%{release}
BuildRequires : openssl
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package bin
Summary: bin components for the stx-ssl package.
Group: Binaries

%description bin
bin components for the stx-ssl package.


%package doc
Summary: doc components for the stx-ssl package.
Group: Documentation

%description doc
doc components for the stx-ssl package.


%prep
%setup -q -n stx-ssl-1.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568272201
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568272201
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir	/usr/local/etc
## install_prepend end
RPM_BUILD_DIR_PKG="%{name}-%{version}"
## install_append content
mkdir -p $RPM_BUILD_DIR_PKG
CSRCONF="$RPM_BUILD_DIR_PKG/server-csr.conf"
PEMFILE="$RPM_BUILD_DIR_PKG/self-signed-server-cert.pem"
cp server-csr.conf $CSRCONF
/usr/bin/openssl req -new -x509 -sha256 -keyout $PEMFILE -out $PEMFILE -days 365 -nodes -config $CSRCONF
mkdir -p $RPM_BUILD_ROOT/%{_sysconfdir}/ssl/private
install -m 400 $PEMFILE $RPM_BUILD_ROOT/%{_sysconfdir}/ssl/private/self-signed-server-cert.pem
mkdir -p $RPM_BUILD_ROOT/%{_sbindir}
install -m 700 tpmdevice-setup $RPM_BUILD_ROOT/%{_sbindir}/tpmdevice-setup
mkdir -p $RPM_BUILD_ROOT/%{_defaultdocdir}/%{name}-%{version}
install -m 644 LICENSE $RPM_BUILD_ROOT/%{_defaultdocdir}/%{name}-%{version}
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/ssl/private/self-signed-server-cert.pem

%files bin
%defattr(-,root,root,-)
/usr/bin/tpmdevice-setup

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/stx-ssl-1.0.0/LICENSE
