#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sm-common
Version  : 1.0.0
Release  : 3
URL      : file:///home/clr/stx-tar/sm-common-1.0.0.tar.gz
Source0  : file:///home/clr/stx-tar/sm-common-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: sm-common-bin = %{version}-%{release}
Requires: sm-common-lib = %{version}-%{release}
Requires: sm-common-services = %{version}-%{release}
Requires: /bin/sh
Requires: mtce-pmon
Requires: sqlite
Requires: systemd
Requires: util-linux
BuildRequires : gcc
BuildRequires : glib-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : util-linux
BuildRequires : util-linux-dev
Patch1: 0001-fix-snprintf-compiler-error.patch
Patch2: 0002-change-sysconfig-dir.patch

%description
No detailed description available

%package bin
Summary: bin components for the sm-common package.
Group: Binaries
Requires: sm-common-services = %{version}-%{release}

%description bin
bin components for the sm-common package.


%package dev
Summary: dev components for the sm-common package.
Group: Development
Requires: sm-common-lib = %{version}-%{release}
Requires: sm-common-bin = %{version}-%{release}
Provides: sm-common-devel = %{version}-%{release}
#Requires: sm-common = %{version}-%{release}

%description dev
dev components for the sm-common package.


%package extras
Summary: extras components for the sm-common package.
Group: Default

%description extras
extras components for the sm-common package.


%package lib
Summary: lib components for the sm-common package.
Group: Libraries

%description lib
lib components for the sm-common package.


%package services
Summary: services components for the sm-common package.
Group: Systemd services

%description services
services components for the sm-common package.


%prep
%setup -q -n sm-common-1.0.0
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
%global _buildsubdir %{_builddir}/%{name}-%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566292839
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} VER=${VER} VER_MJR=$MAJOR


%install
export SOURCE_DATE_EPOCH=1566292839
rm -rf %{buildroot}
## install_prepend content
%global _sysconfdir "/usr/local/etc"
%global _unitdir "/usr/lib/systemd/system"
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
## install_prepend end
make DEST_DIR=$RPM_BUILD_ROOT BIN_DIR=%{_bindir} UNIT_DIR=%{_unitdir} LIB_DIR=%{_libdir} INC_DIR=%{_includedir} VER=$VER VER_MJR=$MAJOR install
## install_append content
install -m 750 -d %{buildroot}/usr
install -m 750 -d %{buildroot}/usr/bin
install -m 750 -p -D %{_buildsubdir}/src/sm_eru %{buildroot}%{_bindir}/sm-eru
install -m 750 -p -D %{_buildsubdir}/src/sm_eru_dump %{buildroot}%{_bindir}/sm-eru-dump
install -m 750 -p -D %{_buildsubdir}/src/sm_watchdog %{buildroot}%{_bindir}/sm-watchdog
install -m 644 -p -D %{_buildsubdir}/scripts/sm-eru.service %{buildroot}%{_unitdir}/sm-eru.service
install -m 644 -p -D %{_buildsubdir}/scripts/sm-watchdog.service %{buildroot}%{_unitdir}/sm-watchdog.service
install -m 750 -d %{buildroot}%{_sysconfdir}/pmon.d
install -m 640 -p -D %{_buildsubdir}/scripts/sm-eru.conf %{buildroot}%{_sysconfdir}/pmon.d/sm-eru.conf
install -m 640 -p -D %{_buildsubdir}/scripts/sm-watchdog.conf %{buildroot}%{_sysconfdir}/pmon.d/sm-watchdog.conf
install -m 750 -p -D %{_buildsubdir}/scripts/sm-eru %{buildroot}%{_sysconfdir}/init.d/sm-eru
install -m 750 -p -D %{_buildsubdir}/scripts/sm-watchdog %{buildroot}%{_sysconfdir}/init.d/sm-watchdog
%post
/usr/bin/systemctl enable sm-watchdog.service >/dev/null 2>&1
/usr/bin/systemctl enable sm-eru.service >/dev/null 2>&1
## install_append end

%files
%defattr(-,root,root,-)
%exclude /usr/local/etc/init.d/sm-eru
%exclude /usr/local/etc/pmon.d/sm-eru.conf
%exclude /var/lib/sm/watchdog/modules/libsm_watchdog_nfs.so
/usr/local/etc/init.d/sm-watchdog
/usr/local/etc/pmon.d/sm-watchdog.conf
/var/lib/sm/watchdog/modules/libsm_watchdog_nfs.so.1
/var/lib/sm/watchdog/modules/libsm_watchdog_nfs.so.1.0.0

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/sm-eru
%exclude /usr/bin/sm-eru-dump
/usr/bin/sm-watchdog

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libsm_common.so
/var/lib/sm/watchdog/modules/libsm_watchdog_nfs.so

%files extras
%defattr(-,root,root,-)
/usr/bin/sm-eru
/usr/bin/sm-eru-dump
/usr/lib/systemd/system/sm-eru.service
/usr/local/etc/init.d/sm-eru
/usr/local/etc/pmon.d/sm-eru.conf

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsm_common.so.1
/usr/lib64/libsm_common.so.1.0.0

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/sm-eru.service
/usr/lib/systemd/system/sm-watchdog.service
