#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : namespace-utils
Version  : 1.0
Release  : 2
URL      : file:///home/clear/tar/namespace-utils-1.0.tar.gz
Source0  : file:///home/clear/tar/namespace-utils-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: namespace-utils-bin = %{version}-%{release}
Requires: namespace-utils-data = %{version}-%{release}

%description
No detailed description available

%package bin
Summary: bin components for the namespace-utils package.
Group: Binaries
Requires: namespace-utils-data = %{version}-%{release}

%description bin
bin components for the namespace-utils package.


%package data
Summary: data components for the namespace-utils package.
Group: Data

%description data
data components for the namespace-utils package.


%prep
%setup -q -n namespace-utils-1.0

%build
## build_prepend content
%define license /usr/share/licenses/%{name}
cc -o bashns bashns.c
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568627702
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} -o bashns bashns.c


%install
export SOURCE_DATE_EPOCH=1568627702
rm -rf %{buildroot}
install -d -m 755 ${RPM_BUILD_ROOT}%{_sbindir}
## install_append content
pwd
install -m 500 bashns ${RPM_BUILD_ROOT}%{_sbindir}
install -m 500 umount-in-namespace ${RPM_BUILD_ROOT}%{_sbindir}
install -d -m 755 ${RPM_BUILD_ROOT}%{license}
install -m 500 LICENSE ${RPM_BUILD_ROOT}%{license}
%clean
rm -rf ${RPM_BUILD_ROOT}
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bashns
/usr/bin/umount-in-namespace

%files data
%defattr(-,root,root,-)
/usr/share/licenses/namespace-utils/LICENSE
