#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : playbookconfig
Version  : 1.0
Release  : 2
URL      : file:///home/clr/stx-tar/playbookconfig-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/playbookconfig-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: playbookconfig-data = %{version}-%{release}
Requires: ansible
Requires: netaddr
Requires: pexpect
Requires: ptyprocess
Requires: python
Requires: sshpass
Requires: sysinv
Patch1: 0001-fix-Makefile-dir.patch

%description
No detailed description available

%package data
Summary: data components for the playbookconfig package.
Group: Data

%description data
data components for the playbookconfig package.


%prep
%setup -q -n playbookconfig-1.0
%patch1 -p1

%build
## build_prepend content
%define local_stx_ansible_dir %{_datadir}/ansible/stx-ansible
%define local_etc_ansible /usr/local/etc/ansible
%define debug_package %{nil}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568875520
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568875520
rm -rf %{buildroot}
%make_install
## install_append content
make install DESTDIR=%{buildroot}%{_datadir}/ansible/stx-ansible
%post
cp %{local_stx_ansible_dir}/playbooks/ansible.cfg %{local_etc_ansible}
cp %{local_stx_ansible_dir}/playbooks/hosts %{local_etc_ansible}
chmod 644 %{local_etc_ansible}/ansible.cfg
chmod 644 %{local_etc_ansible}/hosts
## install_append end

%files
%defattr(-,root,root,-)
/playbooks/ansible.cfg
/playbooks/backup-restore/backup.yml
/playbooks/backup-restore/host_vars/default.yml
/playbooks/backup-restore/restore_openstack.yml
/playbooks/backup-restore/roles/backup/backup-system/files/fm_alarm.py
/playbooks/backup-restore/roles/backup/backup-system/tasks/main.yml
/playbooks/backup-restore/roles/backup/backup-system/vars/main.yml
/playbooks/backup-restore/roles/backup/prepare-env/tasks/main.yml
/playbooks/backup-restore/roles/backup/prepare-env/vars/main.yml
/playbooks/backup-restore/roles/common/tasks/main.yml
/playbooks/backup-restore/roles/restore-openstack/restore/tasks/main.yml
/playbooks/backup-restore/roles/restore-openstack/restore/vars/main.yml
/playbooks/bootstrap/bootstrap.yml
/playbooks/bootstrap/host_vars/default.yml
/playbooks/bootstrap/restore_platform.yml
/playbooks/bootstrap/roles/apply-bootstrap-manifest/defaults/main.yml
/playbooks/bootstrap/roles/apply-bootstrap-manifest/tasks/main.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/bringup_flock_services.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/bringup_helm.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/bringup_kubemaster.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/load_images_from_archive.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/main.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/refresh_local_dns.yml
/playbooks/bootstrap/roles/bringup-essential-services/tasks/setup_registry_certificate_and_keys.yml
/playbooks/bootstrap/roles/bringup-essential-services/templates/calico-cni.yaml.j2
/playbooks/bootstrap/roles/bringup-essential-services/templates/kubelet.conf.j2
/playbooks/bootstrap/roles/bringup-essential-services/templates/multus-cni.yaml.j2
/playbooks/bootstrap/roles/bringup-essential-services/templates/sriov-cni.yaml.j2
/playbooks/bootstrap/roles/bringup-essential-services/templates/sriov-plugin.yaml.j2
/playbooks/bootstrap/roles/bringup-essential-services/vars/main.yml
/playbooks/bootstrap/roles/persist-config/files/populate_initial_config.py
/playbooks/bootstrap/roles/persist-config/tasks/main.yml
/playbooks/bootstrap/roles/persist-config/tasks/one_time_config_tasks.yml
/playbooks/bootstrap/roles/persist-config/tasks/shutdown_services.yml
/playbooks/bootstrap/roles/persist-config/tasks/update_sysinv_database.yml
/playbooks/bootstrap/roles/persist-config/vars/main.yml
/playbooks/bootstrap/roles/prepare-env/files/check_root_disk_size.py
/playbooks/bootstrap/roles/prepare-env/handlers/main.yml
/playbooks/bootstrap/roles/prepare-env/tasks/main.yml
/playbooks/bootstrap/roles/prepare-env/tasks/restore_prep_tasks.yml
/playbooks/bootstrap/roles/prepare-env/vars/main.yml
/playbooks/bootstrap/roles/restore-more-data/tasks/main.yml
/playbooks/bootstrap/roles/restore-more-data/vars/main.yml
/playbooks/bootstrap/roles/store-passwd/tasks/main.yml
/playbooks/bootstrap/roles/store-passwd/vars/main.yml
/playbooks/bootstrap/roles/validate-config/meta/main.yml
/playbooks/bootstrap/roles/validate-config/tasks/main.yml
/playbooks/bootstrap/roles/validate-config/tasks/validate_address.yml
/playbooks/bootstrap/roles/validate-config/tasks/validate_address_range.yml
/playbooks/bootstrap/roles/validate-config/tasks/validate_url.yml
/playbooks/bootstrap/roles/validate-config/vars/main.yml
/playbooks/hosts

%files data
%defattr(-,root,root,-)
/usr/share/ansible/stx-ansible/playbooks/ansible.cfg
/usr/share/ansible/stx-ansible/playbooks/backup-restore/backup.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/host_vars/default.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/restore_openstack.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/backup/backup-system/files/fm_alarm.py
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/backup/backup-system/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/backup/backup-system/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/backup/prepare-env/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/backup/prepare-env/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/common/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/restore-openstack/restore/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/backup-restore/roles/restore-openstack/restore/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/bootstrap.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/host_vars/default.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/restore_platform.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/apply-bootstrap-manifest/defaults/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/apply-bootstrap-manifest/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/bringup_flock_services.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/bringup_helm.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/bringup_kubemaster.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/load_images_from_archive.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/refresh_local_dns.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/tasks/setup_registry_certificate_and_keys.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/templates/calico-cni.yaml.j2
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/templates/kubelet.conf.j2
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/templates/multus-cni.yaml.j2
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/templates/sriov-cni.yaml.j2
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/templates/sriov-plugin.yaml.j2
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/bringup-essential-services/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/persist-config/files/populate_initial_config.py
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/persist-config/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/persist-config/tasks/one_time_config_tasks.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/persist-config/tasks/shutdown_services.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/persist-config/tasks/update_sysinv_database.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/persist-config/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/prepare-env/files/check_root_disk_size.py
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/prepare-env/handlers/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/prepare-env/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/prepare-env/tasks/restore_prep_tasks.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/prepare-env/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/restore-more-data/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/restore-more-data/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/store-passwd/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/store-passwd/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/validate-config/meta/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/validate-config/tasks/main.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/validate-config/tasks/validate_address.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/validate-config/tasks/validate_address_range.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/validate-config/tasks/validate_url.yml
/usr/share/ansible/stx-ansible/playbooks/bootstrap/roles/validate-config/vars/main.yml
/usr/share/ansible/stx-ansible/playbooks/hosts
