#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openssh-config
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/openssh-config-1.0.tar.gz
Source0  : file:///home/clear/tar/openssh-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: openssh-config-data = %{version}-%{release}
Requires: openssh-config-services = %{version}-%{release}
Requires: bin/systemctl
Requires: openssh-clients
Requires: openssh-server
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%package data
Summary: data components for the openssh-config package.
Group: Data

%description data
data components for the openssh-config package.


%package services
Summary: services components for the openssh-config package.
Group: Systemd services

%description services
services components for the openssh-config package.


%prep
%setup -q -n openssh-config-1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568691097
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568691097
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir /usr/local/etc
%define _unitdir /usr/lib/systemd/system
## install_prepend end
%{__install} -d  %{buildroot}%{_datadir}/starlingx
## install_append content
%{__install} -d  %{buildroot}%{_sysconfdir}/systemd/system
%{__install} -m 644 sshd.service  %{buildroot}%{_sysconfdir}/systemd/system/sshd.service
%{__install} -m 644 ssh_config    %{buildroot}%{_datadir}/starlingx/ssh_config
%{__install} -m 600 sshd_config   %{buildroot}%{_datadir}/starlingx/sshd_config
install -d -m 755 %{buildroot}%{_unitdir}
install -m 644 sshd.service %{buildroot}%{_unitdir}/sshd.service
%post
if [ $1 -eq 1 ] ; then
cp -f %{_datadir}/starlingx/ssh_config  %{_sysconfdir}/ssh/ssh_config
cp -f %{_datadir}/starlingx/sshd_config %{_sysconfdir}/ssh/sshd_config
fi
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/systemd/system/sshd.service

%files data
%defattr(-,root,root,-)
/usr/share/starlingx/ssh_config
/usr/share/starlingx/sshd_config

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/sshd.service
