#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-puppi
Version  : 1
Release  : 1
URL      : file:///home/clr/stx-tar/puppi-c1c47f4edfd761d1bbde32a75da0c3fa7cc93a81.tar.gz
Source0  : file:///home/clr/stx-tar/puppi-c1c47f4edfd761d1bbde32a75da0c3fa7cc93a81.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-puppi-data = %{version}-%{release}
BuildRequires : python-dev
Patch1: 0001-add-makefile.patch

%description
In this directory you find some examples of deploy procedures
for general purposes deploys (single wars, single files, tarballs, list
of files from a list...) described in a single define.

%package data
Summary: data components for the puppet-puppi package.
Group: Data

%description data
data components for the puppet-puppi package.


%prep
%setup -q -n puppi-master
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568711340
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568711340
rm -rf %{buildroot}
install -d -m 0755 %{buildroot}/%{_datadir}/puppet/modules/puppi
## install_append content
cp -R ../puppi-master/* %{buildroot}/%{_datadir}/puppet/modules/puppi/.
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/puppi/Gemfile
/usr/share/puppet/modules/puppi/LICENSE
/usr/share/puppet/modules/puppi/Makefile
/usr/share/puppet/modules/puppi/README.md
/usr/share/puppet/modules/puppi/README_check.md
/usr/share/puppet/modules/puppi/README_deploy.md
/usr/share/puppet/modules/puppi/README_info.md
/usr/share/puppet/modules/puppi/README_log.md
/usr/share/puppet/modules/puppi/Rakefile
/usr/share/puppet/modules/puppi/files/info/readme/readme
/usr/share/puppet/modules/puppi/files/info/readme/readme-default
/usr/share/puppet/modules/puppi/files/mailpuppicheck
/usr/share/puppet/modules/puppi/files/mcollective/mc-puppi
/usr/share/puppet/modules/puppi/files/mcollective/puppi.ddl
/usr/share/puppet/modules/puppi/files/mcollective/puppi.rb
/usr/share/puppet/modules/puppi/files/mcollective/puppicheck
/usr/share/puppet/modules/puppi/files/mcollective/puppideploy
/usr/share/puppet/modules/puppi/files/scripts/archive.sh
/usr/share/puppet/modules/puppi/files/scripts/check_project.sh
/usr/share/puppet/modules/puppi/files/scripts/checkwardir.sh
/usr/share/puppet/modules/puppi/files/scripts/clean_filelist.sh
/usr/share/puppet/modules/puppi/files/scripts/database.sh
/usr/share/puppet/modules/puppi/files/scripts/delete.sh
/usr/share/puppet/modules/puppi/files/scripts/deploy.sh
/usr/share/puppet/modules/puppi/files/scripts/deploy_files.sh
/usr/share/puppet/modules/puppi/files/scripts/execute.sh
/usr/share/puppet/modules/puppi/files/scripts/firewall.sh
/usr/share/puppet/modules/puppi/files/scripts/functions
/usr/share/puppet/modules/puppi/files/scripts/get_file.sh
/usr/share/puppet/modules/puppi/files/scripts/get_filesfromlist.sh
/usr/share/puppet/modules/puppi/files/scripts/get_maven_files.sh
/usr/share/puppet/modules/puppi/files/scripts/get_metadata.sh
/usr/share/puppet/modules/puppi/files/scripts/git.sh
/usr/share/puppet/modules/puppi/files/scripts/header
/usr/share/puppet/modules/puppi/files/scripts/hg.sh
/usr/share/puppet/modules/puppi/files/scripts/predeploy.sh
/usr/share/puppet/modules/puppi/files/scripts/predeploy_tar.sh
/usr/share/puppet/modules/puppi/files/scripts/report_mail.sh
/usr/share/puppet/modules/puppi/files/scripts/report_mongo.sh
/usr/share/puppet/modules/puppi/files/scripts/service.sh
/usr/share/puppet/modules/puppi/files/scripts/svn.sh
/usr/share/puppet/modules/puppi/files/scripts/wait.sh
/usr/share/puppet/modules/puppi/files/scripts/yant.sh
/usr/share/puppet/modules/puppi/files/scripts/yum.sh
/usr/share/puppet/modules/puppi/lib/facter/last_run.rb
/usr/share/puppet/modules/puppi/lib/facter/puppi_projects.rb
/usr/share/puppet/modules/puppi/lib/facter/windows_common_appdata.rb
/usr/share/puppet/modules/puppi/lib/puppet/functions/params_lookup.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/bool2ensure.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/get_class_args.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/get_magicvar.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/get_module_path.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/nslookup.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/options_lookup.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/params_lookup.rb
/usr/share/puppet/modules/puppi/lib/puppet/parser/functions/url_parse.rb
/usr/share/puppet/modules/puppi/manifests/check.pp
/usr/share/puppet/modules/puppi/manifests/configure.pp
/usr/share/puppet/modules/puppi/manifests/dependencies.pp
/usr/share/puppet/modules/puppi/manifests/deploy.pp
/usr/share/puppet/modules/puppi/manifests/extras.pp
/usr/share/puppet/modules/puppi/manifests/helper.pp
/usr/share/puppet/modules/puppi/manifests/helpers.pp
/usr/share/puppet/modules/puppi/manifests/info.pp
/usr/share/puppet/modules/puppi/manifests/info/instance.pp
/usr/share/puppet/modules/puppi/manifests/info/module.pp
/usr/share/puppet/modules/puppi/manifests/info/readme.pp
/usr/share/puppet/modules/puppi/manifests/init.pp
/usr/share/puppet/modules/puppi/manifests/initialize.pp
/usr/share/puppet/modules/puppi/manifests/install_packages.pp
/usr/share/puppet/modules/puppi/manifests/log.pp
/usr/share/puppet/modules/puppi/manifests/mcollective/client.pp
/usr/share/puppet/modules/puppi/manifests/mcollective/server.pp
/usr/share/puppet/modules/puppi/manifests/netinstall.pp
/usr/share/puppet/modules/puppi/manifests/one.pp
/usr/share/puppet/modules/puppi/manifests/params.pp
/usr/share/puppet/modules/puppi/manifests/project.pp
/usr/share/puppet/modules/puppi/manifests/project/README
/usr/share/puppet/modules/puppi/manifests/project/archive.pp
/usr/share/puppet/modules/puppi/manifests/project/builder.pp
/usr/share/puppet/modules/puppi/manifests/project/dir.pp
/usr/share/puppet/modules/puppi/manifests/project/files.pp
/usr/share/puppet/modules/puppi/manifests/project/git.pp
/usr/share/puppet/modules/puppi/manifests/project/hg.pp
/usr/share/puppet/modules/puppi/manifests/project/maven.pp
/usr/share/puppet/modules/puppi/manifests/project/mysql.pp
/usr/share/puppet/modules/puppi/manifests/project/service.pp
/usr/share/puppet/modules/puppi/manifests/project/svn.pp
/usr/share/puppet/modules/puppi/manifests/project/tar.pp
/usr/share/puppet/modules/puppi/manifests/project/war.pp
/usr/share/puppet/modules/puppi/manifests/project/y4maven.pp
/usr/share/puppet/modules/puppi/manifests/project/yum.pp
/usr/share/puppet/modules/puppi/manifests/report.pp
/usr/share/puppet/modules/puppi/manifests/rollback.pp
/usr/share/puppet/modules/puppi/manifests/run.pp
/usr/share/puppet/modules/puppi/manifests/runscript.pp
/usr/share/puppet/modules/puppi/manifests/skel.pp
/usr/share/puppet/modules/puppi/manifests/todo.pp
/usr/share/puppet/modules/puppi/manifests/two.pp
/usr/share/puppet/modules/puppi/manifests/ze.pp
/usr/share/puppet/modules/puppi/metadata.json
/usr/share/puppet/modules/puppi/spec/classes/puppi_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_check_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_deploy_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_helper_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_info_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_initialize_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_log_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_project_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_report_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_rollback_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_run_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_todo_spec.rb
/usr/share/puppet/modules/puppi/spec/defines/puppi_ze_spec.rb
/usr/share/puppet/modules/puppi/spec/functions/any2bool_spec.rb
/usr/share/puppet/modules/puppi/spec/functions/bool2ensure_spec.rb
/usr/share/puppet/modules/puppi/spec/functions/url_parse_spec.rb
/usr/share/puppet/modules/puppi/spec/spec_helper.rb
/usr/share/puppet/modules/puppi/templates/helpers/standard.yml.erb
/usr/share/puppet/modules/puppi/templates/info.erb
/usr/share/puppet/modules/puppi/templates/info/instance.erb
/usr/share/puppet/modules/puppi/templates/info/module.erb
/usr/share/puppet/modules/puppi/templates/info/puppet.erb
/usr/share/puppet/modules/puppi/templates/info/readme.erb
/usr/share/puppet/modules/puppi/templates/install_packages.erb
/usr/share/puppet/modules/puppi/templates/log.erb
/usr/share/puppet/modules/puppi/templates/project/config.erb
/usr/share/puppet/modules/puppi/templates/puppi.conf.erb
/usr/share/puppet/modules/puppi/templates/puppi.erb
/usr/share/puppet/modules/puppi/templates/puppi_clean.erb
/usr/share/puppet/modules/puppi/templates/todo.erb
