#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pm-qos-mgr
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/pm-qos-mgr-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/pm-qos-mgr-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: pm-qos-mgr-bin = %{version}-%{release}
Requires: pm-qos-mgr-python = %{version}-%{release}
Requires: pm-qos-mgr-python3 = %{version}-%{release}
Requires: pm-qos-mgr-services = %{version}-%{release}
Requires: Pinotify
Requires: pbr >= 2.0.0
Requires: systemd
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : git
BuildRequires : pbr
BuildRequires : pip
BuildRequires : setuptools
BuildRequires : systemd-devel

%description
No detailed description available

%package bin
Summary: bin components for the pm-qos-mgr package.
Group: Binaries
Requires: pm-qos-mgr-services = %{version}-%{release}

%description bin
bin components for the pm-qos-mgr package.


%package doc
Summary: doc components for the pm-qos-mgr package.
Group: Documentation

%description doc
doc components for the pm-qos-mgr package.


%package python
Summary: python components for the pm-qos-mgr package.
Group: Default
Requires: pm-qos-mgr-python3 = %{version}-%{release}

%description python
python components for the pm-qos-mgr package.


%package python3
Summary: python3 components for the pm-qos-mgr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pm-qos-mgr package.


%package services
Summary: services components for the pm-qos-mgr package.
Group: Systemd services

%description services
services components for the pm-qos-mgr package.


%prep
%setup -q -n pm-qos-mgr-1.0

%build
## build_prepend content
export PBR_VERSION=%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568864471
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
rm -rf *.egg-info
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
%define pythonroot %{_libdir}/python2.7/site-packages
%define _unitdir /usr/lib/systemd/system/
export PBR_VERSION=%{version}
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
%{__python} setup.py install --root=%{buildroot} \
--install-lib=%{pythonroot} \
--prefix=%{_prefix} \
--install-data=%{_datadir} \
--single-version-externally-managed
install -p -D -m 664 pm-qos-mgr.service %{buildroot}%{_unitdir}/pm-qos-mgr.service
mkdir -p %{buildroot}%{_defaultdocdir}/%{name}-%{version}
install -m 644 LICENSE %{buildroot}%{_defaultdocdir}/%{name}-%{version}
%post
systemctl enable pm-qos-mgr.service
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pm-qos-mgr

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/pm-qos-mgr-1.0/LICENSE

%files python
%defattr(-,root,root,-)
/usr/lib64/python*/*

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/pm-qos-mgr.service
