#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : starlingx-dashboard
Version  : 1.0
Release  : 1
URL      : file:///home/clr/stx-tar/starlingx-dashboard-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/starlingx-dashboard-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: starlingx-dashboard-data = %{version}-%{release}
Requires: starlingx-dashboard-python = %{version}-%{release}
Requires: starlingx-dashboard-python3 = %{version}-%{release}
Requires: pbr
Requires: python-django-horizon
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : setuptools

%description
No detailed description available

%package data
Summary: data components for the starlingx-dashboard package.
Group: Data

%description data
data components for the starlingx-dashboard package.


%package python
Summary: python components for the starlingx-dashboard package.
Group: Default
Requires: starlingx-dashboard-python3 = %{version}-%{release}

%description python
python components for the starlingx-dashboard package.


%package python3
Summary: python3 components for the starlingx-dashboard package.
Group: Default
Requires: python3-core

%description python3
python3 components for the starlingx-dashboard package.


%prep
%setup -q -n starlingx-dashboard-1.0

%build
## build_prepend content
%define py_pkg_name          starlingx_dashboard
%define enabled_dir          %{_datadir}/openstack-dashboard/openstack_dashboard/enabled/
%define stx_themes_dir       %{_datadir}/openstack-dashboard/openstack_dashboard/themes/starlingx/
%define local_settings_dir   %{_datadir}/openstack-dashboard/openstack_dashboard/local/local_settings.d
%define debug_package %{nil}
export PBR_VERSION=%{version}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570516050
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
echo "dont need check"
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
## install_prepend content
export PBR_VERSION=%{version}
## install_prepend end
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -d -m 755 %{buildroot}%{enabled_dir}
install -p -D -m 755 %{py_pkg_name}/enabled/* %{buildroot}%{enabled_dir}
install -d -m 755 %{buildroot}%{stx_themes_dir}
cp -R %{py_pkg_name}/themes/starlingx/* %{buildroot}%{stx_themes_dir}
chmod -R 755 %{buildroot}%{stx_themes_dir}/*
install -d -m 755 %{buildroot}%{local_settings_dir}
install -p -D -m 755 %{py_pkg_name}/local/local_settings.d/* %{buildroot}%{local_settings_dir}
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_1001_starlingx.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2002_starlingx_admin_default.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2005_starlingx_admin_platform_panel_group.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2034_starlingx_platform_software_management_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2035_starlingx_admin_inventory_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2036_starlingx_admin_providernets.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2037_starlingx_admin_host_topology_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2038_starlingx_platform_storage_overview_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2039_starlingx_admin_system_config.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2200_starlingx_dc_admin.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2211_starlingx_dc_admin_cloud_overview_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2212_WRS_dc_admin_software_management_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2400_starlingx_admin_fault_management_panel_group.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2401_starlingx_admin_fault_management_alarms_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2402_starlingx_admin_fault_management_events_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2403_starlingx_admin_fault_management_events_suppression_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2823_starlingx_disable_defaults_panel.py
/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2841_starlingx_admin_info_panel_tabs.py
/usr/share/openstack-dashboard/openstack_dashboard/local/local_settings.d/_30_stx_local_settings.py
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/_styles.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/_variables.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/components/_badges.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/components/_charts.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/components/_sidebar.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/components/_splash.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/components/_tables.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/components/_topbar.scss
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/img/favicon.png
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/img/logo-splash.svg
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/static/img/logo.png
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/templates/500.html
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/templates/_stylesheets.html
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/templates/header/_brand.html
/usr/share/openstack-dashboard/openstack_dashboard/themes/starlingx/templates/header/_user_menu.html

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
