#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : puppet-manifests
Version  : 1.0.0
Release  : 2
URL      : file:///home/clr/stx-tar/puppet-manifests-1.0.0.tar.gz
Source0  : file:///home/clr/stx-tar/puppet-manifests-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: puppet-manifests-data = %{version}-%{release}
Requires: puppet-barbican
Requires: puppet-boolean
Requires: puppet-ceph
Requires: puppet-certmonger
Requires: puppet-collectd
Requires: puppet-concat
Requires: puppet-create_resources
Requires: puppet-dcdbsync
Requires: puppet-dcmanager
Requires: puppet-dcorch
Requires: puppet-dnsmasq
Requires: puppet-drbd
Requires: puppet-etcd
Requires: puppet-filemapper
Requires: puppet-firewall
Requires: puppet-fm
Requires: puppet-haproxy
Requires: puppet-horizon
Requires: puppet-inifile
Requires: puppet-keystone
Requires: puppet-kmod
Requires: puppet-ldap
Requires: puppet-lvm
Requires: puppet-memcached
Requires: puppet-mtce
Requires: puppet-network
Requires: puppet-nfv
Requires: puppet-nslcd
Requires: puppet-nssdb
Requires: puppet-openstacklib
Requires: puppet-patching
Requires: puppet-postgresql
Requires: puppet-puppi
Requires: puppet-rabbitmq
Requires: puppet-smapi
Requires: puppet-sshd
Requires: puppet-stdlib
Requires: puppet-sysctl
Requires: puppet-sysinv
Requires: puppet-vlan
Requires: puppet-vswitch
Patch1: 0001-fix-Makefile-dir.patch

%description
No detailed description available

%package data
Summary: data components for the puppet-manifests package.
Group: Data

%description data
data components for the puppet-manifests package.


%prep
%setup -q -n puppet-manifests-1.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568785764
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568785764
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir	/usr/local/etc
%define config_dir %{_sysconfdir}/puppet
%define module_dir %{_datadir}/puppet/modules
%define local_bindir /usr/local/bin
## install_prepend end
%make_install
## install_append content
make install BINDIR=%{buildroot}%{local_bindir} CONFIGDIR=%{buildroot}%{config_dir} MODULEDIR=%{buildroot}%{module_dir}
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/bin/apply_network_config.sh
/usr/local/bin/puppet-manifest-apply.sh
/usr/local/etc/puppet/hiera.yaml
/usr/local/etc/puppet/hieradata/controller.yaml
/usr/local/etc/puppet/hieradata/global.yaml
/usr/local/etc/puppet/hieradata/storage.yaml
/usr/local/etc/puppet/hieradata/worker.yaml
/usr/local/etc/puppet/manifests/ansible_bootstrap.pp
/usr/local/etc/puppet/manifests/bootstrap.pp
/usr/local/etc/puppet/manifests/controller.pp
/usr/local/etc/puppet/manifests/runtime.pp
/usr/local/etc/puppet/manifests/storage.pp
/usr/local/etc/puppet/manifests/upgrade.pp
/usr/local/etc/puppet/manifests/worker.pp

%files data
%defattr(-,root,root,-)
/usr/share/puppet/modules/openstack/manifests/barbican.pp
/usr/share/puppet/modules/openstack/manifests/horizon.pp
/usr/share/puppet/modules/openstack/manifests/keystone.pp
/usr/share/puppet/modules/openstack/templates/barbican-api-logrotate.erb
/usr/share/puppet/modules/openstack/templates/cinder-lvm-simplex.erb
/usr/share/puppet/modules/openstack/templates/horizon-params.erb
/usr/share/puppet/modules/openstack/templates/horizon-region-config.erb
/usr/share/puppet/modules/openstack/templates/keystone-defaultregion-filter.erb
/usr/share/puppet/modules/openstack/templates/keystone-defaultregion.erb
/usr/share/puppet/modules/openstack/templates/keystone-extra.conf.erb
/usr/share/puppet/modules/openstack/templates/keystone-policy.json.erb
/usr/share/puppet/modules/openstack/templates/keystone-systemcontroller-filter.erb
/usr/share/puppet/modules/openstack/templates/keystone-systemcontroller.erb
/usr/share/puppet/modules/openstack/templates/lighttpd-inc.conf.erb
/usr/share/puppet/modules/openstack/templates/lighttpd.conf.erb
/usr/share/puppet/modules/platform/files/docker-distribution
/usr/share/puppet/modules/platform/files/etcd
/usr/share/puppet/modules/platform/files/etcd-override.conf
/usr/share/puppet/modules/platform/files/kubeconfig.sh
/usr/share/puppet/modules/platform/files/ldap.cgcs-shell.ldif
/usr/share/puppet/modules/platform/files/registry-token-server
/usr/share/puppet/modules/platform/lib/facter/boot_disk_device_path.rb
/usr/share/puppet/modules/platform/lib/facter/configured_ceph_monitors.rb
/usr/share/puppet/modules/platform/lib/facter/controller_sw_versions_match.rb
/usr/share/puppet/modules/platform/lib/facter/disable_worker_services.rb
/usr/share/puppet/modules/platform/lib/facter/get_cmdline.rb
/usr/share/puppet/modules/platform/lib/facter/install_uuid.rb
/usr/share/puppet/modules/platform/lib/facter/is_broadwell_processor.rb
/usr/share/puppet/modules/platform/lib/facter/is_controller_active.rb
/usr/share/puppet/modules/platform/lib/facter/is_gb_page_supported.rb
/usr/share/puppet/modules/platform/lib/facter/is_hugetlbfs_enabled.rb
/usr/share/puppet/modules/platform/lib/facter/is_initial_config.rb
/usr/share/puppet/modules/platform/lib/facter/is_initial_config_primary.rb
/usr/share/puppet/modules/platform/lib/facter/is_initial_k8s_config.rb
/usr/share/puppet/modules/platform/lib/facter/is_keystone_running.rb
/usr/share/puppet/modules/platform/lib/facter/is_node_ceph_configured.rb
/usr/share/puppet/modules/platform/lib/facter/is_per_numa_supported.rb
/usr/share/puppet/modules/platform/lib/facter/is_primary_disk_rotational.rb
/usr/share/puppet/modules/platform/lib/facter/is_resctrl_supported.rb
/usr/share/puppet/modules/platform/lib/facter/is_restore_in_progress.rb
/usr/share/puppet/modules/platform/lib/facter/is_standalone_controller.rb
/usr/share/puppet/modules/platform/lib/facter/number_of_logical_cpus.rb
/usr/share/puppet/modules/platform/lib/facter/number_of_numa_nodes.rb
/usr/share/puppet/modules/platform/lib/facter/physical_core_count.rb
/usr/share/puppet/modules/platform/lib/facter/platform_res_mem.rb
/usr/share/puppet/modules/platform/lib/facter/system_info.rb
/usr/share/puppet/modules/platform/lib/puppet/parser/functions/check_grub_config.rb
/usr/share/puppet/modules/platform/manifests/amqp.pp
/usr/share/puppet/modules/platform/manifests/anchors.pp
/usr/share/puppet/modules/platform/manifests/ceph.pp
/usr/share/puppet/modules/platform/manifests/client.pp
/usr/share/puppet/modules/platform/manifests/collectd.pp
/usr/share/puppet/modules/platform/manifests/compute.pp
/usr/share/puppet/modules/platform/manifests/config.pp
/usr/share/puppet/modules/platform/manifests/dcdbsync.pp
/usr/share/puppet/modules/platform/manifests/dcmanager.pp
/usr/share/puppet/modules/platform/manifests/dcorch.pp
/usr/share/puppet/modules/platform/manifests/devices.pp
/usr/share/puppet/modules/platform/manifests/dhclient.pp
/usr/share/puppet/modules/platform/manifests/dns.pp
/usr/share/puppet/modules/platform/manifests/docker.pp
/usr/share/puppet/modules/platform/manifests/dockerdistribution.pp
/usr/share/puppet/modules/platform/manifests/drbd.pp
/usr/share/puppet/modules/platform/manifests/etcd.pp
/usr/share/puppet/modules/platform/manifests/exports.pp
/usr/share/puppet/modules/platform/manifests/filesystem.pp
/usr/share/puppet/modules/platform/manifests/firewall.pp
/usr/share/puppet/modules/platform/manifests/fm.pp
/usr/share/puppet/modules/platform/manifests/fstab.pp
/usr/share/puppet/modules/platform/manifests/grub.pp
/usr/share/puppet/modules/platform/manifests/haproxy.pp
/usr/share/puppet/modules/platform/manifests/helm.pp
/usr/share/puppet/modules/platform/manifests/influxdb.pp
/usr/share/puppet/modules/platform/manifests/kubernetes.pp
/usr/share/puppet/modules/platform/manifests/ldap.pp
/usr/share/puppet/modules/platform/manifests/lldp.pp
/usr/share/puppet/modules/platform/manifests/lvm.pp
/usr/share/puppet/modules/platform/manifests/memcached.pp
/usr/share/puppet/modules/platform/manifests/mtce.pp
/usr/share/puppet/modules/platform/manifests/multipath.pp
/usr/share/puppet/modules/platform/manifests/network.pp
/usr/share/puppet/modules/platform/manifests/nfv.pp
/usr/share/puppet/modules/platform/manifests/ntp.pp
/usr/share/puppet/modules/platform/manifests/params.pp
/usr/share/puppet/modules/platform/manifests/partitions.pp
/usr/share/puppet/modules/platform/manifests/password.pp
/usr/share/puppet/modules/platform/manifests/patching.pp
/usr/share/puppet/modules/platform/manifests/pciirqaffinity.pp
/usr/share/puppet/modules/platform/manifests/postgresql.pp
/usr/share/puppet/modules/platform/manifests/ptp.pp
/usr/share/puppet/modules/platform/manifests/remotelogging.pp
/usr/share/puppet/modules/platform/manifests/scratch.pp
/usr/share/puppet/modules/platform/manifests/sm.pp
/usr/share/puppet/modules/platform/manifests/smapi.pp
/usr/share/puppet/modules/platform/manifests/snmp.pp
/usr/share/puppet/modules/platform/manifests/sysctl.pp
/usr/share/puppet/modules/platform/manifests/sysinv.pp
/usr/share/puppet/modules/platform/manifests/users.pp
/usr/share/puppet/modules/platform/manifests/vswitch.pp
/usr/share/puppet/modules/platform/manifests/worker.pp
/usr/share/puppet/modules/platform/templates/calico.yaml.erb
/usr/share/puppet/modules/platform/templates/calico.yaml.erb.orig
/usr/share/puppet/modules/platform/templates/calico_oam_if_gnp.yaml.erb
/usr/share/puppet/modules/platform/templates/calico_oam_if_hep.yaml.erb
/usr/share/puppet/modules/platform/templates/ceph.journal.location.erb
/usr/share/puppet/modules/platform/templates/ceph.journal.partitions.erb
/usr/share/puppet/modules/platform/templates/ceph.osd.create.erb
/usr/share/puppet/modules/platform/templates/collectd.conf.erb
/usr/share/puppet/modules/platform/templates/compute_extend.conf.erb
/usr/share/puppet/modules/platform/templates/dhclient.conf.erb
/usr/share/puppet/modules/platform/templates/dnsmasq.conf.erb
/usr/share/puppet/modules/platform/templates/dockerdistribution.conf.erb
/usr/share/puppet/modules/platform/templates/dockerproxy.conf.erb
/usr/share/puppet/modules/platform/templates/fm.snmp.conf.erb
/usr/share/puppet/modules/platform/templates/get-secret-payload.erb
/usr/share/puppet/modules/platform/templates/influxdb.conf.erb
/usr/share/puppet/modules/platform/templates/insecuredockerregistry.conf.erb
/usr/share/puppet/modules/platform/templates/kube-stx-override.conf.erb
/usr/share/puppet/modules/platform/templates/kubeadm.yaml.erb
/usr/share/puppet/modules/platform/templates/kubelet-pmond-conf.erb
/usr/share/puppet/modules/platform/templates/kubelet.conf.erb
/usr/share/puppet/modules/platform/templates/kvm_timer_advance.conf.erb
/usr/share/puppet/modules/platform/templates/ldap.conf.erb
/usr/share/puppet/modules/platform/templates/ldapscripts.conf.erb
/usr/share/puppet/modules/platform/templates/lldp.conf.erb
/usr/share/puppet/modules/platform/templates/lldpd.default.erb
/usr/share/puppet/modules/platform/templates/logrotate.erb
/usr/share/puppet/modules/platform/templates/multipath.conf.erb
/usr/share/puppet/modules/platform/templates/multus.yaml.erb
/usr/share/puppet/modules/platform/templates/nslcd.conf.erb
/usr/share/puppet/modules/platform/templates/ntp.conf.client.erb
/usr/share/puppet/modules/platform/templates/ntp.conf.server.erb
/usr/share/puppet/modules/platform/templates/ntp.override.erb
/usr/share/puppet/modules/platform/templates/ntp.pmon.conf.erb
/usr/share/puppet/modules/platform/templates/ntp_initial.conf.client.erb
/usr/share/puppet/modules/platform/templates/ntp_initial.conf.server.erb
/usr/share/puppet/modules/platform/templates/openrc.admin.erb
/usr/share/puppet/modules/platform/templates/ovs.add-bridge.erb
/usr/share/puppet/modules/platform/templates/ovs.add-flow.erb
/usr/share/puppet/modules/platform/templates/ovs.add-port.erb
/usr/share/puppet/modules/platform/templates/ovs.clean.erb
/usr/share/puppet/modules/platform/templates/ovs.disable-dpdk-init.erb
/usr/share/puppet/modules/platform/templates/ovsdb.clean.erb
/usr/share/puppet/modules/platform/templates/pam.passwd.erb
/usr/share/puppet/modules/platform/templates/partitions.manage.erb
/usr/share/puppet/modules/platform/templates/pci-irq-affinity.conf.erb
/usr/share/puppet/modules/platform/templates/pcidp.conf.erb
/usr/share/puppet/modules/platform/templates/phc2sys.erb
/usr/share/puppet/modules/platform/templates/phc2sys.service.erb
/usr/share/puppet/modules/platform/templates/ptp4l.conf.erb
/usr/share/puppet/modules/platform/templates/ptp4l.erb
/usr/share/puppet/modules/platform/templates/ptp4l.service.erb
/usr/share/puppet/modules/platform/templates/registry-cert-extfile.erb
/usr/share/puppet/modules/platform/templates/registry-token-server.conf.erb
/usr/share/puppet/modules/platform/templates/remotelogging.conf.erb
/usr/share/puppet/modules/platform/templates/resolv.conf.erb
/usr/share/puppet/modules/platform/templates/sm-api.conf.erb
/usr/share/puppet/modules/platform/templates/snmpd.conf.erb
/usr/share/puppet/modules/platform/templates/sriov-cni.yaml.erb
/usr/share/puppet/modules/platform/templates/sriov.bind-device.erb
/usr/share/puppet/modules/platform/templates/sriovdp-daemonset.yaml.erb
/usr/share/puppet/modules/platform/templates/systemd-system-cpuaffinity.conf.erb
/usr/share/puppet/modules/platform/templates/worker_reserved.conf.erb
