#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spectre-meltdown-checker
Version  : 0.37+.5cc77741
Release  : 1
URL      : file:///home/clr/stx-tar/spectre-meltdown-checker-0.37+-5cc77741.tar.gz
Source0  : file:///home/clr/stx-tar/spectre-meltdown-checker-0.37+-5cc77741.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: spectre-meltdown-checker-bin = %{version}-%{release}
Requires: bash
Patch1: 0001-add-makefile.patch

%description
Spectre & Meltdown Checker
==========================
A shell script to tell if your system is vulnerable against the 3 "speculative execution" CVEs that were made public early 2018.

%package bin
Summary: bin components for the spectre-meltdown-checker package.
Group: Binaries

%description bin
bin components for the spectre-meltdown-checker package.


%prep
%setup -q -n spectre-meltdown-checker
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568602222
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568602222
rm -rf %{buildroot}
install -d -m 755 %{buildroot}/usr/sbin/
## install_append content
tar -xzvf %{SOURCE0}
install -m 744 spectre-meltdown-checker/spectre-meltdown-checker.sh %{buildroot}/usr/sbin/spectre-meltdown-checker.sh
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/sbin/spectre-meltdown-checker.sh
