#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : update-motd
Version  : 1.0
Release  : 2
URL      : file:///home/clr/stx-tar/update-motd-1.0.tar.gz
Source0  : file:///home/clr/stx-tar/update-motd-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: update-motd-bin = %{version}-%{release}
Requires: crontabs
Patch1: 0001-add-makefile.patch

%description
No detailed description available

%package bin
Summary: bin components for the update-motd package.
Group: Binaries

%description bin
bin components for the update-motd package.


%prep
%setup -q -n update-motd-1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568190137
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568190137
rm -rf %{buildroot}
## install_prepend content
%define _sysconfdir	/usr/local/etc
## install_prepend end
install -d %{buildroot}%{_sbindir}
## install_append content
install -m 700 motd-update %{buildroot}%{_sbindir}/motd-update
install -d %{buildroot}%{_sysconfdir}
install -d %{buildroot}%{_sysconfdir}/motd.d
install -m 755 motd-header %{buildroot}%{_sysconfdir}/motd.d/00-header
install -m 755 motd-footer %{buildroot}%{_sysconfdir}/motd.d/99-footer
install -m 644 motd.head %{buildroot}%{_sysconfdir}/motd.head
install -d %{buildroot}%{_sysconfdir}/cron.d
install -m 600 motd-update.cron %{buildroot}%{_sysconfdir}/cron.d/motd-update
install -m 700 customize-banner %{buildroot}%{_sbindir}/customize-banner
install -m 700 apply_banner_customization %{buildroot}%{_sbindir}/apply_banner_customization
install -m 700 install_banner_customization %{buildroot}%{_sbindir}/install_banner_customization
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/cron.d/motd-update
/usr/local/etc/motd.d/00-header
/usr/local/etc/motd.d/99-footer
/usr/local/etc/motd.head

%files bin
%defattr(-,root,root,-)
/usr/bin/apply_banner_customization
/usr/bin/customize-banner
/usr/bin/install_banner_customization
/usr/bin/motd-update
