#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dhcp-config
Version  : 1.0
Release  : 1
URL      : file:///home/clear/tar/dhcp-config-1.0.tar.gz
Source0  : file:///home/clear/tar/dhcp-config-1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: dhclient
Patch1: 0001-add_makefile.patch

%description
No detailed description available

%prep
%setup -q -n dhcp-config-1.0
%patch1 -p1

%build
## build_prepend content
%define _sysconfdir /usr/local/etc
%global dhcpconfdir %{_sysconfdir}/dhcp
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568190000
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568190000
rm -rf %{buildroot}
%{__install} -d %{buildroot}%{dhcpconfdir}
## install_append content
%{__install} -p -m 0755 dhclient-enter-hooks %{buildroot}%{dhcpconfdir}/dhclient-enter-hooks
%{__install} -p -m 0644 dhclient.conf %{buildroot}%{dhcpconfdir}/dhclient.conf
ln -s  %{dhcpconfdir}/dhclient-enter-hooks  %{buildroot}%{_sysconfdir}/dhclient-enter-hooks
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/dhclient-enter-hooks
/usr/local/etc/dhcp/dhclient-enter-hooks
/usr/local/etc/dhcp/dhclient.conf
